tensorflow/addons

tensorflow_addons/text/cc/kernels/skip_gram_kernels.cc
tensorflow_addons/text/python/skip_gram_ops_test.py

Issue #12: Fix skip_gram input_tensor check

---

tensorflow_addons/layers/__init__.py
tensorflow_addons/layers/python/wrappers.py
tensorflow_addons/layers/python/wrappers_test.py

This renames the `WeightNorm` wrapper to `WeightNormalization` in order to be consistent with  [`tf.keras.layers.BatchNormalization`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/normalization.py#L774).
See https://github.com/tensorflow/addons/pull/14#discussion_r248224896

Rename WeightNorm -> WeightNormalization

---

tensorflow_addons/layers/BUILD
tensorflow_addons/layers/python/poincare.py
tensorflow_addons/layers/python/poincare_test.py

Implement PoincareNormalize

---

tensorflow_addons/layers/BUILD
tensorflow_addons/layers/__init__.py
tensorflow_addons/layers/python/maxout.py
tensorflow_addons/layers/python/maxout_test.py

Implement Maxout layer

---

README.md

I don't think `bleeding edge` contributions should be a requirement for Addons. Many things in this repo have been around for a while, but are useful to a subset of the community and shouldn't be installed with every TF installation.
Thoughts? Certainly happy to re-word.

Update repository description

---

tensorflow_addons/losses/BUILD
tensorflow_addons/losses/python/metric_learning.py
tensorflow_addons/losses/python/triplet.py
tensorflow_addons/losses/python/triplet_test.py

Implement triplet_semihard_loss

---

tensorflow_addons/layers/BUILD
tensorflow_addons/layers/python/wrappers.py
tensorflow_addons/layers/python/wrappers_test.py
tensorflow_addons/text/BUILD

Various changes to better fit TF2

TF2 WeightNormalization

---

tensorflow_addons/layers/python/wrappers.py

Hotfix for https://github.com/tensorflow/tensorflow/commit/bd36b48c555b2d46c41a179ed9f27a04806e9e66#diff-8eb7e20502209f082d0cb15119a50413

FIX: Rename keras track checkpointable

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
tensorflow_addons/layers/README.md
tensorflow_addons/losses/README.md
tensorflow_addons/optimizers/BUILD
tensorflow_addons/optimizers/README.md
tensorflow_addons/optimizers/python/lazy_adam_optimizer.py

Major doc changes...
* Added project core concepts to central README
* Added table of contents to central README
* Began separate contribution guidelines for each sub-package API
Just a note.. there is a planned PR coming which will place all "custom op" sub-packages under a single API type so that we can have contribution guidelines similar to `layers`, `losses`, and `optimizers`.

Contribution docs

---

README.md
tensorflow_addons/custom_ops/README.md
tensorflow_addons/layers/README.md
tensorflow_addons/losses/README.md
tensorflow_addons/optimizers/README.md

- Update the tables of content
- Add documentation guidelines per API
Just a note: It is understood that updating two tables of content is redundant. After #46 is completed we can remove the central TOC

ENH: Add documentation guidelines

---

README.md

Last doc merge for 0.1 release (already available on PyPi).

DOC: Add pip install

---

tensorflow_addons/custom_ops/image/cc/kernels/image_projective_transform_op.cc
tensorflow_addons/custom_ops/image/cc/ops/image_ops.cc
tensorflow_addons/custom_ops/image/python/transform.py

Rename addon op ImageProjectiveTransform to ImageProjectiveTransformV2.
This ensures the op names are consistent between addon and contrib (see #86).

rename ImageProjectiveTransform to ImageProjectiveTransformV2

---

README.md
tensorflow_addons/layers/python/sparsemax_test.py

Our first catch from nightly CI... but this is kind of an ugly one. 
**Summary:** 
New decorator introcduced in https://github.com/tensorflow/tensorflow/commit/c27909ea80e8823dbf4f7176ab69991a630356a1#diff-f541c00fcae53468339272b7c92a67a4 is causing this test to fail because the decorator is never provided an argument as [seen here](https://source.cloud.google.com/results/invocations/c481cc72-92ab-46d9-90b4-7e9ae40e2626/targets/tensorflow_addons%2Fubuntu%2Fgpu%2Fpy2%2Fcontinuous/log)
I believe this is a bug, but since we're using a private test API, I wasn't sure if its worth an issue (maybe just a bug fix PR?)

FIX: testutil decorator

---

README.md

The test itself is failing right now as per the comments in #68 , but here are the badge links for the Readme when ready.

Adding badge for Sanity check

---

tensorflow_addons/activations/BUILD
tensorflow_addons/custom_ops/image/BUILD
tensorflow_addons/custom_ops/image/cc/kernels/image_projective_transform_op.cc
tensorflow_addons/custom_ops/seq2seq/BUILD
tensorflow_addons/custom_ops/text/BUILD
tensorflow_addons/image/BUILD
tensorflow_addons/layers/BUILD
tensorflow_addons/losses/BUILD
tensorflow_addons/optimizers/BUILD
tensorflow_addons/seq2seq/BUILD
tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/text/BUILD
tools/ci_build/builds/builds_common.sh

Reformat all codes because we have set up sanity checker: https://github.com/tensorflow/addons/issues/68

CLN: reformat all codes

---

tensorflow_addons/examples/tfa_optimizer.py
tensorflow_addons/optimizers/BUILD
tensorflow_addons/optimizers/README.md
tensorflow_addons/optimizers/__init__.py
tensorflow_addons/optimizers/lazy_adam.py
tensorflow_addons/optimizers/lazy_adam_test.py

Rename LazyAdamOptimizer to LazyAdam

---

tf_dependency/BUILD.tpl
tf_dependency/tf_configure.bzl

Bit of a moving target here... but at least the soname is correct for tf2-preview now

FIX: Correctly link the new soname for tf2

---

tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/seq2seq/attention_wrapper_test.py
tensorflow_addons/seq2seq/beam_search_decoder.py
tensorflow_addons/seq2seq/beam_search_decoder_test.py

* Inherit from `tf.keras.layers.AbstractRNNCell`
* Replace `tf.compat.v1.layers.Dense` by `tf.keras.layers.Dense`
* Store sublayers in `list` instead of `tuple`
Closes #128

Improve AttentionWrapper compatibility with TF 2.0

---

README.md
build_pip_pkg.sh

Mac's builtin readlink don't support -f option. Which need install GNU's readlink: greadlink by brew. Doc and script are both modified for this.

Add Mac OS X supporting for install from source

---

tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/seq2seq/attention_wrapper_test.py

The scores were not masked even when `memory_sequence_length` was passed. Consequently, the expected mean of most tests was wrong.

Fix AttentionMechanism masking

---

tools/ci_testing/addons_cpu.sh

addons_cpu.sh cannot work correctly on Mac OS X system due to cannot get CPU core number correctly. this PR fix it.
Also, related with #77 , I build and unit test tensorflow-addons on Mac based on [commit a3fd8ef](https://github.com/tensorflow/addons/commit/a3fd8efd977accec0a68c96c7a49358369f641a1) (not the master branch which is CI test failed when I write this PR): building is OK and unit test passed. 
As a reminder for other developers on Mac, due to the issue bazelbuild/bazel#7241 with bazel, developers should not using virtualenv to test addons on Mac for now.

[bugfix] unit test on mac

---

tensorflow_addons/image/dense_image_warp_test.py

Closes #138. In the latest docker image, I find that the error is caused by `test_zero_flows`. The workaround is to disable test in graph mode.

Fix flaky test

---

tensorflow_addons/losses/contrastive.py

Minor patch: use `convert_to_tensor` to make sure `dtype` attribute exists.

Fix minor error in contrastive_loss

---

tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/seq2seq/attention_wrapper_test.py
tensorflow_addons/seq2seq/basic_decoder.py
tensorflow_addons/seq2seq/basic_decoder_test.py
tensorflow_addons/seq2seq/beam_search_decoder.py
tensorflow_addons/seq2seq/beam_search_decoder_test.py
tensorflow_addons/seq2seq/beam_search_ops_test.py
tensorflow_addons/seq2seq/decoder.py
tensorflow_addons/seq2seq/decoder_test.py
tensorflow_addons/seq2seq/loss.py
tensorflow_addons/seq2seq/loss_test.py
tensorflow_addons/seq2seq/sampler.py

- as per #134, replaces calls with TF2 public API
- TODO: replace v1 / compat.v1 constructs with v2
- TODO: `my_decoder is not callable` produced by pylint for decoder_test.py:63,140
- dense_image_warp_tests are failing - fixing them was not part of this pull request

conversion to use tf2 public API - installment 1

---

requirements.txt

Starting the PR to unpin tf-nightly and resume testing against latest build. It looks as though the protobuf error we had will be fixed in tomorrows nightly.

Utilize current TF2 nightly

---

configure.sh

Resolves #117. Added yes/no prompt in `configure.sh`

Added prompt before install

---

tensorflow_addons/image/dense_image_warp.py
tensorflow_addons/image/dense_image_warp_test.py

Closes #138 
Removing the decorator is not ideal, but stability is more important than the speed up we'd get with that decorator. @WindQAQ are these changes okay with you?

FIX: Dense Image Warp Bug

---

README.md
build_pip_pkg.sh
tensorflow_addons/version.py

* Remove unnecessary check for cmake build. We only offer bazel build
* Remove os dependent call to readlink. All this was doing was gathering an absolute directory path

CLN: Simplify Build Script

---

.github/CODEOWNERS
BUILD
README.md
tensorflow_addons/__init__.py
tensorflow_addons/rnn/BUILD
tensorflow_addons/rnn/README.md
tensorflow_addons/rnn/__init__.py
tensorflow_addons/rnn/cell.py
tensorflow_addons/rnn/cell_test.py

Slowly bring over the tf.contrib.rnn code to addons.
The selection criteria so far are:
1. Previous requested by user.
2. From widely cited research paper (more than 100 based on Google scholar).
The initial commit only contains one rnn cell so far (NASCell), expect more cells to come.

Add subpackage for RNN related code.

---

README.md
configure.sh
tf_dependency/BUILD.tpl
tf_dependency/tf_configure.bzl

This will make the lookup of shared library name OS agnostic.

FIX: build using tf sysconfig

---

tensorflow_addons/image/filters_test.py

Fix test cases

---

tensorflow_addons/layers/wrappers.py
tensorflow_addons/layers/wrappers_test.py

1. Move the weights v and g to the wrapper itself, since they are
more tie to the concept of weight norm, not the wrapped layer.
2. Update the build() method to only create weights, and not do
weights manipulation. Setting the init value based on the inputs
are done in call().
3. Remove the tf.function annotation on call, for debugability.
4. Renamed few function and add some comments for readability.
5. Added get_config() for serialization.

Update and fix WeightNorm Wrapper.

---

tensorflow_addons/seq2seq/beam_search_decoder.py

Current nightly is breaking for 
```
raw_next_word_ids = tf.mod(
AttributeError: 'module' object has no attribute 'mod'
```

FIX: Update API

---

tensorflow_addons/optimizers/BUILD
tensorflow_addons/optimizers/README.md
tensorflow_addons/optimizers/__init__.py
tensorflow_addons/optimizers/moving_average.py
tensorflow_addons/optimizers/moving_average_test.py

Implement MovingAverage optimizer

---

tensorflow_addons/rnn/cell.py
tensorflow_addons/rnn/cell_test.py

1. The change was based on contrib.LayerNormBasicLSTMCell, which is
popular based on https://tf-contrib-analyzer.herokuapp.com.
2. The cell has been updated to align with keras and v2 standard,
eg use keras LSTMCell as base class, get rid of variable scope, etc.
3. The implementation has been updated to match the original paper.
There are 3 norm performed. One for input kernel, second one for
recurrent kernel, and finally for the carry state before activation.
More importantly, the first 2 norm are based on fused gates, rather
than the existing implementation (individual gates separately).
4. Adding the bias when normalization is on. I think missing the bias
was an oversight for the original implementation, and I have confirmed
this with original author of the contrib code.
5. Update the …

 Add LayerNormLSTMCell to RNN cell

---

tensorflow_addons/examples/layers_weightnormalization.ipynb

FIX: x_test scaling in weightnormalization example

---

tensorflow_addons/layers/wrappers.py
tensorflow_addons/layers/wrappers_test.py

Closes #216
Looks like assigning the variables using operations during init created an issue in the gradients. Setting their values inside of tf.function as done before appears to fix it. I'm not really thrilled about the lack of test coverage, but also not excited to build a regression test into our unit tests. 
https://colab.research.google.com/drive/1Md7SnyEC5bUfkME1Akth4KKM24ac26NK
After this bugfix is in I'll work on publishing a 0.3 release

FIX: weightnorm variables

---

.gitignore
BUILD
tensorflow_addons/BUILD
tools/docs/BUILD
tools/docs/README.md
tools/docs/build_docs.py
tools/docs/doc_requirements.txt

Fix #46
Related PRs: #140, #195, #196
```bash
bazel build tools/docs:build_docs
bazel-bin/tools/docs/build_docs --git_branch=master --output_dir=docs/api_docs/python/
```
I push the documnets generated to my repository, and everyone can preview it at https://github.com/facaiy/addons/blob/tf_addons_doc_preview/docs/api_docs/python/tfa.md

add bazel command to generate API docs

---

tensorflow_addons/image/distance_transform.py
tensorflow_addons/image/transform_ops.py

Removing private API and I believe these are leftover from a TF version from long ago.
0.11 Release mentions removing the python SetShape, and I see no uses of this in TF core repository. I belive the C++ SetShape is all that is required:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L2798

CLN: Remove outdated python RegisterShape

---

tensorflow_addons/optimizers/lazy_adam.py
tensorflow_addons/optimizers/weight_decay_optimizers_test.py

FIX:  Remove epsilon as variable.

---

tensorflow_addons/activations/sparsemax.py
tensorflow_addons/seq2seq/decoder.py
tensorflow_addons/seq2seq/sampler.py

Temporary patch to close #250 and return CI testing. Will make separate issues so that submodule owners can correctly reshape the tensors whenever there is time.

Use compat.v1 for broadcasted tf.where

---

tensorflow_addons/image/distort_image_ops.py
tensorflow_addons/image/distort_image_ops_test.py

Fix failed builds because of update in upstream.

Fix distort_image_ops_test

---

tensorflow_addons/optimizers/lazy_adam.py
tensorflow_addons/optimizers/lazy_adam_test.py

Fixes a break caused by change in upstream:
https://github.com/tensorflow/tensorflow/commit/611db3490b1dcf22c13ffcb64f50b75faa5e0ecc

FIX: LazyAdam init

---

CONTRIBUTING.md
README.md
examples/README.md
examples/template.ipynb

Adding information since [the RFC](https://github.com/tensorflow/community/blob/master/rfcs/20190308-addons-proxy-maintainership.md) has been merged. Also adding some instructions for adding examples.
Closes #168

DOC: Update READMEs

---

tensorflow_addons/image/filters.py
tensorflow_addons/image/filters_test.py
tensorflow_addons/utils/keras_utils.py

Closes #234. Will create another PR to clean up median_filter2d.

Speed up mean_filter2d with depthwise_conv2d

---

.gitignore
.travis.yml
README.md
build_pip_pkg.sh
configure.sh
setup.py
tools/ci_build/builds/release_linux.sh
tools/ci_build/builds/release_macos.sh
tools/ci_build/builds/wheel_verify.sh

Closes #76 
Nightlies are being pushed to:
https://pypi.org/project/tfa-nightly/#files
Will set up a nightly cron once this is merged into master. This is also a big help for the 0.4 release which should be happening shortly after TF2 release candidate

ENH: Automate build

---

tensorflow_addons/seq2seq/loss.py

Fixes today's broken nightly.
Just curious -- I guess the decision has been made to remove the tf.* aliases? I think its a nice API clean-up personally but I wasn't aware this was happening.

FIX: Use keras loss

---

tensorflow_addons/layers/README.md
tensorflow_addons/losses/README.md
tensorflow_addons/optimizers/README.md

In preparation for the monthly newsletter / maintainer request. Clearing the legacy SIG-Addons maintainers so it's clear that these are un-maintained.
Obviously if there is a bug the SIG will still look into / fix it -- but for clarity we're looking for submodule maintainers.

DOC: Clear SIG-Addons as a maintainer

---

.travis.yml

Quick question: @ewilderj do you know if a travis server will be able to email that address without being in the google group?

Add notifications for failing tests/builds

---

tensorflow_addons/image/filters.py
tensorflow_addons/image/filters_test.py

Addresses #230. Also meets the interface of mean_filter2d.
A general random test case is down below. Maybe there are some ways to speed up. It's now much more slower than scipy's implementation even for the input of shape [1, h, w, 1].
https://colab.research.google.com/drive/1UkNXxjTMHifKmHB2N5ojOHFojtXrOUIG

Support batch input for median_filter2d

---

tensorflow_addons/image/distort_image_ops.py
tensorflow_addons/image/distort_image_ops_test.py

1. Do TODO : make tests compatible with graph mode in distort_image_ops.
2. Revert #257. 
3. Have to use `self.evaluate()` to make exception raised in C++.

Make tests compatible with graph mode

---

tensorflow_addons/losses/triplet.py
tensorflow_addons/losses/triplet_test.py

FIX: compile triplet loss within keras model

---

tools/docs/README.md
tools/docs/doc_requirements.txt

Looks like yaml files were added to the api generator:
```
root@30cbf3ddea58:/addons# bazel-bin/tools/docs/build_docs --git_branch=$(git rev-parse --abbrev-ref HEAD)
Traceback (most recent call last):
File "/addons/bazel-bin/tools/docs/build_docs.runfiles/__main__/tools/docs/build_docs.py", line 36, in <module>
from tensorflow_docs.api_generator import generate_lib
File "/usr/local/lib/python2.7/dist-packages/tensorflow_docs/__init__.py", line 7, in <module>
from tensorflow_docs import api_generator
File "/usr/local/lib/python2.7/dist-packages/tensorflow_docs/api_generator/__init__.py", line 21, in <module>
import tensorflow_docs.api_generator.generate_lib
File "/usr/local/lib/python2.7/dist-packages/tensorflow_docs/api_generator/generate_lib.py", line 38, in <module>
import yaml …
```

DOC: Update doc generator requirements and instructions

---

tensorflow_addons/image/filters.py

Native `tf.image.extract_patches` could extract multi-channeled image patches. Speed up a lot when `batch_size` and `channels` are large.
https://colab.research.google.com/drive/1UkNXxjTMHifKmHB2N5ojOHFojtXrOUIG

Speed up median_filter2d

---

tensorflow_addons/losses/BUILD
tensorflow_addons/losses/README.md
tensorflow_addons/losses/__init__.py
tensorflow_addons/losses/npairs.py
tensorflow_addons/losses/npairs_test.py

Addresses #26. Will proceed with multilabel npairs loss after this.

Migrate npairs_loss

---

tensorflow_addons/image/dense_image_warp_test.py
tensorflow_addons/image/transform_ops_test.py

1. TODO in distort_image_ops_test.py: test gradients in TF2.0 favor.
2. TODO in transform_ops_test.py: use `tf.test.compute_gradient` in TF2.0 version. ~~Note that the tolerance in TF1.x (previous code) is 1e-10, but this will cause < 1% mismatch in TF2.0 gradient checker. It will pass if I set the tolerance to 1e-4 (also tested 1e-5, but failed...).~~
3. There's no need to override `setUp()` method in order to set random seed.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/test_util.py#L1729
reference code:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/optimizer_v2/gradient_descent_test.py#L136

Make gradient tests compatible with eager mode

---

tensorflow_addons/seq2seq/beam_search_decoder.py

Commit [1cd4a2b](https://github.com/tensorflow/tensorflow/commit/1cd4a2b5c8a6224423d8d2ed999e528823ff14aa) in TF removed `_element_shape` from TensorArray.

FIX: Use element_shape in beam_search_decoder

---

.travis.yml

Confirmed that it is successfully able to email the addons-testing mailing list:
https://groups.google.com/a/tensorflow.org/forum/#!topic/addons-testing/2A0gEAS3-gw

BLD: Remove notification email

---

requirements.txt
tensorflow_addons/rnn/cell.py

Fix #321.
Bugs are caused by these lines
https://github.com/tensorflow/addons/blob/31750c99bc24620b2d6cba834a5c954e9c666f32/tensorflow_addons/rnn/cell.py#L324-L326
Both kernel_norm and recurrent_norm work on un-split tensors and will take tensors of shape [batch_size, self.units * 4] as input.
Have no idea why previous version could work though...

Fix LayerNormLSTMCell

---

tensorflow_addons/image/BUILD
tensorflow_addons/image/README.md
tensorflow_addons/image/__init__.py
tensorflow_addons/image/translate_ops.py
tensorflow_addons/image/translate_ops_test.py

The translate ops and the test scripts have been added for the issue #25

Translate ops added and its test script

---

tensorflow_addons/image/BUILD
tensorflow_addons/image/transform_ops.py
tensorflow_addons/image/transform_ops_test.py
tensorflow_addons/image/utils.py
tensorflow_addons/image/utils_test.py

Fix #243
1. The name `*_4D_image` looks kind of confusing, any good idea?
2. I didn't check all image ops and see if they can work well with unknown rank image, perhaps we should file a new issue with check list.

Convert unknown rank image to 4D image

---

tools/ci_testing/addons_gpu.sh

We run into GPU OOM errors if we allow more than one job. TF claims the entire memory of a card so multiple jobs with a single card causes errors. See:
https://source.cloud.google.com/results/invocations/457625fa-7589-40ca-9f59-c097bac89322/targets/tensorflow_addons%2Fubuntu%2Fgpu%2Fpy2%2Fpresubmit/log

Limit GPU testing jobs

---

configure.sh

Closes #353 
I wanted a more elegant fix than string parsing, but it's quite a pain with bazel. I'll file an issue on custom-op and we can update this if there is a better way later on.

FIX: macos build

---

build_deps/gpu/cuda_configure.bzl

This PR tries to fix the error `load() statements must be called before any other statement` when building the project on MacOS. It moves `load()` to the top of `cuda_configure.bzl`.

Make cuda_configure.bzl compatible with bazel

---

examples/losses_triplet.ipynb

TripletLoss example

---

tools/ci_build/builds/release_macos.sh

Resolve `load() statements must be called before any other statement. First non-load() statement appears at ` Error.
Seems we could alter the cuda_configure script to be compatible with 0.25, but for now I think we should align our bazel versions anyway.

BLD: Pin bazel version for macos

---

tensorflow_addons/image/distort_image_ops_test.py

This PRs adds the unknown shape tests for `adjust_hue_in_yip` and `random_hsv_in_yiq` (related to #332) and cleans up the test script a little bit.

Add unknown shape tests for adjust_hue_in_yip and random_hsv_in_yiq

---

tensorflow_addons/seq2seq/BUILD

* Prevent warning during bazel test
```
WARNING: //tensorflow_addons/seq2seq:basic_decoder_test: Test execution time (3.8s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
```

BLD: Change test sizes of seq2seq

---

tensorflow_addons/image/distort_image_ops_test.py

Seeing as this is only failing in graph mode, and it's throwing an error on a test case that should throw errors anyway.. I'd like to merge this temporary fix so we can return full CI testing.
Will leave the issue open for a final fix.

Temporary fix for distort_ops testing

---

tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/seq2seq/attention_wrapper_test.py
tensorflow_addons/seq2seq/basic_decoder.py
tensorflow_addons/seq2seq/beam_search_decoder.py
tensorflow_addons/seq2seq/beam_search_decoder_test.py
tensorflow_addons/seq2seq/decoder.py

Fixes #364 
Also fixes a few typos using `tf.contrib`.

Add `training` parameter in seq2seq decoders

---

tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/seq2seq/attention_wrapper_test.py

This simplifies the usage of the layer outside of Keras where a typical usage would be to create the layer once and then setup the memory dynamically, e.g.:
```python
attention = tfa.seq2seq.LuongAttention(units)
attention.setup_memory(memory, memory_sequence_length)
```

Improve API for resetting AttentionMechanism memory

---

tensorflow_addons/seq2seq/attention_wrapper_test.py

This test uses a Keras anti-pattern in where the layer optionally accepts the output of another layer in the constructor. We are in the process of refactoring the v2 training loop to make it work with tf.function (faster! better! stronger!), but this code will need to be updated as a result. For now, we are falling back to the v1 training loop with an experimental flag; @qlzh727 will look for a longer-term solution when he gets through some pressing release issues.
(The flag won't be in the nightlies until tomorrow, but setting up this PR early, and will wait until tests are green to submit.)

Add fallback flag to seq2seq tests

---

tools/ci_testing/addons_cpu.sh
tools/ci_testing/addons_gpu.sh
tools/ci_testing/install_py36.sh

Closes #279.
Py34 pip packages for tf-nightly have not been produced in ~2 weeks. When the new build env arrives we'll be re-vamping our testing scripts anyway.

TEST: Upgrade python3 env to py36

---

tools/ci_testing/addons_cpu.sh
tools/ci_testing/addons_gpu.sh
tools/ci_testing/install_py36.sh
tools/run_docker.sh

@Squadrick @tensorflow/sig-addons-maintainers  this should work better. Apologies.
Installing py36 is only safe to do knowing the user is running in a docker container.

FIX: Better implementation of py36 testing

---

build_deps/gpu/cuda/BUILD.tpl
build_deps/gpu/cuda/build_defs.bzl.tpl
build_deps/requirements.txt
build_deps/requirements_gpu.txt

Prefix of cuda include path is changed in core Tensorflow so we need to sync build files in custom-op.
Need this PR for [beam_search_ops_gpu.cc](https://github.com/tensorflow/addons/blob/d57ffc2296a599542833da6c1c1482799ce811ad/tensorflow_addons/custom_ops/seq2seq/cc/kernels/beam_search_ops_gpu.cu.cc#L21) and [adjust_hsv_in_yiq_op_gpu.cu.cc](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/custom_ops/image/cc/kernels/adjust_hsv_in_yiq_op_gpu.cu.cc#L21). We could keep working on GPU kernel building after this :-)
Related links:
https://github.com/tensorflow/custom-op/commit/b267cc546365f30963ef2f6b690ff0a4e7391913#diff-0c845043da8b3200ae16b7a3e1781cc2
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/gpu_kernel_helper.h#L22

Sync custom-op

---

tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op.h
tensorflow_addons/image/utils.py
tensorflow_addons/optimizers/weight_decay_optimizers.py
tensorflow_addons/seq2seq/beam_search_decoder.py
tools/ci_build/install/ci_requirements.txt
tools/ci_build/install/install_ci_dependency.sh
tools/ci_build/pylintrc

Upgrade pylint to 2.x for python 3.6 environment. Fix `make sanity-check` hanging problem.

BLD: upgrade pylint for python 3

---

tensorflow_addons/custom_ops/image/cc/ops/distort_image_ops.cc
tensorflow_addons/image/distort_image_ops_test.py

Closes #373. 
This is probably related to https://github.com/tensorflow/addons/issues/12 and https://github.com/tensorflow/tensorflow/issues/24945 (in the totally opposite side). I think the best solution now is to do shape inference in SetShapeFn while registering OP, which seems to successfully raise the same exception (ValueError) and the same error message in both graph and eager modes.

[image/distort_image_ops] fix graph mode tests

---

tensorflow_addons/custom_ops/image/BUILD
tensorflow_addons/custom_ops/image/cc/kernels/adjust_hsv_in_yiq_op_gpu.cu.cc

[image/distort_image_ops] build GPU kernel

---

tools/ci_build/builds/release_linux.sh
tools/ci_build/builds/release_macos.sh

Nightly builds are failing since there is no py34 package:
https://travis-ci.org/tensorflow/addons/jobs/568829836
This will get fixed in #389 but I'm currently on vacation so it'll be another week or so.

BLD: Remove py34 support as it no longer published for tf-core

---

tensorflow_addons/seq2seq/beam_search_decoder.py

The function `as_shape` only creates a TensorShape if not already one.

Remove unnecessary tensor_shape module import

---

.travis.yml
CONTRIBUTING.md

Travis build failed because pip was out of date (we upgrade pip in our `run_docker` script). It's cleaner to run it this way anyway IMO

Use docker script in travis

---

tensorflow_addons/optimizers/lazy_adam_test.py
tensorflow_addons/optimizers/moving_average_test.py

MovingAverage is broken until https://github.com/tensorflow/tensorflow/issues/31582

FIX: Unhashable variables

---

tensorflow_addons/metrics/cohens_kappa.py

Closes https://github.com/tensorflow/addons/issues/397
Corrected the example in docstring.

FIX: docstring example in cohen_kappa.py

---

tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/seq2seq/attention_wrapper_test.py

Closes #407. Since `AttentionWrapper` is also a subclass of `Layer` and indeed does something. So this PR makes it able to takes `**kwargs` while calling `__init__()`.

[seq2seq] fix float64 tests

---

CONTRIBUTING.md
tools/ci_build/builds/wheel_verify.sh
tools/ci_build/install/install_ci_dependency.sh

Dockerfile has been updated to include these installs/updates

CLN: docker build since update

---

tensorflow_addons/layers/wrappers_test.py

Yikes... don't really have time to look into this more. What looks like a graph Tensor is running in eager execution as part of the keras test suite.
Constant breaks are getting draining here and it might just be easier to wait for 2.0-RC. I would say this layer is even a candidate for removal, but it continues to be used in academia and this bayesian inference paper may continue that:
https://arxiv.org/abs/1908.03491

Hotfix: temporarily remove test

---

tensorflow_addons/text/crf.py
tensorflow_addons/text/crf_test.py

Replace tf.get_variable with tf.Variable

---

tools/ci_build/builds/release_linux.sh
tools/ci_build/builds/tf_auditwheel
tools/ci_build/builds/tf_auditwheel_patch.sh
tools/ci_build/builds/wheel_verify.sh

Copying @yongtang 's patch https://github.com/tensorflow/io/commit/02dcf4a . Pure wizardry :smile: 
Closes #119

Patch manylinux2010 auditwheel repair so libtensorflow is not copied

---

tensorflow_addons/optimizers/moving_average_test.py

revert #416
The bug https://github.com/tensorflow/tensorflow/issues/31582 is fixed by https://github.com/tensorflow/tensorflow/commit/dc3534c6a502d2830634f51e08de507163aac952

TST: reopen moving_average_test

---

tensorflow_addons/activations/sparsemax.py
tensorflow_addons/activations/sparsemax_test.py
tensorflow_addons/losses/sparsemax_loss.py
tensorflow_addons/losses/sparsemax_loss_test.py

The order of decorators do matter! If we put `@tf.function` outer, then the function after deserialization will not be the same with the original one (before: `tf.function`, deserialize: python function).
Also, I think serialization/deserialization is also one of the features in keras. Maybe we have to make sure all subclasses from `tf.keras.*` could be serialized/de-serialized and be well tested.

Make sparsemax deserializable

---

tensorflow_addons/layers/wrappers.py
tensorflow_addons/layers/wrappers_test.py

WIP: Fix: WeightNormalization data init fails

---

tensorflow_addons/layers/wrappers.py
tensorflow_addons/layers/wrappers_test.py

It seems that autograph is not smart enough, so we have to control execute order by ourselves.

bugfix: force WeightNormalization to execute in order

---

tensorflow_addons/losses/README.md
tensorflow_addons/losses/__init__.py
tensorflow_addons/losses/npairs.py
tensorflow_addons/losses/npairs_test.py

Closes #26. Finally the last one :-)
- Migrate `npairs_loss_multilabel` from contrib
- Rename `npairs_loss_multilabel` to `npairs_multilabel_loss`, which makes sense to addons' naming style
- Modify input spec from
- `labels` (list of sparse tensor)
- `embedding_anchor`
- `embedding_posititve`
to
- `y_true` (either tensor or sparse tensor)
- `y_pred` (similarity matrix, which is the multiplication of anchor and positive)

[losses] migrate npairs multilabel loss

---

tensorflow_addons/metrics/f_scores.py

fixed small typo in docstring example

fix for typo in docstring example f1score metric

---

tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/seq2seq/attention_wrapper_test.py

This fixes using a custom attention layer which required the AttentionMechanism instances to be initialized with a memory at the time the AttentionWrapper is created.
Fixes #461.

Lazily compute the attention layer size

---

tensorflow_addons/seq2seq/decoder.py

Original change at
https://github.com/tensorflow/tensorflow/commit/a913689fddb70729dbce45a2cad44f4bd0f03935.
Fix for https://github.com/tensorflow/addons/issues/494

Port bug fix in TF contrib to addons.

---

tensorflow_addons/optimizers/lazy_adam.py

add documentation for lazy adam

---

tensorflow_addons/optimizers/moving_average.py
tensorflow_addons/optimizers/moving_average_test.py

* `get_config` correctly serializes the wrapped optimizer using `tf.keras.optimizers.serialize()`
* `from_config` to deserialize the config correctly, including the wrapped optimizer
* Wrapper optimizer can be specified using keras optimizer strings like: adam, rmsprop, adagrad, etc.
* Add tests for above new functionality
* Minor refactoring in `moving_average.py`

FIX: MovingAverage from_config, get_config

---

tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/seq2seq/basic_decoder.py
tensorflow_addons/seq2seq/basic_decoder_test.py
tensorflow_addons/seq2seq/beam_search_decoder.py
tensorflow_addons/utils/keras_utils.py
tensorflow_addons/utils/keras_utils_test.py

This function was a TensorFlow private API so it's probably better to own it at this point. It was ported with 2 changes:
* Reference to `zero_state` is removed
* `_hasattr` will first check if the attribute can be found by name before using `getattr`. This is to allow cells that run some lazy computation in their attribute.
Fixes #511.

Port assert_like_rnncell in addons utils

---

tensorflow_addons/optimizers/BUILD
tensorflow_addons/optimizers/README.md
tensorflow_addons/optimizers/__init__.py
tensorflow_addons/optimizers/lookahead.py
tensorflow_addons/optimizers/lookahead_test.py
tensorflow_addons/optimizers/rectified_adam.py
tensorflow_addons/optimizers/rectified_adam_test.py

Related to #422:
* The name of the optimizer is `RectifiedAdam` in case of conflicting with other abbreviations. (The name appears in the first line of the second page in the paper)
* Add `Lookahead` optimizer wrapper.
* Unit tests for RAdam are compared with the results of the [official implementation](https://github.com/LiyuanLucasLiu/RAdam).
* Unit tests for Ranger (RAdam + Lookahead) are compared with the results of the [implementation](https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer) from the proposer.

Add RAdam and LookAhead optimizers

---

.gitignore
CONTRIBUTING.md
MANIFEST.in
README.md
docs/_book.yaml
docs/_index.yaml
docs/_project.yaml
docs/tutorials/README.md
docs/tutorials/image_ops.ipynb
docs/tutorials/layers_normalizations.ipynb
docs/tutorials/layers_weightnormalization.ipynb
docs/tutorials/losses_triplet.ipynb
docs/tutorials/optimizers_lazyadam.ipynb
docs/tutorials/template.ipynb

Initial setup for tensorflow subsite

---

tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/seq2seq/decoder.py

Most of these functions are small and can be replaced by a simple implementation. However, they included some additional logic about static shapes but it does not seem to be needed here (at least the tests are not covering such cases).
@qlzh727 Let me know if there is a strong reason to rely on these internal functions.

Implement alternatives to some TensorFlow private APIs

---

tools/docs/build_docs.py

Hi, 
To generate docs for tensorflow.org we need to standardize the `FLAGS` so this script works with our pipeline without throwing errors about unrecognized flags.
This change doesn't affect the output of the script (except path prefixes is .yaml files) or the current usage described in README.md.
For #226

Add standard flags to build_docs.py

---

tensorflow_addons/layers/optical_flow_test.py

Fix optical_flow test case

---

tensorflow_addons/layers/optical_flow.py
tensorflow_addons/layers/optical_flow_test.py

Fix #509 
I have added the documentation for the CorrelationCost function and also made the _correlation_cost_ as private. 
I am new to open source and this is my first contribution to the community. I would appreciate any reviews.
Thanks

Add docstring correlation cost

---

tensorflow_addons/custom_ops/text/BUILD
tensorflow_addons/custom_ops/text/cc/kernels/parse_time_kernel.cc
tensorflow_addons/custom_ops/text/cc/ops/parse_time_op.cc
tensorflow_addons/text/BUILD
tensorflow_addons/text/__init__.py
tensorflow_addons/text/parse_time_op.py
tensorflow_addons/text/parse_time_op_test.py

The parse time operator parses an input string according to the
provided format string into a Unix time, the number of seconds /
milliseconds / microseconds / nanoseconds elapsed since January 1,
1970 UTC.
Fixes: https://github.com/tensorflow/addons/issues/492

Implement Addons>ParseTime operator.

---

tensorflow_addons/custom_ops/activations/BUILD
tensorflow_addons/custom_ops/image/BUILD
tensorflow_addons/custom_ops/layers/BUILD
tensorflow_addons/custom_ops/seq2seq/BUILD

This is what is done in the TensorFlow codebase for custom ops:
https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/tensorflow.bzl#L1771-L1772
After building a pip package with this change, I no longer get the error reported in #532.
Fixes #532.

Link to cudart_static and remove cuda_libs

---

tensorflow_addons/activations/BUILD
tensorflow_addons/activations/README.md
tensorflow_addons/activations/activations_test.py
tensorflow_addons/activations/gelu_test.py
tensorflow_addons/activations/hardshrink_test.py
tensorflow_addons/activations/lisht_test.py
tensorflow_addons/activations/sparsemax.py
tensorflow_addons/activations/sparsemax_test.py
tensorflow_addons/activations/tanhshrink_test.py
tensorflow_addons/custom_ops/activations/cc/kernels/gelu_op.cc
tensorflow_addons/custom_ops/activations/cc/kernels/gelu_op.h
tensorflow_addons/custom_ops/activations/cc/kernels/gelu_op_gpu.cu.cc
tensorflow_addons/custom_ops/activations/cc/kernels/hardshrink_op.cc
tensorflow_addons/custom_ops/activations/cc/kernels/hardshrink_op.h
tensorflow_addons/custom_ops/activations/cc/kernels/hardshrink_op_gpu.cu.cc
tensorflow_addons/custom_ops/activations/cc/ops/gelu_op.cc
tensorflow_addons/custom_ops/activations/cc/ops/hardshrink_op.cc

- Remove `name` arg for sparsemax
- Test theoretical gradients only
- Test outputs against numerical values instead of reference function
- Move serialization test to standalone file to reduce duplicated codes
- CC trivial fix

unify activations and tests

---

tensorflow_addons/metrics/multilabel_confusion_matrix.py

This PR avoids to use `get_shape` from https://github.com/tensorflow/addons/pull/483 ; it also helps keep precision.

avoid substraction ops to maintain precision

---

tensorflow_addons/seq2seq/beam_search_decoder.py

The manual construction of gather coordinates can be removed by using the `batch_dims` argument of `tf.gather`.
The commit also merges a double `tf.expand_dims` into a single `tf.reshape`.

Simplify gather_tree_from_array implementation

---

tensorflow_addons/activations/BUILD
tensorflow_addons/activations/README.md
tensorflow_addons/activations/__init__.py
tensorflow_addons/activations/activations_test.py
tensorflow_addons/activations/softshrink.py
tensorflow_addons/activations/softshrink_test.py
tensorflow_addons/custom_ops/activations/BUILD
tensorflow_addons/custom_ops/activations/cc/kernels/softshrink_op.cc
tensorflow_addons/custom_ops/activations/cc/kernels/softshrink_op.h
tensorflow_addons/custom_ops/activations/cc/kernels/softshrink_op_gpu.cu.cc
tensorflow_addons/custom_ops/activations/cc/ops/softshrink_op.cc

- Address #437 - softshrink kernel https://www.gabormelli.com/RKB/Softshrink_Activation_Function

add softshrink kernel

---

README.md
build_deps/requirements.txt
build_deps/requirements_gpu.txt
configure.sh
setup.py

Close #562
Per https://groups.google.com/a/tensorflow.org/forum/#!topic/announce/DIDUrh6LZbo
> TensorFlow 2.0 nightly pip packages are now available under the tf-nightly project starting 10/3/19. tf-nightly-2.0-preview will no longer be updated
>  the nightly `tensorflow` and `tensorflow-gpu` pip packages consolidation as announced previously has been extended to the nightly pip packages as well.

BLD: switch to tf-nightly

---

tensorflow_addons/custom_ops/activations/BUILD
tensorflow_addons/custom_ops/image/BUILD
tensorflow_addons/custom_ops/layers/BUILD
tensorflow_addons/custom_ops/seq2seq/BUILD
tensorflow_addons/custom_ops/text/BUILD
tensorflow_addons/tensorflow_addons.bzl

Here is a proposal for #580.
It builds the custom op libraries with the same flags and deps as before. A difference is that GPU libraries have possibly a different name and/or include multiple kernels. Could it be an issue?
Closes #580.

Define custom_op_library Bazel macro

---

tensorflow_addons/activations/hardshrink.py
tensorflow_addons/activations/hardshrink_test.py
tensorflow_addons/activations/softshrink.py
tensorflow_addons/activations/softshrink_test.py
tensorflow_addons/custom_ops/activations/cc/ops/hardshrink_op.cc
tensorflow_addons/custom_ops/activations/cc/ops/softshrink_op.cc

Per this discussion:
https://github.com/tensorflow/addons/pull/570#discussion_r332281330
Matching the default lambda values with other frameworks:
https://github.com/pytorch/pytorch/blob/446a79b95992dee7b987d0f35364fbb4ed1372db/torch/csrc/api/include/torch/nn/options/activation.h#L166
https://github.com/PaddlePaddle/Paddle/blob/8fb569e5b913958619f07243decebc24e5a6aa48/paddle/fluid/operators/activation_op.cc#L393
https://github.com/pytorch/pytorch/blob/446a79b95992dee7b987d0f35364fbb4ed1372db/torch/csrc/api/include/torch/nn/options/activation.h#L33

Standardize lambda with other frameworks

---

tensorflow_addons/activations/__init__.py
tensorflow_addons/callbacks/__init__.py
tensorflow_addons/image/__init__.py
tensorflow_addons/metrics/__init__.py
tensorflow_addons/rnn/__init__.py
tensorflow_addons/seq2seq/__init__.py
tensorflow_addons/text/__init__.py

Seeing as these doc strings appear on the landing page for our API docs. Probably best that they're a bit more standardized:
https://www.tensorflow.org/addons/api_docs/python/tfa

DOC: Standardize doc information

---

tensorflow_addons/layers/optical_flow.py
tensorflow_addons/layers/optical_flow_test.py

* Fixes in CorrelationCost::compute_output_shape: integer division and channel indexing
* Cleanup in CorrelationCostTest for duplicated code

Bugfix: correct input shape handling for CorrelationCost Keras layer

---

tensorflow_addons/image/dense_image_warp.py
tensorflow_addons/image/dense_image_warp_test.py

* Make interpolate_bilinear compatible with TF Dataset
* Split InterpolateBilinearTest from DenseImageWarpTest
* Add InterpolateBilinearTest::test_unknown_shape

Make interpolate_bilinear compatible with TF Dataset (#332)

---

tensorflow_addons/text/crf.py
tensorflow_addons/text/crf_test.py

FIX: Internally cast to required DType

---

tensorflow_addons/metrics/cohens_kappa.py
tensorflow_addons/metrics/cohens_kappa_test.py

- Fix overflow issue stated in #267.
- Failed [testcase](https://colab.research.google.com/drive/1lA0mc0prr0XB4buKOdf44WvKi_xMXtIt) in previous version.
- Fix minor docstring.

Fix overflow of CohenKappa

---

tensorflow_addons/callbacks/tqdm_progress_bar.py

Solving this issue: https://github.com/tensorflow/addons/issues/679
The updated tf.keras.utils.register_keras_serializable requires get_config method, which I forgot to include in the original version. I have added the get_config method to TQDM_Progress_Bar in this PR. CC: @Squadrick

add get_config() method to TQDM_Progress_Bar

---

docs/overview.md
tensorflow_addons/optimizers/__init__.py

Fixing missing files

---

tensorflow_addons/layers/wrappers.py
tensorflow_addons/layers/wrappers_test.py

FIX: Invariant input_spec for WeightNormalization

---

tensorflow_addons/optimizers/BUILD
tensorflow_addons/optimizers/README.md
tensorflow_addons/optimizers/__init__.py
tensorflow_addons/optimizers/cyclical_learning_rate.py
tensorflow_addons/optimizers/cyclical_learning_rate_test.py

Migrating CyclicLR from keras-team/keras-contrib as discussed in https://github.com/keras-team/keras-contrib/issues/519.
- @gabrieldemarmiesse & @seanpmorgan would love some feedback on implementation
- @seanpmorgan is there any recommendations regarding tests? I plan on taking inspiration from [tf core schedulers](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/optimizer_v2/learning_rate_schedule_test.py), does it seem ok to you?

Add cyclical learning rate schedulers

---

tensorflow_addons/layers/wrappers.py
tensorflow_addons/layers/wrappers_test.py

The original wrapped layer and the non-trainable layer created for data-dependent initialization had a clash in their namespaces. Creating the second layer under a name scope of 'data_dep_init' fixes the issue.
Fixes #624

Build data_init layer under name_scope

---

tensorflow_addons/layers/wrappers.py
tensorflow_addons/layers/wrappers_test.py

When using WeightNormalization wrapper layer on a layer which set use_bias=False we get an exception. 
Make sure to check that a bias exists before trying to assign to it.

Fix WeightNormalization wrapped layer has use_biase=False

---

tensorflow_addons/custom_ops/layers/cc/kernels/correlation_cost_op.cc
tensorflow_addons/layers/optical_flow_test.py

- Closes #688 
- Sharding over each pixel: this could be 10 times faster than original one (or more depending on parameters)
- Robust test on CPU: because CPU/GPU kernels are implemented differently, I do think we have to run both of them if GPU is available

Speed up correlation cost

---

tensorflow_addons/optimizers/BUILD
tensorflow_addons/optimizers/README.md
tensorflow_addons/optimizers/stochastic_weight_averaging.py
tensorflow_addons/optimizers/stochastic_weight_averaging_test.py
tensorflow_addons/optimizers/weight_decay_optimizers_test.py

Adding Stochastic Weight Averaging Optimizer.
Notes:
* The optimizer needs the calling of the `assign_average_vars()` at the end of training to assign the averaged values to the model variables. Docstring for `assign_average_vars()` contains an example on how to do this.
* Averaging starts happening at step `start_averaging` and then happens at every `average_period` steps.
Closes #592

Add Stochastic Weight Averaging Optimizer.

---

tensorflow_addons/losses/lifted.py
tensorflow_addons/losses/lifted_test.py

Fix keras model compile for lifted_struct_loss

---

tensorflow_addons/custom_ops/text/cc/kernels/skip_gram_kernels.cc

Note that during the transition period tstring is typedef'ed to
std::string.
See: https://github.com/tensorflow/community/pull/91

Migrate from std::string to tensorflow::tstring.

---

tensorflow_addons/custom_ops/text/BUILD
tensorflow_addons/text/BUILD
tensorflow_addons/text/__init__.py

As discussed, we won't build `parse_time` till #663 is completely resolved in r2.1

Don't build parse_time till TF r2.1

---

tensorflow_addons/custom_ops/image/BUILD
tensorflow_addons/custom_ops/image/cc/kernels/adjust_hsv_in_yiq_op.cc
tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops.cc
tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops.h
tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops_gpu.cu.cc
tensorflow_addons/custom_ops/image/cc/ops/resampler_ops.cc
tensorflow_addons/image/BUILD
tensorflow_addons/image/README.md
tensorflow_addons/image/__init__.py
tensorflow_addons/image/resampler_ops.py
tensorflow_addons/image/resampler_ops_test.py
tensorflow_addons/image/sparse_image_warp.py

Address [issue #640](https://github.com/tensorflow/addons/issues/640), resampler kernel

add resampler kernel

---

tools/ci_build/builds/release_macos.sh

Nightly macos build is currently failing while trying to upgrade an up-to-date pyenv:
https://travis-ci.org/tensorflow/addons/jobs/616260135
Small fix to correct this:
https://travis-ci.org/seanpmorgan/addons/jobs/616425666
Reference: https://github.com/Homebrew/legacy-homebrew/issues/27897
Just a note: Plan on doing some upgrades to the build later this week (e.g. Bazel 1.0 / CUDA 10.1)

Hotfix: fix brew setup

---

tensorflow_addons/image/transform_ops_test.py
tensorflow_addons/layers/BUILD
tensorflow_addons/layers/normalizations_test.py
tensorflow_addons/metrics/r_square_test.py
tensorflow_addons/optimizers/conditional_gradient_test.py
tensorflow_addons/optimizers/cyclical_learning_rate_test.py
tensorflow_addons/optimizers/weight_decay_optimizers_test.py

To be consistent with all tests in optimizers, layers, etc; replacing `run_in_graph_and_eager_modes` (only supports test methods) by `run_all_in_graph_and_eager_modes`.

Test in eager model

---

tensorflow_addons/metrics/cohens_kappa.py
tensorflow_addons/metrics/cohens_kappa_test.py

It fixes the following two bugs related to the CohenKappa metric:
- dtype issue when used within distributed strategy scope #720 
- NaN result issue after state reset.

fix distributed training error and nan result bugs

---

tensorflow_addons/layers/normalizations.py
tensorflow_addons/layers/normalizations_test.py

* Fix a bug, where the GroupNormalization layer was normalizing over the second axis instead of the selected axis.
* Update tests (which seem to be irrelevant anyway)

Fix GroupNormalization

---

tensorflow_addons/optimizers/BUILD
tensorflow_addons/optimizers/README.md
tensorflow_addons/optimizers/yogi.py
tensorflow_addons/optimizers/yogi_test.py

Implement Yogi optimizer in paper [Adaptive Methods for Nonconvex Optimization](https://papers.nips.cc/paper/8186-adaptive-methods-for-nonconvex-optimization.pdf) as a tf.keras.optimizers.Optimizer

Implements YogiOptimizer

---

tools/ci_build/builds/release_linux.sh
tools/ci_build/install/install_ci_dependency.sh

Current CI and nightly build fail to run `apt-get update` since this ppa is now stale. Some context:
https://launchpad.net/~jonathonf
Tested the build scripts as well and it should fix our nightly.

Temporarily remove stale ppa until image can be updated

---

docs/tutorials/time_stopping.ipynb
tensorflow_addons/callbacks/BUILD
tensorflow_addons/callbacks/README.md
tensorflow_addons/callbacks/__init__.py
tensorflow_addons/callbacks/time_stopping.py

This PR adds TimeStopping to tfa.callback. Similar to EarlyStopping but stops the training when a specified amount of time has passed since the start of the training.
This may be useful for people who want to train a model for a certain amount of time. Personally, sometimes I would want to train models for a certain amount of time (and there are codes after training ends so CTRL+C is not ideal) and I often find myself using pen and pencil to calculate how many epochs I would want to run. I hope people may find this useful as well.
Relevant Issues:
https://github.com/tensorflow/addons/issues/750
https://github.com/keras-team/keras/issues/1625
https://github.com/keras-team/keras-contrib/issues/87
Thank you so much for your time!

Adding TimeStopping to tfa.callback

---

tensorflow_addons/image/transform_ops_test.py

This makes it more visually-explicit that as_numpy_dtype(0) returns a scalar value, not a dtype.

as_numpy_dtype is a property, not a method

---

tensorflow_addons/seq2seq/attention_wrapper_test.py

The seq2seq layers need to be made to work w/o `experimentatl_run_tf_function=False`

Disable seq2seq test that uses deprecated fallback

---

tensorflow_addons/seq2seq/attention_wrapper_test.py

It seems we don't need this flag to run the test.
Closes #790.

Remove experimental_run_tf_function in AttentionWrapper test

---

MIGRATED_TO_CORE.md
MIGRATION_TO_CORE.md

DOC: Add core migration guide

---

tensorflow_addons/image/BUILD

This test occasionally fails just outside of tolerance. Marking as flaky:
https://docs.bazel.build/versions/master/be/common-definitions.html#test.flaky

Mark filters_test as flaky

---

tensorflow_addons/activations/BUILD

Temporary until #802 is resolved.
Example:
https://source.cloud.google.com/results/invocations/2490d700-0837-4468-916a-0306b1714d87/targets/tensorflow_addons%2Fubuntu%2Fgpu%2Fpy3%2Fpresubmit/log

Temporarily set rrelu_test as flaky

---

tensorflow_addons/optimizers/__init__.py

to fix the following error when `tfa.optimizers.SWA` is used:
`AttributeError: module 'tensorflow_addons.optimizers' has no attribute 'SWA'`

Add SWA in optimizers.__init__

---

.travis.yml
CONTRIBUTING.md
README.md
build_deps/check_deps.py
build_deps/requirements.txt
build_deps/toolchains/gpu/find_cuda_config.py
configure.sh
setup.py
tools/ci_build/builds/release_linux.sh
tools/ci_build/builds/release_macos.sh
tools/ci_build/builds/release_windows.sh
tools/ci_build/ci_sanity.sh
tools/ci_testing/addons_cpu.sh
tools/ci_testing/addons_gpu.sh

First steps for #770
* Update configure script to take user input
* Update build scripts
* Simplify documentation
* Enable windows nightly now that it's available.

BLD: Refactor configure

---

tensorflow_addons/layers/wrappers.py
tensorflow_addons/layers/wrappers_test.py

* Use `recurrent_kernel` for RNNs
* Add more test cases
* Add warning for RNN + data-dependent initialization 
* Add `remove()`, fixes #763 
Continuation of #769

FIX: RNN support for weight norm and `remove()`

---

.github/workflows/macos_nightly.yml
README.md

Badge is currently working, but this will rename the workflow so we can easily transition other nightlies to GitHub Actions when time allows:
https://github.com/tensorflow/addons/workflows/nightly-tests/badge.svg

DOC: Add badge for nightly macos tests

---

.travis.yml

One more.... 
Even though the build was green our upload for the linux wheel fails for permission:
https://travis-ci.org/tensorflow/addons/jobs/632292641#L2621
https://pypi.org/project/tfa-nightly/0.7.0.dev20200103/#files

BLD: Install twine to user

---

tensorflow_addons/layers/wrappers.py

Minor fix:
https://stackoverflow.com/questions/15539937/whats-the-difference-between-logging-warn-and-logging-warning-in-python

Update logging to warning since warn is deprecated

---

tensorflow_addons/callbacks/tqdm_progress_bar.py

Quick fix to a bug when using `fit_generator`
It turns out that when using `fit_generator` the progress bar is updating by 1 (instead of by `batch_size`) after each batch, but we still need to keep the number of samples seen to accuracy compute and display the metrics. Therefore I add another field to keep track of steps so far and rename `self.seen` to `self.num_samples_seen` for clarity.
Edit: Link to Issue
https://github.com/tensorflow/addons/issues/812

fixes bugs when using fit generator

---

.travis.yml

Welp... installing twine as user for mac/windows puts it off the PATH:
https://travis-ci.org/tensorflow/addons/jobs/632643533#L4300
This should be the last fix for nightlies... sorry about the multiple PRs

BLD: Only install twine to user path for linux builds

---

tensorflow_addons/layers/__init__.py
tensorflow_addons/layers/gelu.py
tensorflow_addons/layers/gelu_test.py

Correct the abbreviation from GeLU to GELU, which is used in the original [paper](https://arxiv.org/abs/1606.08415) and the community.

FIX: GELU name

---

tensorflow_addons/image/dense_image_warp.py
tensorflow_addons/image/dense_image_warp_test.py

Fixed incorrect clipping of query indices for non-square images.
Also modified tests to use non-square images.
Additional note: a single tf.reverse(query_points, -1) operation in an if statement could simplify this function for "ij" vs "xy" mode.

Fix bug in "xy" mode for bilinear interpolation

---

README.md

This badge doesn't make much sense to me on the central README. The test is really used for incoming PRs.

CLN: Remove sanity nightly badge

---

.github/workflows/ci_test.yml
.github/workflows/ubuntu_nightly.yml
README.md

Moving CPU testing to github. After this merges we can contact TF team to update per #863

Move ubuntu CPU testing to github actions

---

tensorflow_addons/layers/BUILD
tensorflow_addons/layers/__init__.py
tensorflow_addons/layers/tlu.py
tensorflow_addons/layers/tlu_test.py

This activation unit is introduced in Filter Response Normalization

Thresholded Linear Unit

---

.github/boring-cyborg.yml

After this we can remove the duplicate `testing` label

CLN: Consolidate test case label

---

tensorflow_addons/activations/gelu.py
tensorflow_addons/activations/hardshrink.py
tensorflow_addons/activations/lisht.py
tensorflow_addons/activations/mish.py
tensorflow_addons/activations/softshrink.py
tensorflow_addons/activations/tanhshrink.py
tensorflow_addons/image/connected_components.py
tensorflow_addons/image/distance_transform.py
tensorflow_addons/image/distort_image_ops.py
tensorflow_addons/image/resampler_ops.py
tensorflow_addons/image/transform_ops.py
tensorflow_addons/layers/optical_flow.py
tensorflow_addons/seq2seq/beam_search_decoder.py
tensorflow_addons/seq2seq/beam_search_decoder_test.py
tensorflow_addons/seq2seq/beam_search_ops_test.py
tensorflow_addons/text/parse_time_op.py
tensorflow_addons/text/skip_gram_ops.py
tensorflow_addons/utils/resource_loader.py

Fixes #855
I don't know how to make a test for that though. If possible we need to check that an so isn't loaded when doing `import tensorflow_addons`.

Lazy loading of shared libraries.

---

tools/ci_build/builds/release_linux.sh
tools/ci_build/builds/tf_auditwheel_patch.sh
tools/ci_build/builds/wheel_verify.sh

Current build is failing since it's trying to build a python2 whl after the new changes:
https://travis-ci.org/tensorflow/addons/jobs/639961631#L281
The real issue is that the configure script now removed a hacky PYTHON_VERSION env lookup. Instead I've created a symlink in the loop. 
Also cleaned up some hard-coded hackiness in the auditwheel check.

FIX: Build with the correct python version

---

tensorflow_addons/callbacks/tqdm_progress_bar.py

This is a simple change that will allow custom formatting of metrics for the tqdm status bar. This is especially useful if you have small loss values and want to see it in scientific notation. Replace `metrics_format` with `'{name}: {value:e}'`

Custom metrics formatting in tqdm status bar

---

.github/workflows/macos_nightly.yml
.github/workflows/ubuntu_nightly.yml
.github/workflows/windows_nightly.yml
README.md
configure.sh
docs/overview.md
requirements.txt

Linked to #893
I'll try to list here the pros and cons so that we can decide if we go forward with this or not:
Pros:
* The CI can't fail out of nowhere because or a bug/API change on the Tensorflow side. The CI is more deterministic than before.
* The bump of the tensorflow version can be done in a isolated manner, in a pull request.
* We can make a minimal Dockerfile used for testing and tooling locally, and include bazel and tensorflow inside. Contributors won't have to download tf-nightly every day. Build once, run every day :)
* We don't have to support a single version of tensorflow, we can support a range of them and test against the oldest and the most recent in the CI: (eg: >=2.0.0,<2.2.0)
* If the dependency doesn't change every day, it means that the unit tests are …

Target tensorflow stable instead of tensorflow-nightly.

---

tensorflow_addons/optimizers/weight_decay_optimizers.py

`tfa.optimizers.SGDW` and `tfa.optimizers.AdamW` do not have `global_step` argument for `minimize()` method.
But the document describes about them. This PR removes them.

Fix: Remove descriptions about global_step in tfa.optimizers.{SGDW, AdamW}

---

.flake8

See #932 for more context
Some modifications were added to ensure we don't get conflicts between black and flake8. 
Actually pycodestyle have checks that are really nice to have even if we use black. It would be beneficial for us to keep them. e.g.:
* do not compare types, use ‘isinstance()’
* do not use variables named ‘l’, ‘O’, or ‘I’
* do not use bare except, specify exception instead
and so on...
For this reason, I followed black's documentation and only changed a few rules to ensure compatibility.

Ensuring flake8 is compatible with black.

---

tools/ci_build/builds/builds_common.sh
tools/ci_build/install/ci_requirements.txt
tools/ci_build/install/install_ci_dependency.sh

"Search in the whole project" says that those variables/functions are unused.

Removing dead code.

---

docs/tutorials/tqdm_progress_bar.ipynb
tensorflow_addons/callbacks/tqdm_progress_bar.py

This PR fixed TQDM Progress Bar tutorial failure (cause: installing importing tfa after deep reloading tqdm), this PR also fixed the comments for TQDM Progress Bar so that the doc generated on Tensorflow.org can display the arguments nicely (https://www.tensorflow.org/addons/api_docs/python/tfa/callbacks/TQDMProgressBar)
https://github.com/tensorflow/addons/issues/934

fixed tqdm progress bar tutorial and comments

---

.github/workflows/macos_nightly.yml
.github/workflows/ubuntu_nightly.yml
.github/workflows/windows_nightly.yml
tools/ci_build/builds/tf_auditwheel_patch.sh

Feedback cycle on this is painfully slow. If this doesn't work tomorrow then I'll modify the yaml so we can troubleshoot on each push.
PyPi Github action is only for linux. We could work around this by uploading /downloading the artifacts and pushing once. But I'd like to see the builds succeed and publish prior to optimizing so as to change as little as possible.

FIX: GitHub build

---

tensorflow_addons/callbacks/time_stopping.py

Discovered by @RomainBrault in https://github.com/tensorflow/addons/issues/964, the time_stopping callback breaks when the training ends before the proposed time is passed, due to `self.stopped_epoch` been undefined when that case happened. This small PR fixed it. Thanks @RomainBrault for catching the bug and proposed fix!

Quick Fix for Time_Stopping Callback Bug

---

.github/workflows/ci_test.yml
build_deps/tf_dependency/tf_configure.bzl
tensorflow_addons/tensorflow_addons.bzl
tools/ci_build/builds/builds_common.sh
tools/ci_build/code_format.sh

Linked to #991
I bumped the buildifier version from 0.4.5 to 0.29 because there is a very nice option (`-r` for recursive search in directory) that we need.
The check runs in 3s :)

Moved the bazel format check outside the sanity check. 

---

tensorflow_addons/layers/BUILD
tensorflow_addons/layers/README.md
tensorflow_addons/layers/__init__.py
tensorflow_addons/layers/polynomial.py
tensorflow_addons/layers/polynomial_test.py

This is from internal design to open-source the DCN network from paper https://arxiv.org/abs/1708.05123

Add PolynomialCrossing to Addons

---

.github/workflows/ci_test.yml
.gitignore
makefile
tools/ci_build/install/buildifier.sh
tools/ci_build/install/clang-format.sh
tools/docker/Dockerfile_formatting
tools/format.py
tools/pre-commit-docker.sh
tools/pre-commit.sh

Use docker to run. Is quite fast if buildkit is available (docker 19.03+). On my machine, the docker build step takes 0.2s.
I had to remove the buildifier from the gitignore as it was ignoring the install script that I made. Now that everything runs in docker I'm not sure this glob ignore is needed. We can change it later if necessary.

New pre-commit running black/buildifier/clang-format.

---

.github/workflows/ci_test.yml
CONTRIBUTING.md
tools/docker/sanity_check.Dockerfile
tools/run_sanity_check.sh

See #991 for background. 
This pull request add a sanity check that users can run locally.
It requires docker to run, but the daemon doesn't have to be present locally. 
It makes use of buildkit if the docker daemon installed is recent enough:  https://docs.docker.com/develop/develop-images/build_enhancements/
Basically buildkit does everything in parallel if possible (pulling images, getting docker context, executing run statements...)
Without buildkit (second pass): 90s
with buildkit (second pass) 60s
I used images as small as possible, I couldn't use alpine python because it lacked a gcc compiler.
later on with docker buildx and remote caching, we may have the luxury of running docker in the CI for very fast tasks.
I'll also do some cleanup about duplicated code for install after this …

Running the sanity check locally

---

tensorflow_addons/layers/polynomial.py

Windows/MacOS builds failed last night on Py35 for trailing comma.
Related: https://github.com/psf/black/issues/419
But going forward we should probably test oldest python and newest python in CI

FIX: Remove trailing comma from double star

---

.github/workflows/ci_test.yml
.github/workflows/macos_nightly.yml
.github/workflows/manylinux_nightly.yml
.github/workflows/release.yml
.github/workflows/windows_nightly.yml
tensorflow_addons/rnn/cell_test.py
tools/ci_build/verify/check_typing_info.py
tools/docker/Dockerfile_formatting
tools/docker/sanity_check.Dockerfile

Python being really good at backward compatibility, I think all our tests should run with the oldest version of python we support and some selected tests should run with the most recent version that we support.
See #1024

Use py35 instead of 36 as much as possible.

---

.github/workflows/macos_nightly.yml
.github/workflows/release.yml
.github/workflows/windows_nightly.yml

So the shared bazel artifact was meant to improve build time, but we've been getting timeout errors on our uploads/downloads using GitHub actions:
https://github.com/tensorflow/addons/actions/runs/35265244
IMO the extra computation time is not really an issue compared to missing releases.

BLD: Remove bazel artifact upload/download

---

tools/docker/sanity_check.Dockerfile

Better use of the docker cache for faster local sanity check. 
Since the commands are the same, starting from the same base image, the second download of tensorflow is skipped and uses the docker cache.
Yes I have a bad internet connection 😢

Don't download tensorflow multiple times.

---

.github/workflows/ci_test.yml
tools/docker/sanity_check.Dockerfile
tools/docs/doc_requirements.txt

For now it's not super fast to use docker build in the CI, but I tried without and for building the docs, it's not much faster.
Wait until [docker buildx](https://github.com/docker/buildx) becomes stable and we're going to have super fast CI builds with remote caching!

Add a test for the documentation.

---

README.md

* Removed 0.5.2 since there is no reason to use that instead of 0.6
* Added 0.8.1
* Updated 0.7.0 to 0.7.1
Do we think it is sufficient to just label the tensorflow version? tf-gpu or tf-cpu could be added but IMO it can be inferred.

DOC: Update bld matrix

---

.github/workflows/release.yml

When we cut the 0.8 release, 3 github actions were triggered:
https://github.com/tensorflow/addons/actions?query=workflow%3Aaddons-release
Need to limit this to just published releases.

BLD: Limit releases to published

---

tools/docker/pre-commit.Dockerfile
tools/format.py
tools/pre-commit.sh

flake8 is very fast to run and contributors often submit pull requests with this check failing. I believe it will improve the contributor's experience to have the check running locally automatically.
I also remove the python stacktrace when there is an issue because it would make it harder to see what is the real problem.

Use flake8 in the pre-commit.

---

pyproject.toml
tensorflow_addons/layers/normalizations.py
tensorflow_addons/layers/normalizations_test.py
tensorflow_addons/layers/wrappers.py
tensorflow_addons/layers/wrappers_test.py

related to https://github.com/tensorflow/addons/issues/988

run black normalizations and wrappers

---

tools/ci_testing/addons_cpu.sh
tools/docker/cpu_tests.Dockerfile

Keep in mind that the total time vary a lot in the CI, so it might not be fair to compare using that. This is why I compare the speed of the steps:
| Step | before (s)| after (s)|
| ------------- |:-------------:| -----:|
| Downloading docker image | 74 | 22 |
| installing tf | 93 | 54|
| installing bazel | 0 | 8|
The speed of compiling and testing should in theory be the same.
I also think it's nice to start from scratch to build and run because:
* it helps other to understand how to build tensorflow addons from source locally. We don't start from a big docker image with who-knows-what already installed in it. 
* Here we have full control over the python version and bazel version for example. 
We might want to do the same for the gpu and releases.

Making the tests faster.

---

tensorflow_addons/optimizers/yogi.py
tensorflow_addons/optimizers/yogi_test.py

It is found initial_accumulator_value=1e-6 works better for a range of tasks. Thus switching the default value.

Changes default value of Yogi hyper-parameters

---

configure.py

The function was too long (150 lines) there were too many variables floating around. It hurts readability. If the configure.py is simpler, it'll be easier to debug build errors for contributors.

Refactoring configure.py

---

README.md

Don't love this process. Perhaps we make it e.g. `0.8.x`

DOC: Update versions in build matrix

---

tensorflow_addons/utils/types.py

Add `tf.SparseTensor` into `TensorLike` type (`tensorflow_addons/utils/types.py`) as @autoih @gabrieldemarmiesse mentioned in #1088 .

Add tf.SparseTensor into TensorLike type

---

tools/docker/sanity_check.Dockerfile

I believe it's a good opportunity to check the backport bot. We don't have to merge the PR opened by the bot, we can just close it afterwards.

Used pypi release for typedapi

---

.github/workflows/macos_nightly.yml
.github/workflows/release.yml

Update macos build version

---

tools/docker/gpu_tests.Dockerfile

Not really a good way to handle this. But it returns CI and then we can go from there.

HOTFIX: pin docker container pip install to py36

---

tools/docker/cpu_tests.Dockerfile

It only takes 10 more seconds in the test suite but it should prevent quite some bugs.
I can't find a way to pin the version of the CUDA image because they don't version it.
Is there a document somewhere on the web explaining where this image comes from, what are the tags and what is inside?

Test that the wheel works in a fresh environment.

---

tensorflow_addons/activations/hardshrink.py
tensorflow_addons/activations/hardshrink_test.py

See #1114
For the moment the function is not exposed publicly. We'll see later what is the best way to expose it to the users.

Added a py function for hardshrink

---

tensorflow_addons/seq2seq/attention_wrapper_test.py

74s -> 51s
It's not needed to train the model to see if it saves itself correctly.
See #1143

Made the attention_wrapper_test faster.

---

tensorflow_addons/optimizers/rectified_adam_test.py

111s -> 18s
If it's just a matter of pinning the numbers the optimizer should produce, then the number of steps doesn't matter.
See #1143

Made the rectified adam test faster.

---

tools/docker/cpu_tests.Dockerfile
tools/docker/finish_bazel_install.sh
tools/docker/gpu_tests.Dockerfile
tools/docker/sanity_check.Dockerfile

When running a dockerfile, bazel doesn't get installed completely after running the `tools/ci_build/install/bazel.sh`. Actually, when running the first build, bazel does 3 things:
* Unpacking the bazel install
* Downloading the JDK
* Downloading from http archives set in the `WORKSPACE` file.
This delayed install isn't really compatible with how docker build works, since those install steps are not cached. 
To get around the bazel hack of delayed install, I made another hack (fighting fire with fire XD) which is to clone the master branch and do a dry run of `bazel build` in a previous layer.
In that way, when the cache gets invalidated at the COPY step, we already have a full bazel install, no need to download the ~300MB of additional stuff at every build.
Depending on your internet …

Finish the bazel install before building addons

---

tensorflow_addons/activations/tanhshrink.py
tensorflow_addons/activations/tanhshrink_test.py

add tanhshrink_py

---

pyproject.toml
tensorflow_addons/losses/__init__.py
tensorflow_addons/losses/focal_loss.py
tensorflow_addons/losses/giou_loss.py
tensorflow_addons/losses/giou_loss_test.py
tensorflow_addons/metrics/multilabel_confusion_matrix.py
tensorflow_addons/metrics/r_square.py
tensorflow_addons/optimizers/__init__.py
tensorflow_addons/optimizers/lookahead.py
tensorflow_addons/optimizers/moving_average.py
tensorflow_addons/optimizers/weight_decay_optimizers.py
tensorflow_addons/text/__init__.py
tensorflow_addons/text/crf.py
tensorflow_addons/text/crf_test.py

Fix #988 
If any PR has a conflicts, I'll fix them myself as it's not trivial to do (checkout the toml -> format with black -> commit -> merge master -> commit)

Complete the black formatting migration.

---

tensorflow_addons/optimizers/novograd_test.py
tensorflow_addons/optimizers/stochastic_weight_averaging_test.py

stochastic_weight_averaging_test: 57s -> 15s
novograd_test  : 58s -> 14s
related to https://github.com/tensorflow/addons/issues/1143

make two tests faster

---

tools/ci_build/builds/release_linux.sh

Use less disk space when building wheels. It was causing issues in Github actions (no space left on device).
it should save use ~2.5GB of disk
We can look later on for a clean and permanent fix.

Fix broken master branch

---

tensorflow_addons/optimizers/lookahead_test.py

Reduce number of samples from 10e5 to 10e4, increase error from 1e-4 to 1e-3
CPU test time: 33s -> 17s
Related to #1143 
cc @gabrieldemarmiesse

[Test] Speed up lookahead_test

---

tensorflow_addons/optimizers/moving_average_test.py

Increase error: 1e-3 -> 5e-3
Reduce number of samples: 50000 -> 5000
Use a simpler optimizer: adam -> sgd
Reduce epochs: 10 -> 5
CPU Test time: 35s -> 8s
Related to #1143

[Test] Speed up moving_average_test

---

tensorflow_addons/utils/test_utils.py

This came in super handy for #1173 and would be helpful while tackling #1143.
I can close this PR if you don't think it needs to be included in the codebase.

Function that print each function's execution time 

---

tensorflow_addons/image/transform_ops_test.py

`_test_grad` was the most expensive call. Reduce the number of calls by removing useless differing image sizes.
Local test: 55s -> 21s 
Related to #1143

[Test] Speed up transform_ops_test

---

tensorflow_addons/image/filters_test.py

filters_test: 56.8s -> 41s (by replacing divide op)
related to [1143](https://github.com/tensorflow/addons/issues/1143)

Have faster filters_test 

---

tensorflow_addons/image/dense_image_warp_test.py

Reduce few cases in `shapes_to_try` and have 40.9s -> 19.6s
related to [1143](https://github.com/tensorflow/addons/issues/1143)

Fast dense_image_warp_test

---

.github/workflows/notify_codeowners.py
.github/workflows/notify_codeowners.yml

* Usernames are case insensitive. Fix that.
* Do not notify the author of the pull request
* If there is nobody to notify, don't send a message.
* The default mode is the debug mode. `--no-dry-run` to run for real.

Less spamming from the bot when notifying codeowners

---

CONTRIBUTING.md

Fix #1116
A "search in the whole projects" tells me that those private docker images are not used anymore.

Remove all mentions of nosla.

---

tensorflow_addons/optimizers/cyclical_learning_rate.py

The current CyclicalLearningRate subclasses (TriangularCyclicalLearningRate, Triangular2CyclicalLearningRate, and ExponentialCyclicalLearningRate) are responsible for generating their own scale_fn. So they should not have scale_fn in their function arguments.

Removed erroneous scale_fn from CLR subclasses

---

tensorflow_addons/activations/gelu_test.py
tensorflow_addons/activations/hardshrink_test.py
tensorflow_addons/activations/lisht_test.py
tensorflow_addons/activations/mish_test.py
tensorflow_addons/activations/softshrink_test.py
tensorflow_addons/activations/tanhshrink_test.py

https://github.com/tensorflow/addons/pull/1137#issuecomment-592125603

Better precision when comparing implementations.

---

.github/workflows/release.yml

Last night's release failed:
https://github.com/tensorflow/addons/runs/485118606?check_suite_focus=true
This was because the wheel file did not match `tensorflow_addons-*.whl` since its `tfa-*`. A single wheel artifact is downloaded so a wildcard should work here.

Fix test-release for nightlies

---

tensorflow_addons/optimizers/lazy_adam_test.py

The given value already is the default one, and I am exploring actually removing that parameter from `test_util.run_in_graph_and_eager_modes`, as nobody ever sets it to `False`.

Remove explicit `reset_test=True` from test.

---

tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/seq2seq/attention_wrapper_test.py

This is a suggested fix for #1194.
The `time` attribute has a limited use in both internal and user codes:
* Internal: it was only used to append to `alignment_history`, but here it is an alias for `alignment_history.size()`
* User: the time component can be inferred from input or output of the layer.
Fixes #1194.

Remove time field from AttentionWrapperState

---

README.md

Some people make bug reports and think that the tf-nightly is compatible with tfa-nightly, which is not the case. Let's try to emphasize that in the readme.

Some more info about the nightly.

---

.github/workflows/release.yml

`runner.os` is always linux. That was a stupid bug.

Fix bug where only the linux wheel is uploaded.

---

.github/workflows/release.yml
README.md
setup.py

Because they're not built at the exact same time in github actions, the 9 wheels we upload have a different version number. Here we use the last commit time. It's also then easier to track back the commit used from the version number.

Fix bug where each wheel has a different version number.

---

tensorflow_addons/losses/quantiles_test.py

Related to #1202 but doesn't fix it. It just enables passing tests to run in the CI

Enbale passing tests in quantiles_test.py

---

tensorflow_addons/metrics/multilabel_confusion_matrix_test.py

This does not fix fully #1204 but at least now we're running some tests.

Enable passing tests in multilabel_confusion_matrix_test.py

---

tensorflow_addons/layers/BUILD
tensorflow_addons/layers/poincare_test.py

Related to #1205 but doesn't close it.
Skipping the failing test. Should be fixed later on.

Enable testing of poincare_test.py

---

CONTRIBUTING.md
tools/pre-commit.sh

We don't have a windows Dockerfile but for the moment it's enough. With git bash on PATH and Docker desktop installed, everything worked out of the box. 
Except the pesky file path starting with / being translated automatically by git bash when using a windows command (ex; docker desktop). MSYS_NO_PATHCONV=1 is here to disable it.
That was way less pain than what I imagined 😄 
Fix #1134
There are no instructions to compile custom ops with windows but I think that people motivated enough to do that will be able to look at the github actions file to find out how it works.

Added instructions to work on Addons on Windows.

---

tensorflow_addons/text/BUILD
tensorflow_addons/text/__init__.py
tensorflow_addons/text/parse_time_dummy_test.py
tensorflow_addons/text/parse_time_op.py
tensorflow_addons/text/parse_time_op_test.py

It's a bit better than `text has no attribute parse_time`.

Better error message for parse_time on windows.

---

tensorflow_addons/losses/BUILD
tensorflow_addons/losses/__init__.py
tensorflow_addons/losses/npairs.py
tensorflow_addons/losses/npairs_dummy_test.py
tensorflow_addons/losses/npairs_test.py

A descriptive error message is better than `losses has no attribute ...`.

Better error message for npairs on Windows

---

tensorflow_addons/layers/poincare.py
tensorflow_addons/layers/poincare_test.py

Closes #1205 
axis is used in `reduce_sum` and supports several types:
https://github.com/tensorflow/tensorflow/blob/r2.1/tensorflow/python/ops/math_ops.py#L1555-L1564

Fix typing for poincare layer

---

CONTRIBUTING.md
build_deps/build_pip_pkg.sh
setup.py
tools/docker/sanity_check.Dockerfile

As we move towards being more and more contributor-friendly, this move is to make the install easier.
The following commands will work on all systems:
```bash
pip install -e ./
pip install ./
pip install git+https://github.com/tensorflow/addons.git # useful to ask people to try the latest commit.
```
Note that none of those commands build any SO file. So there is that.

Simpler install for contributors.

---

tensorflow_addons/metrics/BUILD
tensorflow_addons/metrics/metrics_test.py
tensorflow_addons/metrics/multilabel_confusion_matrix.py
tensorflow_addons/metrics/r_square.py

Fix #1229 and it's a small step for #992

Check `update_state` signature for metrics.

---

tensorflow_addons/activations/gelu.py

Exposed the pure python gelu implementation publicly.

---

.github/workflows/release.yml

Fast-fail was disabled only for the first jobs. When testing the wheels or uploading it, it's important to have the results of all jobs.

Remove fast-fail for easier debug.

---

.dockerignore
.github/workflows/make_wheel_Linux.sh
.gitignore
tools/docker/build_wheel.Dockerfile

This makes the process easily reproducible locally.
The output argument can feel a bit strange. It's used in docker buildkit when the result of the build should be something else than docker images (eg compiled binaries). See https://github.com/moby/buildkit#local-directory
Later on, in the same dockerfile, we can integrate the test of the wheel in a fresh environement. It's going to be faster than to pop a new github action runner just for that.

Build the linux wheel in a dockerfile.

---

tensorflow_addons/utils/ensure_tf_install.py

Better user experience when the version of TF is not right.

---

tensorflow_addons/metrics/multilabel_confusion_matrix_test.py

Closes #1204 
The default dtype for a Keras metric results in a float:
https://github.com/tensorflow/tensorflow/blob/r2.1/tensorflow/python/keras/metrics.py#L145
However, since this is a confusion matrix I'm wondering if we should always cast it as an integer? 
++ @SSaishruthi as code owner for input

Update dtype for multilabel CM test

---

pytest.ini

By default, pytest doesn't make a list of all tests that have failed (only the traceback). It's useful to have it though, especially in the CI when a lot of tests are failing. 
This pull request changes the default options for pytest. `-r` is for creating a small report at the end. `f` is for failed, `E` is for errors, `x` is for xfail, the tests we know are failing (see #1303 for an example). I didn't include the skipped tests, because tf.test.TestCase has a `test_session` that is skipped for every class and that would be a too much to display all of them at the end.

Better error reporting in the CI

---

tools/docker/cpu_tests.Dockerfile
tools/run_cpu_tests.sh

So the `No module named _sqllite3` that we had before was an issue of python not being compiled with sqllite support. So nothing we can do about it in the custom-ops image. 
Something we can do though is running it in the standard python3.5 docker image since the python used here supports it. So now, if we want to look at the code coverage in the master branch, we just need to look at the logs of the minimal cpu build.
Also the progress plain is used to have the full output when building the image locally. By default buildkit swallow the output. I tried and it also worked when `DOCKER_BUILDKIT=0` so my hope is that this option won't break the script for people who don't have a version of docker recent enough.
See https://github.com/tensorflow/addons/pull/1243#issuecomment-596510466 
and …

Added code coverage to tools/run_cpu_tests.sh

---

configure.py
tools/install_deps/finish_bazel_install.sh

We need to clone a specific commit to avoid making our CI depend on a moving target. Even when using a hack like in this case.
Hopefully one day we can get rid of this hack. I wish there was a bazel command like `bazel download-jdk`

Fixing the master branch.

---

.github/workflows/ci_test.yml
tensorflow_addons/activations/mish_test.py
tensorflow_addons/losses/giou_loss_test.py
tensorflow_addons/metrics/cohens_kappa_test.py
tensorflow_addons/seq2seq/loss_test.py
tools/docker/cpu_tests.Dockerfile

I have marked as xfail the tests which are not passing. What's left to determine is which bugs come from tensorflow addons and which bugs come from us.
Then can then fix the tests one by one in other pull requests.

Running minimal cpu tests on 2.2.0-rc0

---

tensorflow_addons/losses/giou_loss.py
tensorflow_addons/losses/giou_loss_test.py

Related #1320.
As [Reduction.NONE](https://www.tensorflow.org/versions/r2.2/api_docs/python/tf/keras/losses/Reduction) has changed. Change reduction mode to Reduction.SUM_OVER_BATCH_SIZE for unifying graph and eager reduction behavior.

fix giou loss test

---

tensorflow_addons/activations/softshrink.py

I don't know why I didn't think about using tf.where the first time, it's much easier.

Simpler python implementation of softshrink.

---

tensorflow_addons/BUILD
tensorflow_addons/conftest.py
tensorflow_addons/losses/focal_loss_test.py
tensorflow_addons/metrics/cohens_kappa_test.py
tensorflow_addons/utils/BUILD
tensorflow_addons/utils/test_utils.py

So, replacing this `run_all_in_graph_and_eager_mode` is quite difficult but it's worth it for two reasons:
* It's not a public API, so it can go away at any time. The behavior can change silently.
* We don't need to execute the test methods in graph mode. We only need to execute a small part of the test in graph mode (for the layers, it's the `call` method, for the metrics/losses, it's the `update_state`...). It allows us to enjoy the eager mode outside those selected functions and we don't have to do `self.session` `self.evaluate(tf.compat.v1.initialize_global_variables(...))`. We can just do `.numpy()` to get results. This has the benefit to make testing much easier and bring new contributors who might be put off by this testing which looks like coding in tensorflow 1.x.
* It does not …

Alternative to run_all_in_graph_and_eager_mode

---

tensorflow_addons/metrics/cohens_kappa_test.py

Nothing changed except the fixtures and going from method to function.

Using the pytest fixture rather than run_all_in_keras_and_eager_mode in cohen_kappa

---

tensorflow_addons/layers/optical_flow_test.py

This is to progressively get rid of the `@run_all_in_graph_and_eager_mode`. I try no to take everything out of the class at once to avoid a big diff.
See #1328

Function may be static in optical_flow_test.py

---

tensorflow_addons/text/parse_time_op.py
tensorflow_addons/text/parse_time_op_test.py

Test parse time in eager mode

---

tensorflow_addons/activations/README.md
tensorflow_addons/callbacks/README.md
tensorflow_addons/image/README.md
tensorflow_addons/layers/README.md
tensorflow_addons/losses/README.md
tensorflow_addons/metrics/README.md
tensorflow_addons/optimizers/README.md
tensorflow_addons/rnn/README.md
tensorflow_addons/seq2seq/README.md
tensorflow_addons/text/README.md

Updated the README files concerning testing.

---

tensorflow_addons/layers/tlu_test.py

Removed run_all_in_graph_and_eager_mode in tlu_tests.

---

tensorflow_addons/metrics/r_square.py
tensorflow_addons/metrics/r_square_test.py

I noticed that the `RSquared` metric does not behave in the same way as the `scikit-learn` implementation of the same metric for multivariate regression (in `scikit-learn` known as "multioutput"). First I thought I should mend it to align with the `scikit-learn` implementation that calculates separate scores for each label element and aggregates the scores. Then I started asking myself whether there might be other ways of interpreting R<sup>2</sup> in higher dimensions. Looking at the definition presented in https://en.wikipedia.org/wiki/Coefficient_of_determination, it does look like it might make sense to extend it to higher rank data types, but this can be done in different ways, and I am unsure what would make sense mathematically. The `scikit-learn` approach at least makes some sense …

Multivariate r2

---

tensorflow_addons/metrics/cohens_kappa.py
tensorflow_addons/metrics/cohens_kappa_test.py

The errors were:
```
================================================================================================================== FAILURES ==================================================================================================================
_______________________________________________________________________________________________ CohenKappaTest.test_keras_multiclass_reg_model _______________________________________________________________________________________________
[gw3] linux -- Python 3.7.4 /opt/conda/bin/python
self = <tensorflow_addons.metrics.cohens_kappa_test.CohenKappaTest testMethod=test_keras_multiclass_reg_model>
def test_keras_multiclass_reg_model(self):
kp = CohenKappa(num_classes=5, regression=True, sparse_labels=True)
inputs = …
```

Fix cohen kappa when using tf 2.2.0rc1

---

tensorflow_addons/image/connected_components.py

See for the current broken markdown:
https://www.tensorflow.org/addons/api_docs/python/tfa/image/connected_components
Adds a note that any integer/floating/boolean types are supported as per:
https://github.com/tensorflow/addons/blob/f4db0b1b23788d5b512dfd758bcef491d5a7da88/tensorflow_addons/custom_ops/image/cc/ops/image_ops.cc#L142

update doc string to fix broken one and updates some typing errors

---

tensorflow_addons/seq2seq/basic_decoder_test.py
tensorflow_addons/seq2seq/decoder_test.py
tensorflow_addons/utils/test_utils.py

The class `keras_parametrized.TestCase` is used for its parameter `should_run_eagerly` to be passed to a compile function. This was not used. This class was useful only to parametrize the tests but we can use a public class instead.
See https://github.com/tensorflow/tensorflow/blob/3fcd7f5978149dcce229c3d203543c61c9645599/tensorflow/python/keras/keras_parameterized.py#L303

Removed usage of keras_parametrized.

---

tensorflow_addons/image/dense_image_warp_test.py

Our longest test so far in the test suite `test_interpolation` went from 23s to 2s. I guess that tracing 20+ for loops is expensive :p
See #1328
not much has changed, except indentation and `self.assertAllClose` -> `np.testing.assertAllClose`.

Used fixture instead of run_all_in_eager_and_graph_mode

---

tensorflow_addons/image/distance_transform_test.py

I don't think it needs to be tested twice in graph and eager mode. We have here a simple custom op, so graph or eager mode wouldn't change anything.
The gpu failures look unrelated.

Took some functions outside the run_all_in_eager_and_graph_mode in distance_transform

---

tensorflow_addons/layers/polynomial_test.py

Removed run_all_in_graph_and_eager_mode in polynomial_test.py

---

tensorflow_addons/optimizers/stochastic_weight_averaging_test.py

I didn't add the fixture to test in eager mode because running this test in eager mode takes 40seconds compared to 5 seconds with tf.function.
See #1328

Moved test_fit_simple_linear_model function out of run_all_in_graph_and_eager_mode.

---

tensorflow_addons/seq2seq/beam_search_ops_test.py

We only need to run this test in eager mode, it makes it more readable too.

Test gather tree in eager mode only because it's a custom op

---

tensorflow_addons/seq2seq/loss_test.py

I runs in full eager mode + with the tf.function enabled by default for keras layers.
@guillaumekln that might be useful for #1371 
`get_test_data` is here to replace the `setup` method. I'll convert to pytest the rest of the tests in this file in another pull request.
`np.testing.assert_allclose(calculated_loss, expected_loss, rtol=1e-6, atol=1e-6)`
`np.testing.assert_allclose` is more strict than the tf counterpart `self.assertAllClose` so I took the rtol and atol from the `self.assertAllClose` to have the same behavior. Otherwise the tests were not passing.

run keras compatibility test for sequence loss with v2 behavior.

---

tensorflow_addons/optimizers/rectified_adam.py
tensorflow_addons/optimizers/rectified_adam_test.py

Fix the serialization bug of rectified adam.

---

tensorflow_addons/image/utils_test.py

Moved method out of the run_all_in_graph_and_eager_mode in utils_test.py

---

tensorflow_addons/activations/tanhshrink_test.py
tensorflow_addons/utils/test_utils.py

See #1328
For `assert_allclose_according_to_type` this is actually a copy of the tensorflow code.

Used pytest only to test tanshrink in eager mode

---

tensorflow_addons/metrics/r_square_test.py

Removed run_all_in_graph_and_eager_mode in r_square_test.py

---

tensorflow_addons/activations/gelu_test.py

Get function out of run_all_in_graph_and_eager_mode in gelu tests.

---

tensorflow_addons/image/connected_components_test.py

Moved tests out of run_in_graph_and_eager_mode in connected components.

---

tensorflow_addons/activations/mish_test.py

Dug into this a bit and found that this check could conceivably fail for TF2.1. It does empirically appear more common on TF2.2, and I don't have an answer about what could have changed. As previously discussed we have no guarantee the py gradient should behave the exact same at this precision:
https://github.com/tensorflow/addons/issues/1220#issuecomment-595871107
Part of #1320

Relax gradient assertion for mish activation

---

tensorflow_addons/activations/hardshrink_test.py

Moved test out of run_all_in_graph_and_eager_mode in hardshrink.

---

tensorflow_addons/image/distance_transform_test.py

Moved test out of run_in_graph_and_eager_mode in distance_transform.

---

.github/CODEOWNERS
tensorflow_addons/image/BUILD
tensorflow_addons/image/__init__.py
tensorflow_addons/image/cutout_ops.py
tensorflow_addons/image/cutout_ops_test.py

add cutout image op

---

tensorflow_addons/losses/contrastive_test.py

Moved test out of run_in_graph_and_eager_mode in contrastive_test.py

---

tensorflow_addons/conftest.py
tensorflow_addons/layers/optical_flow_test.py
tensorflow_addons/utils/test_utils.py

I added two fixtures, one to run the test two times, one with CPU and one with GPU.
The other fixure I added is when a test is needed to run multiple times with `channels_first` and `channels_last`.
To use fixtures, either use `@pytest.mark.usefixture` for fixtures that don't provide parameters (like gpu and cpu) or you can use directly the name of the function as parameter for the test. Here `data_format`.
More about fixtures: https://docs.pytest.org/en/latest/fixture.html

Added multiple useful fixtures.

---

tensorflow_addons/layers/maxout_test.py

Moved test out of run_in_graph_and_eager_mode in maxout.

---

tensorflow_addons/activations/sparsemax_test.py

related to https://github.com/tensorflow/addons/issues/1328
cc. @AndreasMadsen

move test out of run_all_in_graph_and_eager_modes in sparsemax_test

---

tensorflow_addons/seq2seq/loss.py
tensorflow_addons/seq2seq/loss_test.py

For previous versions, we removed the `reduction` attribute to force tf.keras to call the main `__call__` method. Otherwise, it calls the `call` method where we have no way of controlling the reduction logic.
In 2.2, tf.keras has a new way of dealing with loss objects (see the `LossContainer` class). It now always calls `__call__` and requires the `reduction` attribute to exist.
This new logic is only enabled for V2 execution mode so this commit also disables the deprecated V1 graph mode for this test.
Related to #1320.
Note: this change is only compatible with TensorFlow 2.2 so I'm opening a draft PR for now.

Update SequenceLoss for TensorFlow 2.2 compatibility

---

tensorflow_addons/losses/lifted_test.py

Removed run_in_graph_and_eager_mode in lifted_test.py

---

tensorflow_addons/activations/sparsemax_test.py

Moved test out of run_in_graph_and_eager_mode in sparsemax.

---

tensorflow_addons/losses/contrastive_test.py
tools/pre-commit.sh
tools/run_build.sh
tools/run_cpu_tests.sh
tools/run_google_cloud_tests.sh
tools/run_gpu_tests.sh
tools/run_sanity_check.sh

The Kokoro team has upgraded docker. We can now use buildkit. This should come in handy to merge the CI code for CPU and gpu.

Using buildkit all the time when building docker images.

---

tensorflow_addons/image/compose_ops.py
tensorflow_addons/image/compose_ops_test.py

Small change so operations using `blend` don't have to cast their results to `tf.uint8` before using it. (#1452)

add dtypes to blend

---

tensorflow_addons/activations/mish.py

The fallback should be the python version, not the custom op.

Fix the mish fallback.

---

tensorflow_addons/layers/normalizations_test.py

Moved tests out of run_in_graph_and_eager_mode in multithread attendion

---

tensorflow_addons/__init__.py
tensorflow_addons/utils/ensure_tf_install.py

Added a warning when importing addons and using the wrong version of TF.

---

tensorflow_addons/optimizers/weight_decay_optimizers.py
tensorflow_addons/optimizers/weight_decay_optimizers_test.py

Fixes an error where the list of decay variables is unhashable because they are compared without var.ref() or var.experimental_ref(). This patch is forward compatible with TF 2.2.0.

Fix unhashable decay_var_list

---

tools/docker/build_wheel.Dockerfile

@seanpmorgan 
That's still annoying because I wanted to add a `--mount=type=cache,dest=/root/.cache/pip` but It seems like it won't be possible.

Use a minimal docker image to build wheels. Fix the master branch build.

---

tensorflow_addons/layers/wrappers_test.py

One of our test has become flaky after we increased the precision required. The default `atol` and `rtol` of `tf.test.TestCase.assertAllClose` and `np.testing.assert_allclose` are not the same. This  pull request fixes this.

Fix the flaky test in wrapper_test.py

---

.github/workflows/release.yml

We've been getting a lot of intermittent failures from our nightly publishing:
https://github.com/tensorflow/addons/runs/553687744?check_suite_focus=true
I'm not sure this is the cause since we're getting a 502 error, but still a better practice to pin this action version.

Pin pypi github action

---

.github/workflows/release.yml

Given #1536 and the non-zero chance that there is a network issue when we make a release I believe this is a good thing to add. 
For example if we make a release and one or more uploads fails. We'd be unable to simply re-run the job because whatever uploads did work the first time would fail for the package already existing on pypi. The only other work around I would see for this is bumping a patch version or commenting out some of the uploads.

Do not fail fast for pypi upload

---

tensorflow_addons/optimizers/weight_decay_optimizers.py
tensorflow_addons/optimizers/weight_decay_optimizers_test.py

This is a quick fix to restore compatibility with TF 2.2 which adds a new keyword argument.
See #1267 for the discussion.
@gabrieldemarmiesse, @seanpmorgan  :)
Closes #1267

Add **kwargs to apply_gradients in weight_decay_optimizers.

---

README.md

Closes #1317 along with the warnings that have been merged.

Update documentation regarding compatibility

---

tensorflow_addons/callbacks/tests/tqdm_progress_bar_test.py
tensorflow_addons/callbacks/tqdm_progress_bar.py

Follow-up on #1365
The samples mode is not available anymore. It was causing some issues. It makes the code quite complex to support both, in the future, a refactor to remove all other pieces of code supporting "samples" mode should be removed.
I also made the tests more complex to be sure that it works with the right numbers.
@bjtho08 
@lminer
Please take a look, I used your inputs about the `self.params` and the validation metrics and now it should work out. try it locally with 
```
pip install git+https://github.com/gabrieldemarmiesse/addons.git@fix_progress_bar
```
and report if it works for you. 
Closes #1495

Fix TQDM Progress bar in TF 2.2.0

---

tools/testing/source_code_test.py

This should save us some work during code reviews. 
We might want to discuss for this policy about experimental APIs though. See https://github.com/tensorflow/community/pull/218
Should we be more permissive? Less permissive?
Closes  #1279

Add checks for code quality: usage of tf.compat.v1 and experimental APIs

---

.github/workflows/release.yml

Since the runner is always ubuntu this only pulled down linux wheels. Likely the cause of the 502 errors from pypi.
https://test.pypi.org/manage/project/tensorflow-addons/release/0.9.0.dev2/
vs
https://test.pypi.org/manage/project/tensorflow-addons/release/0.9.0.dev0/

Select correct OS for python wheel uploads

---

tensorflow_addons/optimizers/cyclical_learning_rate.py
tensorflow_addons/optimizers/tests/cyclical_learning_rate_test.py

The gamma parameter was not saved. Causing the new object to behave differently from the original.

Fixed serialization and test for a learning rate scheduler.

---

tools/testing/source_code_test.py

This was fixed by @autoih in a recent commit.

Remove cell_test.py from the blacklist of tf.compat.v1.

---

tensorflow_addons/conftest.py
tensorflow_addons/rnn/tests/cell_test.py
tensorflow_addons/utils/test_utils.py
tensorflow_addons/utils/tests/test_utils_test.py

Depending on the orders of the tests, this one could or could not pass. Notably, 
```
pytest -v ./tensorflow_addons/rnn/tests/cell_test.py::test_config_nas
```
is enough to reproduce it because names of keras objects depends on which objects have already been created in the global context.

Fixing the flaky cell test.

---

tensorflow_addons/callbacks/tests/tqdm_progress_bar_test.py
tensorflow_addons/callbacks/tqdm_progress_bar.py

fixes #1620 .  
Although, I couldn't figure out the use of `batch` parameter in `on_test_batch_begin` method.
@zaccharieramzi and @gabrieldemarmiesse , please review and suggest changes.

Added TQDM Progressbar for evaluate()

---

tensorflow_addons/seq2seq/tests/basic_decoder_test.py

cc @gabrieldemarmiesse. Dividing into several parts since it's large, and not sure if removing `use_gpu` is a good idea. The reason is using gpu seems not helping a lot in LSTM, only if it's self-attention(transformer) based. May need your suggestions.

Moved run_all_in_graph_and_eager_mode in basic decoder

---

tools/run_gpu_tests.sh
tools/testing/build_and_run_tests.sh

Currently, our tests are not running with gpu in kokoro. There seems to have multiple reasons:
* `--runtime=nvidia` doesn't work anymore for some reason. Meaning that `nvidia-smi` doesn't work in the container. The fix is to use `--gpus=all`. This is the fix here.
* There is an issue when opening the cuda lib. That's not fixed yet. But it seems strange since the compilation of CUDA files works. See the kokoro log.
```
+ python -c 'import tensorflow as tf; print(tf.config.list_physical_devices())'
2020-04-15 10:42:28.368032: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-04-15 10:42:28.369637: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6 …
```

Partially fix for gpus in kokoro

---

docs/tutorials/tqdm_progress_bar.ipynb

Added demo as per [#1649 (comment)](https://github.com/tensorflow/addons/pull/1649#pullrequestreview-391989472).  
@shun-lin, @gabrieldemarmiesse  - Please review.

Added demo of TQDMProgressBar() for evaluate()

---

tools/docker/build_wheel.Dockerfile

See #1655
We cleaned the cache to make sure that the options for building the wheels were taken into account, but one could argue that it's bazel's job to invalidate the cache, not ours, so we can let bazel decide what to do.
When building the wheel, we went from 5m to 1s.

Remove the cleaning of the cache to speed up the build.

---

tensorflow_addons/rnn/tests/cell_test.py
tools/testing/build_and_run_tests.sh

Later on, we'll have a smart distribution of gpus among the workers, but we're not there yet.
See #1655
Before: 5m10s, after 2m7s (on the linux build).
EDIT: Since the order of the tests is not deterministic, I had to make sure to fix the name of a layer in a test.

Enable pytest-xdist when nvidia-smi is not found.

---

tensorflow_addons/seq2seq/tests/basic_decoder_test.py

Fix two testing functions and move out tf.test

---

build_deps/toolchains/gpu/crosstool/BUILD.tpl

Build fails on ppc64le, with this minor change build is successful. Tested with following environment variables:
```
export TF_NEED_CUDA="1"
export TF_CUDA_VERSION="10.2"
export TF_CUDNN_VERSION="7"
export CUDA_TOOLKIT_PATH="/usr/local/cuda"
export CUDNN_INSTALL_PATH="/usr/lib/powerpc64le-linux-gnu"
```

Enable ppc64le build

---

tensorflow_addons/activations/tests/sparsemax_test.py

Removed run_all_in_graph_and_eager_mode in sparsemax.

---

tensorflow_addons/utils/test_utils.py

Just port something from TF. TF extends bfloat dtype for numpy. So we can also check it for `assert_allclose_according_to_type`
https://colab.research.google.com/drive/1BbGWrbM_q02LykGoDTcW9YR93DXTgNug
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/test_util.py#L2562

support bfloat16 for assert_allclose_according_to_type

---

tensorflow_addons/losses/lifted.py
tensorflow_addons/losses/tests/lifted_test.py
tensorflow_addons/losses/tests/triplet_test.py
tensorflow_addons/losses/triplet.py

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow version and how it was installed (source or binary): 2.2.0-r3
- TensorFlow-Addons version and how it was installed (source or binary): 0.10.0-dev
- Python version: 3.6
- Is GPU used? (yes/no): yes
**Describe the bug**
When I build a model with mixed precision the input to TripletSemiHardLoss, TripletHardLoss and LiftedStructLoss should accept: float32, float16 or bfloat16.
float32 works fine, but float16 and bfloat16 are not supported by these losses.
**Code to reproduce the issue**
https://colab.research.google.com/drive/1BvOBlBcWnzvKKM5vp8RhYTOK-KMeygWy
```
loss = tfa.losses.triplet_hard_loss(labels, logits)
/usr/local/lib/python3.6/dist-packages/tensorflow_addons/losses/triplet.py:174 …
```

Added float16 and bfloat16 support for TripletSemiHardLoss, TripletHardLoss and LiftedStructLoss

---

tensorflow_addons/optimizers/tests/lazy_adam_test.py

The apply_gradients actually happen in the "self.evaluate" call.
Another tricky thing: `get_beta_accumulators` has to be called every time in the loop because those are eager tensors now (immutable) and as such, should be recomputed.
There was a strange error on gpu with float16. I enforced the execution on CPU to fix it.

Moved one test function out of "run_deprecated_v1"

---

tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops.cc

For gcc >= 8.0 (our docker uses 8.3), using `memset` to clearing non-trivial object will throw the following warning.
To silence it, we can explicitly cast the first argument with type (T*) to (void*).

Silence memset warning

---

tensorflow_addons/losses/tests/metric_test.py

Failing build for py38 since these do not have the same tolerance as tf.test.assertAllClose

Match tf.test assertion tolerance

---

.github/workflows/release.yml
tools/docker/build_wheel.Dockerfile

For some reason the python3.8 build installs the pytest.txt prior to tensorflow:
https://github.com/tensorflow/addons/runs/598441627
This caused issue since numpy was not available for scikit-image installation. I couldn't find documentation about why this order would be changed.
This is a more explicit order regardless.
Marking WIP -- confirming locally since CI won't test this until it merges

Fix Ubuntu py38 build

---

tools/install_deps/pytest.txt
tools/testing/build_and_run_tests.sh

Should be enough to ensure the duration of the tests doesn't blow up out of nowhere.
Closes #1316
Current output:
```
========================== slowest modules durations ===========================
49.85s tensorflow_addons/seq2seq/tests/attention_wrapper_test.py
24.94s tensorflow_addons/layers/tests/normalizations_test.py
17.38s tensorflow_addons/image/tests/filters_test.py
14.21s tensorflow_addons/optimizers/tests/lookahead_test.py
14.14s tensorflow_addons/optimizers/tests/rectified_adam_test.py
======================= slowest test functions durations =======================
11.66s tensorflow_addons/layers/tests/optical_flow_test.py::test_gradients
10.53s tensorflow_addons/optimizers/tests/cyclical_learning_rate_test.py::test_exponential_cyclical_learning_rate
7.97s …
```

Added pytest-extra-durations to monitor the speed of the tests.

---

tensorflow_addons/optimizers/cyclical_learning_rate.py
tensorflow_addons/optimizers/tests/cyclical_learning_rate_test.py

Fixes #1203 .  
**What was causing the errors?**  
- The derived classes of `CyclicLearningRate` doesn't have attribute `scale_fn` which was returned by mistake in `get_config()` through `**super().get_config()`.  
- The tests were poorly written and that's why y_true and y_pred were calculated from two different functions. That's why it was failing.
I have resolved all the errors related to it. Also added one more test which was overlooked in previous implementation.  
@gabrieldemarmiesse and @seanpmorgan - Please review it.

Fixed CyclicLearningRate and its tests' errors

---

.github/workflows/release.yml
CONTRIBUTING.md
README.md
tensorflow_addons/utils/ensure_tf_install.py
tensorflow_addons/utils/resource_loader.py
tools/docker/cpu_tests.Dockerfile
tools/install_deps/tensorflow-cpu.txt
tools/install_deps/tensorflow.txt
tools/run_gpu_tests.sh

Drop support for TF 2.1

---

tensorflow_addons/callbacks/tests/tqdm_progress_bar_test.py

No longer needed now that 2.1 isn't supported on master

Clean up some unnecessary TQDM Documentation

---

tensorflow_addons/losses/npairs.py
tensorflow_addons/losses/tests/npairs_test.py

Fixes https://github.com/tensorflow/addons/issues/838
IIRC this should be fixed on TF2.2

Enable npairs loss on windows

---

tensorflow_addons/optimizers/weight_decay_optimizers.py

The new argument was actually `experimental_aggregate_gradients`
Reference: https://github.com/tensorflow/models/commit/9fc4fd082968c0c959c1d7bc938a9fcbf0f9e50d

DOC: Correct example of new experimental argument

---

tensorflow_addons/seq2seq/sampler.py

To change the `sampling_probability` during training, the simplest option is to make it a `tf.Variable` (alternatively, it could be a placeholder). However, the current constructors of the scheduled samplers call `tf.convert_to_tensor(sampling_probability)`, which converts variables into static tensors. This forces the user to write:
```python
sampler = tfa.seq2seq.sampler.ScheduledEmbeddingTrainingSampler(
sampling_probability=0.,
embedding_fn=decoder_embedding_layer)
sampler.sampling_probability = tf.Variable(0.)
```
This is not too hard, but it's not immediately obvious (and the documentation does not cover this), and it really feels like a hack. It would be more natural to just keep the `sampling_probability` as a variable in the constructor, so we could just write:
``` …
```

In scheduled samplers, don't convert sampling_probability if it's a tf.Variable

---

tensorflow_addons/seq2seq/sampler.py

Format code in python code block, add missing `sample_ids` in the call to `next_inputs(...)`, call `cell(...)` instead of `cell.call(...)` so the cell gets built if necessary (this makes it easier to take the code example and actually try it out), for example:
```python
import tensorflow_addons as tfa
import tensorflow as tf
from tensorflow import keras
input_tensors = tf.constant([[[1., 2.], [4., 3.], [6., 5.]],
[[7., 8.], [10., 9.], [11., 12.]]])
sampler = tfa.seq2seq.TrainingSampler()
(initial_finished, initial_inputs) = sampler.initialize(input_tensors)
cell = keras.layers.LSTMCell(4)
cell_input = initial_inputs
cell_state = cell.get_initial_state(batch_size=len(input_tensors),
dtype=input_tensors.dtype)
max_output_length = input_tensors.shape[1]
for time_step in …
```

Clarify the documentation of the Sampler class

---

.github/workflows/make_wheel_macOS.sh
.github/workflows/release.yml
tools/docker/build_wheel.Dockerfile
tools/install_deps/bazel_macos.sh
tools/install_so_files.sh

No need to upgrade these two packages in our build environment.. this can introduce possible errors we don't control

Fix master: Keep pip version constant

---

tools/docker/build_wheel.Dockerfile

Py3.7 in the Ubuntu container needs pip to be upgraded:
https://github.com/tensorflow/addons/runs/635031760?check_suite_focus=true
We got breaks for 20.1 and it's probably best to make our build env as static as possible

Pin pip version for ubuntu build env

---

.github/workflows/ci_test.yml

We don't need to test in editable mode because the main tests are already done in editable mode. We don't need to test linux 2.2.0 in a separate build because our main tests already run with 2.2.0.

Remove some useless builds.

---

tensorflow_addons/losses/metric_learning.py
tensorflow_addons/losses/tests/triplet_test.py
tensorflow_addons/losses/triplet.py

Added an option to base pairwise distances on cosine similarity in addition to euclidean distance as suggested by several papers.
Formula for distance taken from  [Metric Learning for Adversarial Robustness](https://arxiv.org/pdf/1909.00900.pdf)

Added angular distance option to triplet loss

---

.github/workflows/backport.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml

For unauthenticated github action creators, I would be more comfortable pinning our use to commit SHA.  Not a whole lot can go wrong here, GITHUB_TOKENS expire in an hour and don't have much access, but better safe than sorry.

Use commit SHA for unverified actions

---

tensorflow_addons/conftest.py
tensorflow_addons/utils/test_utils.py

In the pytest reports, having `dtype0`, `True`, `False` as test parameters isn't helpful for debugging. There is a pytest hook to make custom names.
```
tensorflow_addons/activations/tests/gelu_test.py::test_same_as_py_func[cpu-True-float32] PASSED                                                                                                                                        [ 19%]
tensorflow_addons/activations/tests/gelu_test.py::test_same_as_py_func[cpu-True-float64] PASSED                                                                                                                                        [ 20%]
tensorflow_addons/activations/tests/gelu_test.py::test_same_as_py_func[cpu-False-float32] PASSED …
```

Better names for parametrize.

---

.github/workflows/release.yml
tools/docker/build_wheel.Dockerfile

Since we had many issues with specific versions of python lately and the build matrix is not too big, let's enable all builds.

Fix master and enable all builds.

---

tensorflow_addons/image/filters.py
tensorflow_addons/image/tests/filters_test.py

- Support different sigma for x and y direction.
- Minor docs.
- Depthwise conv2d on floating type and retain the original dtype if it is not floating type.
- Simplify tests, including 2d, 3d and 4d image, three different padding modes and different dtype.
- The radius of gaussian kernel is computed as `ceil(sigma * truncate) * 2 + 1`. So for sigma=1.0, truncate=4.0, the kernel size should be 9 instead 3, which is the value we used before.
https://github.com/scipy/scipy/blob/v1.4.1/scipy/ndimage/filters.py#L216
- Use `scipy.ndimage.filters.gaussian_filter` instead of the one in `skimage` to test 4D image directly.

Make gaussian filter meet scipy's implementation

---

tensorflow_addons/seq2seq/decoder.py
tensorflow_addons/seq2seq/tests/decoder_test.py

Also add `@typechecked` to `dynamic_decode` for consistency.
Fixes #1749.

Accept passing maximum_iterations as a Tensor

---

.github/workflows/make_wheel_Windows.sh
.github/workflows/make_wheel_macOS.sh
.github/workflows/release.yml
tools/docker/build_wheel.Dockerfile
tools/install_deps/bazel_macos.sh

Combines changes from #1760 and #1762 
* Use Github token for Bazel API requests
* Pin pip to 19.0 during release
* Test against 2.2.0 stable (still build against 2.1.0 though)
Unblocks #1810

Update 0.9 branch release streategy

---

CONTRIBUTING.md
tensorflow_addons/conftest.py
tensorflow_addons/optimizers/tests/conditional_gradient_test.py
tensorflow_addons/utils/test_utils.py

Made conditional_gradient_test.py use the pytest mark as it's more clean.
I also had to expose a way to grab the device used to run the test function. This can now be done by adding a parameter `device` to the test function. I adapted the CONTRIBUTING to reflect that.

Use the mark for the gpu tests in conditional_gradient_test.py

---

tensorflow_addons/utils/tests/keras_utils_test.py

Hi,
There was a missing test for a method in tensorflow_addons/utils/keras_utils.py so here it is.

added test for normalize_data_format in keras_utils

---

tensorflow_addons/image/color_ops.py

Try to fix https://github.com/tensorflow/addons/issues/1829

Fix condition tracing in scale_channel

---

tensorflow_addons/image/color_ops.py

`tf.nn.depthwise_conv2d` can work on 4D image directly so we do not need to use `tf.map_fn` to operate image-by-image. Achieve about 1.5X speed on large batch of images.
https://colab.research.google.com/drive/1yqqBp6-aXXgUbmN-c-DMOl0RgSaRYX4j?usp=sharing

Speedup sharpness

---

tensorflow_addons/image/dense_image_warp.py
tensorflow_addons/image/distort_image_ops.py
tensorflow_addons/image/resampler_ops.py
tensorflow_addons/image/sparse_image_warp.py

- [tfa.image.random_hsv_in_yiq](https://www.tensorflow.org/addons/api_docs/python/tfa/image/random_hsv_in_yiq): "space" is in the next line.
- [tfa.image.resampler](https://www.tensorflow.org/addons/api_docs/python/tfa/image/resampler): miss an empty line so the doc is not rendered correctly.
- [tfa.image.sparse_image_warp](https://www.tensorflow.org/addons/api_docs/python/tfa/image/sparse_image_warp): change `tf.contrib` to `tfa`.
- [tfa.image.dense_image_warp](https://www.tensorflow.org/addons/api_docs/python/tfa/image/dense_image_warp): use `` to improve the readability.

Fix ill-formatted doc in image

---

.github/CODEOWNERS

`metrics` is currently without any owners.
cc @tensorflow/sig-addons-maintainers

Remove squadrick from subpackage CODEOWNERS

---

README.md

This PR contains a few fixes and harmonizes some names and section titles. For example:
* TF Addons, TF-Addons, TFA, etc. -> TensorFlow Addons
* TF -> TensorFlow
* MacOS -> macOS
* PyPi -> PyPI
* custom-ops -> custom ops
Let me know what you think.

README fixes and consistency improvements

---

.github/workflows/ci_test.yml
.github/workflows/make_wheel_Windows.sh
.github/workflows/make_wheel_macOS.sh
.github/workflows/release.yml
tools/docker/build_wheel.Dockerfile
tools/docker/cpu_tests.Dockerfile
tools/docker/sanity_check.Dockerfile

It seems that just about every PR we have fails once or twice due to "connection reset by peer" while pip installing TF. Certainly related to GitHub action CI, but a possible fix may be to increase the default timeout as suggested here:
https://github.com/pypa/pypi-support/issues/175#issuecomment-578834580

Increase default pip timeout to improve CI reliability

---

.github/CODEOWNERS
tensorflow_addons/rnn/__init__.py
tensorflow_addons/rnn/cell.py
tensorflow_addons/rnn/tests/cell_test.py

Part of https://github.com/tensorflow/addons/pull/1809
I have been working with recurrent neural networks. I needed an implementation of Echo State Networks (ESN) for tensorflow. I found some implementations, but none of them was compatible with tensorflow2, so I implemented it. I think it would be great to add ESN to tensorflow_addons so everybody can use it. 
This pull request add the recurrent ESNCell.
> "Echo state networks (ESN) provide an architecture and supervised learning principle for recurrent neural networks (RNNs). The main idea is (i) to drive a random, large, fixed recurrent neural network with the input signal, thereby inducing in each neuron within this "reservoir" network a nonlinear response signal, and (ii) combine a desired output signal by a trainable linear …

Added echo state network (ESN) recurrent cell

---

tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops.cc
tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops_gpu.cu.cc

Actually, I don't know how we passed tests previously...
We don't register half and double backward kernel, and even don't specialize half forward kernel. But we indeed test them.
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/tests/resampler_ops_test.py#L95-L124
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/tests/resampler_ops_test.py#L185-L213
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/gpu_device_functions.h#L670-L691

Enable half and double for resampler GPU ops

---

tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/seq2seq/tests/attention_wrapper_test.py

Some RNN cells such as `GRUCell` and `SimpleRNNCell` do not return the same state structure in `get_initial_state` and in the `call` method.
This PR ensures that the returned state structure always matches the initial structure.
Fixes #1856.

Ensure cell state structure is unchanged on first AttentionWrapper call

---

tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/seq2seq/basic_decoder.py
tensorflow_addons/seq2seq/beam_search_decoder.py
tensorflow_addons/seq2seq/sampler.py

We can rely on `@typechecked` to run the checks for us.
This PR also fixes some type annotations that did not match the implementation, especially regarding callables.

Remove manual type checks and fix some annotations

---

tensorflow_addons/custom_ops/layers/cc/kernels/correlation_cost_op_gpu.cu.cc

- use `ldg` to read data
- add `__restrict__` qualifier to pointer

Enable some compiler optimalization tricks for correlation cost GPU ops

---

tensorflow_addons/seq2seq/loss.py

We now target TensorFlow >= 2.2 so we can remove this workaround.

Remove workaround for TensorFlow < 2.2

---

tensorflow_addons/seq2seq/basic_decoder.py
tensorflow_addons/seq2seq/beam_search_decoder.py

Also remove some `TypeError` notices that are redundant with the type annotations.

Clarify cell argument docstring in decoder objects

---

tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/seq2seq/beam_search_decoder.py
tensorflow_addons/seq2seq/decoder.py
tensorflow_addons/seq2seq/loss.py
tensorflow_addons/seq2seq/sampler.py
tensorflow_addons/seq2seq/tests/attention_wrapper_test.py
tensorflow_addons/seq2seq/tests/basic_decoder_test.py
tensorflow_addons/seq2seq/tests/beam_search_decoder_test.py
tensorflow_addons/seq2seq/tests/decoder_test.py

* Prefer `shape` attribute over `get_shape` method
* Remove usage of `tf.compat.dimension_value` (we only support TF 2)
* Remove usage of deprecated attribute `TensorShape.dims`

Update shape usage to TensorFlow 2 style

---

tensorflow_addons/layers/multihead_attention.py

Docs on the site look weird due to formatting issues: https://www.tensorflow.org/addons/api_docs/python/tfa/layers/MultiHeadAttention
This PR tries to fix the formatting and also improves parts of the text a bit.

Fix MultiHeadAttention docs

---

.github/CODEOWNERS
tensorflow_addons/layers/BUILD
tensorflow_addons/layers/__init__.py
tensorflow_addons/layers/esn.py
tensorflow_addons/layers/tests/esn_test.py

Part of https://github.com/tensorflow/addons/pull/1809.
After adding the ESN recurrent cell https://github.com/tensorflow/addons/pull/1811, here it is the ESN layer.

Add Echo State Network (ESN) layer

---

tensorflow_addons/layers/multihead_attention.py

at present this check is done only if mask is not None whereas this should be checked irrespective of the msk

fix - in multhead_attention, correct the location where key & value shapes are checked

---

CONTRIBUTING.md
tensorflow_addons/conftest.py
tensorflow_addons/layers/tests/multihead_attention_test.py
tensorflow_addons/optimizers/tests/conditional_gradient_test.py
tensorflow_addons/optimizers/tests/lamb_test.py
tensorflow_addons/optimizers/tests/weight_decay_optimizers_test.py
tensorflow_addons/optimizers/tests/yogi_test.py
tensorflow_addons/utils/test_utils.py
tensorflow_addons/utils/tests/test_utils_test.py

Needs #1767 to be merged first this will make the diff smaller.
Closes #1682 
tf.test.is_gpu_available() is deprecated and was causing issues so I replaced it.
Maybe we should replace the name `device` for the fixture? Maybe it's strange that there is a device being a strategy.
I think we'll rename `with_device` -> `with_scope` and `device` -> `scope`. But the renaming would make a big diff, so it's a TODO for a next pull request.

Enable distributed strategies in tests.

---

tensorflow_addons/image/transform_ops.py

Fix #1779.
cc @WindQAQ 
Related https://github.com/google/automl/issues/480

use raw ops

---

tensorflow_addons/metrics/cohens_kappa.py

Fix typo in docstring of CohenKappa __init__

---

.github/workflows/notify_codeowners.py
tools/testing/source_code_test.py

A number of things going on here. To start these were never really blacklists, but rather should have been denoted as whitelists. The changes are not end-user facing / code breaking and they can be replaced with more informative variable names.
It also aligns with chromium guidelines as well as a number of OSS community changes:
https://chromium.googlesource.com/chromium/src/+/master/styleguide/inclusive_code.md#racially-neutral

Use informative list names

---

tensorflow_addons/optimizers/moving_average.py
tensorflow_addons/optimizers/tests/moving_average_test.py

Adds two new features to MovingAverage:
1.  Dynamic decay: This helps the early accuracy of MovingAverage by starting the decay at 0.1 and gradually increasing it to average_decay.
2.  Swap weights: This makes it easier to temporarily swap the model weights and the average weights during eval.

MovingAverage: add dynamic decay and swap weights

---

tensorflow_addons/seq2seq/BUILD
tensorflow_addons/seq2seq/beam_search_decoder.py
tensorflow_addons/seq2seq/tests/beam_search_decoder_test.py
tensorflow_addons/seq2seq/tests/beam_search_ops_test.py

This PR adds a pure Python TensorFlow implementation of `tfa.seq2seq.gather_tree`, which can be enabled with the global flag [`TF_ADDONS_PY_OP`](https://github.com/tensorflow/addons#gpu-and-cpu-custom-ops-1). This is useful when Addons custom ops are not readily available (e.g. TensorFlow Serving).
I tested the performance on a real world application: beam search decoding of a neural machine translation model. I'm using a [custom beam search implementation](https://github.com/OpenNMT/OpenNMT-tf/blob/master/opennmt/utils/decoding.py) but it is close to the `BeamSearchDecoder` included in Addons.
I did not find significant performance impact.  And I think this makes sense: the function is only used at the very end of the decoding and does not involve very complex ops.

Add a Python alternative to seq2seq.gather_tree

---

tensorflow_addons/text/crf.py
tensorflow_addons/text/tests/crf_test.py

This PR fixes #1934 by adding `get_config` and `from_config` methods to `CrfDecodeForwardRnnCell`.
A test case that fails before the implementation and passes afterwards is also added. The test uses an example similar to the issue. However, I'm unsure if instead it would make more sense to create a simpler test that instantiates the object and then reconstruct it from the methods.

Crf decode cell serialize functions

---

tensorflow_addons/layers/multihead_attention.py

Changes `heads=128` to `heads=12` in the example which is more realistic.

Fix numerical typo in the examples

---

tensorflow_addons/losses/contrastive.py

This PR should close the issue #1957.

Fixes up a typo in ContrastiveLoss `name` identifier.

---

.github/CODEOWNERS
tensorflow_addons/activations/__init__.py
tensorflow_addons/activations/snake.py
tensorflow_addons/activations/tests/activations_test.py
tensorflow_addons/activations/tests/snake_test.py
tensorflow_addons/layers/__init__.py
tensorflow_addons/layers/snake.py
tensorflow_addons/layers/tests/snake_test.py

Snake layer and activation to learn periodic functions

---

tensorflow_addons/optimizers/novograd.py
tensorflow_addons/optimizers/tests/novograd_test.py

Fixes #1087.
- Gathering indices is done in `resource_sparse_apply_keras_momentum`.
- Sparse weight decay isn't correct: only need to apply on the sparse `grad`, so have to use `tf.gather` to extract `indices` of `var`.
- Original tests aren't robust: though it does call `_resource_apply_sparse`, but the test cases are dense.

Fix sparse novograd

---

tensorflow_addons/seq2seq/tests/basic_decoder_test.py

This was used for V1 session.run.

Remove unnecessary eval_result container in tests

---

tensorflow_addons/losses/tests/triplet_test.py
tensorflow_addons/losses/triplet.py

I had a hard time figuring out why my siamese model was not being able to converge, i.e., it was always converging to the pre-defined margin. After a while, I found out that the nomenclature used along the triplet losses (`L1` and `L2`) might be wrong according to their mathematical formulation.
Let's start with the package `losses/metric_learning` and function `pairwise_distance()`:
- At L34, the euclidean distances between all samples are calculated;
- According to the euclidean distance definition, it is initially calculated by summing up the square of the difference between every dimension;
- From L47 to L53, it is optionally possible to reduce the distance with a square root. Hence, we have the square root of the previously calculated distance, thus creating the L2-distance.
- On the …

Fixes up nomenclature on L1 and L2 norms in triplet losses.

---

tensorflow_addons/optimizers/rectified_adam.py
tensorflow_addons/optimizers/tests/rectified_adam_test.py

RAdam implements weight decay based on AdamW, and the latter supports scheduling for both learning rate and weight decays.
This patch extends existing support of Keras schedulers for the learning rate to weight decay, matching the weight decay features of AdamW.
fixes https://github.com/tensorflow/addons/issues/1908

Add support for scheduled weight decays in RectifiedAdam.

---

tensorflow_addons/image/color_ops.py
tensorflow_addons/image/cutout_ops.py
tensorflow_addons/image/tests/color_ops_test.py
tensorflow_addons/image/tests/cutout_ops_test.py

Closes #1825. Should we have some warning on deprecated arguments?

Drop data_format argument

---

tensorflow_addons/conftest.py
tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/seq2seq/sampler.py
tensorflow_addons/seq2seq/tests/attention_wrapper_test.py
tensorflow_addons/seq2seq/tests/decoder_test.py
tensorflow_addons/utils/test_utils.py

The layers should not set a dtype, unless explicitly passed by the user.
Fixes #1968.

Improve support of global dtype policy in seq2seq layers

---

.github/CODEOWNERS
tensorflow_addons/optimizers/__init__.py
tensorflow_addons/optimizers/proximal_adagrad.py
tensorflow_addons/optimizers/tests/proximal_adagrad_test.py

Closes https://github.com/tensorflow/addons/issues/591.

Port ProximalAdagrad

---

tensorflow_addons/losses/focal_loss.py
tensorflow_addons/losses/giou_loss.py

Currently [documentation](https://www.tensorflow.org/addons/api_docs/python/tfa/losses#functions) looks slightly broken, for some losses
Not a big fan of repeating docs in two places, but it looks like a consistent behaviour we do in other places as well.
Also, not sure if it also makes sense to adjust usage examples and bring to the added docs

Duplicate descriptions also to functions

---

tools/docker/build_wheel.Dockerfile

Build broke yesterday because `setuptools` does not present in dist-packages of python3.5 on linux. Try to investigate and fix it :-(
https://github.com/tensorflow/addons/pull/1994/checks?check_run_id=867618216

Install setuptools first

---

tensorflow_addons/optimizers/average_wrapper.py
tensorflow_addons/optimizers/conditional_gradient.py
tensorflow_addons/optimizers/lamb.py
tensorflow_addons/optimizers/moving_average.py

- Use `.assign` instead of raw ops.
- Apply `use_locking` when doing assignment
- Remove trivial `.op`
Cause they are all related to `.assign`, I put them into one PR.

Clean up .assign in optmizers

---

tensorflow_addons/seq2seq/README.md

There were several issues:
* missing encoder masking
* missing training flag
* `encoder_state` passed as memory instead of `encoder_outputs`
This commit also improves variables name consistency and include attention in the first example to have one complete training usage.
Related to #1995.

Fix decoder with attention example in the README

---

tensorflow_addons/losses/kappa_loss.py
tensorflow_addons/losses/tests/kappa_loss_test.py

Fixes #2006.
There is no way to serialize `tf.dtypes.DType` and in `tf.keras.losses.*`, the computation dtype depends on either input (`y_true`, `y_pred`) or `tf.keras.backend.floatx()`. It terms out the most reasonable way for me is to cast values to `tf.keras.backend.floatx()` for computation because it involves something like log and div.
https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/keras/losses.py

Use tf.keras.backend.epsilon() as dtype

---

build_deps/toolchains/gpu/cuda_configure.bzl
tensorflow_addons/register.py

Getting an error message, I've noticed that two words were joined because a space had been forgotten in the message composed of continued multi-line strings.
I've added it, looked around for similar issues and found two more. (I don't vouch to have found all, tho'.)
Furthermore, it seems that multi-line messages are assembled incoherently within the project, sometimes spaces are at the end of lines to be continued, sometimes at the beginnings, furthermore sometimes `\n` stands alone, sometimes with a preceding space. I would suggest to have a standardization to follow here. (My suggestion would be space at the end of an individual line, and no spaces preceding `\n`).

TYPO: Add missing spaces in some multi-line messages

---

tensorflow_addons/metrics/r_square.py
tensorflow_addons/metrics/tests/r_square_test.py

The `R_Square` metric was broken when calling `model.evaluate` or `model.fit` with `validation_data` set. This was due to a tensor shape mismatch.
*  I added to `metrics/test/r_square_test.py`:
```python
def test_keras_fit():
model = tf.keras.Sequential([tf.keras.layers.Dense(1)])
model.compile(loss="mse", metrics=[RSquare(y_shape=(1,))])
data = tf.data.Dataset.from_tensor_slices(
(tf.random.normal(shape=(100, 1)), tf.random.normal(shape=(100, 1)))
)
data = data.batch(10)
model.fit(x=data)
model.fit(x=data, validation_data=data)
```

fix R_Square shape issue in model.evaluate

---

tensorflow_addons/optimizers/tests/weight_decay_optimizers_test.py
tensorflow_addons/optimizers/weight_decay_optimizers.py

Fixes #2049 
*  
I added new unit tests, and also tested the fixes it in a collab environment (see linked gist in original issue)

Fixed lr/wd schedules for DecoupledWeightDecayExtension running on GPU

---

tensorflow_addons/image/transform_ops.py

Fixes #2054.
I tested this on Google Colab environment. Well here's the result :
```
angles_to_projective_transforms     0065868
angles_to_projective_transforms2    0069990
angles_to_projective_transforms_tf  0257738
angles_to_projective_transforms2_tf 0260291
angles_to_projective_transforms     0065672
angles_to_projective_transforms2    0069954
angles_to_projective_transforms_tf  0261689
angles_to_projective_transforms2_tf 0254197
angles_to_projective_transforms     0066451
angles_to_projective_transforms2    0070442
angles_to_projective_transforms_tf  0264665
angles_to_projective_transforms2_tf 0262863
angles_to_projective_transforms     0071835
angles_to_projective_transforms2    0076597
angles_to_projective_transforms_tf  0294059 …
```

Small optimization for tfa.image.transform_ops.angles_to_projective_transforms

---

tensorflow_addons/seq2seq/decoder.py
tensorflow_addons/seq2seq/tests/decoder_test.py

This PR adds some logics to make `dynamic_decoder()` TFLite-convertible.
Hi. I am Jae from TensorFlow Lite team.
Because TFLite doesn't support dynamic shape of `TensorArray` yet, it changes the `TensorArray`'s into static shape.
Also, 2-D `TensorArray` is not supported, so some reshaping at the input & output tensors is required.
Because TFLite assumes `batch_size = 1` at the inference, we can simply implement the above.
Thank you.

Make `dynamic_decode()` TFLite-convertible

---

tensorflow_addons/activations/gelu.py
tensorflow_addons/layers/gelu.py

https://github.com/tensorflow/tensorflow/pull/41178 got merged today (7/27). I suppose it won't appear in TensorFlow 2.3.* unless it's cherry-picked by someone.
@seanpmorgan Can we do that or ask someone to do that or just wait for next release? Thank you.
Fixes #2005.
*  Just add deprecation warnings

Deprecate gelu

---

.github/CODEOWNERS
tensorflow_addons/layers/__init__.py
tensorflow_addons/layers/spectral_normalization.py
tensorflow_addons/layers/tests/spectral_normalization_test.py
tensorflow_addons/layers/wrappers.py

Continues the work of this abandoned PR https://github.com/tensorflow/addons/pull/376 which implements SpectralNormalization layer [1].
Changes:
* Fix `call` method for handling training and inference
* Added support for wrapping an embedding layer, since in [2] they used spectral normalization to the conditional embedding.
* Minor changes in raise error types and doc strings
Still to be done:
It would be great to get some feedback to finally finish this layer
[1] Miyato, T., Kataoka, T., Koyama, M., & Yoshida, Y. (2018). Spectral normalization for generative adversarial networks. arXiv preprint arXiv:1802.05957.
[2] Han Zhang, Ian Goodfellow, Dimitris Metaxas, Augustus Odena (2018). Self-Attention Generative Adversarial Networks. arXiv preprint arXiv:1805.08318

Spectral Normalization continued

---

tensorflow_addons/conftest.py
tensorflow_addons/layers/wrappers.py
tensorflow_addons/losses/focal_loss.py
tensorflow_addons/losses/giou_loss.py
tensorflow_addons/losses/quantiles.py
tensorflow_addons/metrics/cohens_kappa.py
tensorflow_addons/metrics/matthews_correlation_coefficient.py
tensorflow_addons/metrics/multilabel_confusion_matrix.py
tensorflow_addons/metrics/r_square.py
tensorflow_addons/optimizers/lookahead.py
tensorflow_addons/optimizers/moving_average.py
tensorflow_addons/optimizers/weight_decay_optimizers.py
tools/docker/sanity_check.Dockerfile

Reverts tensorflow/addons#677. I thought it was complete and merged it in a rush. Let's revert it. I'll open a new one to enable doctest on CI.

Revert "doctest addons"

---

tensorflow_addons/seq2seq/beam_search_decoder.py
tensorflow_addons/seq2seq/tests/beam_search_decoder_test.py

The purpose of this PR is expose the scores for all token IDs, not only the ones that are selected as `predicted_ids`. In doing so, we enable the user of the `BeamSearchDecoder` to directly access the logits as requested in #1915.
This PR also fixes documentation from #1916 that described the `scores` property as having the shape of `all_scores`. Based on the existing unit tests, it looks as though the intent is for `scores` to have the shape `[batch_size, beam_width]`, not `[batch_size, beam_width, vocab_size]`, which is what is now exposed through `all_scores`.
Unit tests have been added to verify that the new property has the correct shape.

Added all_scores property to BeamSearchDecoderOutput to expose scores for all tokens

---

tensorflow_addons/optimizers/novograd.py

This PR fixes stylistic issues in the [NovoGrad optimizer documentation page](https://www.tensorflow.org/addons/api_docs/python/tfa/optimizers/NovoGrad).
Fixes #2085
*

 Fix broken link in NovoGrad docstring

---

docs/tutorials/average_optimizers_callback.ipynb
docs/tutorials/networks_seq2seq_nmt.ipynb

Add missing installs and fix imports in `networks_seq2seq_nmt.ipynb` 
Remove layer names from `average_optimizers_callback.ipynb` these were crashing the notebook for some reason.

Fix imports and layer naming

---

tensorflow_addons/optimizers/moving_average.py
tensorflow_addons/optimizers/tests/moving_average_test.py

Fixes: https://github.com/tensorflow/addons/issues/2113
If you're adding a bugfix or new feature please describe the tests that you ran to verify your changes: By running `python -m pytest tensorflow_addons/optimizers/tests/moving_average_test.py`

fix typing of num_updates in moving_average

---

tensorflow_addons/optimizers/average_wrapper.py
tensorflow_addons/optimizers/lookahead.py

Inner optimizer is not tracked for checkpoint
https://github.com/tensorflow/addons/issues/2094
- [x ] Bug fix
- [X ] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
- [X ] By running Black + Flake8
- [ X] By running pre-commit hooks
Tested in https://github.com/tensorflow/addons/pull/2102
It still need to pass `save` and `load_model` case.

Base optimizer tracking

---

README.md
setup.py
tensorflow_addons/utils/ensure_tf_install.py
tensorflow_addons/version.py

This restores the functionality removed by #974 but makes it optional, so users can get the behavior when installing:
```
pip install tensorflow_addons[tensorflow]
```
Fixes #2111
Install script enhancement.
```
pip install '.[tensorflow]'
```

Added extra requirements for tensorflow, tensorflow-gpu, and tensorflow-cpu

---

docs/tutorials/layers_normalizations.ipynb

I assume this was wrong, right? You probably meant to apply it to the channel axis, which is the last here.

fix LayerNormalization use on the right axis

---

tensorflow_addons/losses/contrastive.py
tensorflow_addons/losses/focal_loss.py
tensorflow_addons/losses/giou_loss.py
tensorflow_addons/losses/kappa_loss.py
tensorflow_addons/losses/npairs.py
tensorflow_addons/losses/quantiles.py

Adding testable docstrings to `losses`.
Fixes #2066
Changes made to:
- `quantiles.py`
- `npairs.py`
- `kappa_loss.py`
- `giou_loss.py`
- `focal_loss.py`
- `contrastive.py`
- Used pylint with TensorFlow's custom style definition

#2066 doctest update losses

---

docs/tutorials/_template.ipynb
docs/tutorials/average_optimizers_callback.ipynb
docs/tutorials/image_ops.ipynb
docs/tutorials/layers_normalizations.ipynb
docs/tutorials/layers_weightnormalization.ipynb
docs/tutorials/losses_triplet.ipynb
docs/tutorials/networks_seq2seq_nmt.ipynb
docs/tutorials/optimizers_conditionalgradient.ipynb
docs/tutorials/optimizers_lazyadam.ipynb
docs/tutorials/time_stopping.ipynb
docs/tutorials/tqdm_progress_bar.ipynb

This formats the tutorial notebooks using the latest [nbfmt](https://github.com/tensorflow/docs/tree/master/tools/tensorflow_docs/tools) to make more consistent by removing extra metadata fields, ensuring certain ones exist, etc. This helps reduce diff churn for better GitHub reviews.
To run:
```
python3 -m pip install -U --user git+https://github.com/tensorflow/docs
python3 -m tensorflow_docs.tools.nbfmt ./docs/
```
Thanks!

nbfmt tutorial notebooks

---

tensorflow_addons/image/tests/transform_ops_test.py
tensorflow_addons/image/transform_ops.py
tensorflow_addons/image/translate_ops.py

Fixes #1318.
Test against different `fill_mode`.

Support fill_mode for transform

---

tensorflow_addons/image/filters.py

Speedup Gaussian kernel generation. It doesn't really matter (cause `depthwise_conv2d` dominate the computation time), but might be helpful for anyone who is looking for standalone gaussian kernel function. Also switch to `softmax` offers numeric stability.
https://colab.research.google.com/drive/1UTA00ZD6Iq4RSgPpWgNBauyNbgTTk8Xj?usp=sharing
Underlying implementation changes.

Speedup gaussian kernel generation

---

tensorflow_addons/layers/normalizations.py
tensorflow_addons/layers/tests/normalizations_test.py

* Previously, to conform to the GroupNorm, the InstanceNorm needs to insert a singleton dim after the channel axis by using reshape ops. These reshape ops might prevent the TF layout optimizer from eliding unnecessary NHWC/NCHW transposes. This PR removes the unnecessary reshape ops for the instance norm. 
If you're adding a bugfix or new feature please describe the tests that you ran to verify your
*  Corresponding changes are made for test_reshape, test_feature_input, test_picture_input to support the shape checking after this PR.
*  The existing test_groupnorm_conv can be used to test the correctness of the change.
cc. @nluehr

Avoid unnecessary reshapes for instance norm

---

tensorflow_addons/rnn/esn_cell.py
tensorflow_addons/rnn/layer_norm_lstm_cell.py
tensorflow_addons/rnn/layer_norm_simple_rnn_cell.py
tensorflow_addons/rnn/nas_cell.py
tensorflow_addons/rnn/peephole_lstm_cell.py

Adding testable docstrings to `rnn`. 
Part of #2066 
Changes made to:
- `esn_cell.py`
- `layer_norm_simple_rnn_cell.py`
- `peephole_lstm_cell.py`
Using pytest

Rnn testable doctests

---

.github/CODEOWNERS
tensorflow_addons/layers/__init__.py
tensorflow_addons/layers/noisy_dense.py
tensorflow_addons/layers/tests/noisy_dense_test.py

This PR adds support for noisy dense layers. Noisy dense layers are like dense layers but random noise is injected to help agents explore in reinforcement learning environments. This is very commonly used in Deep Q Learning and was first introduced by DeepMind in their [Noisy Networks for Exploration](https://arxiv.org/pdf/1706.10295.pdf) paper in 2017.
Fixes: [#2127](https://github.com/tensorflow/addons/issues/2127)
I used PyTest to test the code and trained it on some reinforcement learning environments from the [gym](https://github.com/openai/gym) toolkit and compared my results to the results on the [Noisy Networks for Exploration](https://arxiv.org/pdf/1706.10295.pdf) paper.

Added support for noisy dense layers.

---

.github/CODEOWNERS
tensorflow_addons/layers/__init__.py
tensorflow_addons/layers/stochastic_depth.py
tensorflow_addons/layers/tests/stochastic_depth_test.py

Resolves #2032
* Unit Tests verifying the functionality 
* Unit Test verifying serialization and deserialization

Added stochastic depth layer

---

tensorflow_addons/text/__init__.py
tensorflow_addons/text/crf.py
tensorflow_addons/text/tests/crf_test.py

We can have a common function for creating filtered_inputs used in `crf_multitag_sequence_score`
This function can be reused to modify the input to `crf_decode` to support constrained decoding.
Fixes #607
*  I ran pytest locally to test this PR. All tests passed.

Added filtered_input and constrained_decoding

---

tensorflow_addons/metrics/cohens_kappa.py
tensorflow_addons/metrics/geometric_mean.py
tensorflow_addons/metrics/hamming.py
tensorflow_addons/metrics/matthews_correlation_coefficient.py
tensorflow_addons/metrics/multilabel_confusion_matrix.py
tensorflow_addons/metrics/r_square.py

#2066-doc-update-metrics-latest

---

tensorflow_addons/layers/__init__.py
tensorflow_addons/layers/crf.py

Improving documentation for `layers/crf.py`
Fixes part of #337

updating documentation for CRF

---

tensorflow_addons/optimizers/cyclical_learning_rate.py

I experienced the following stack trace when TF 2.4 nightly passes "step" as an int64. This happens, for example, when using the nightly version of TensorBoard.
Minimal repro: https://pastebin.com/Ni2dgDgh
Environment:
tf-nightly-gpu 2.4.0.dev20200917
tfa-nightly 0.12.0.dev20200918223509
tb-nightly 2.4.0a20200921
File "...\Python38\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1117, in fit
callbacks.on_epoch_end(epoch, epoch_logs)
File "...\Python38\lib\site-packages\tensorflow\python\keras\callbacks.py", line 427, in on_epoch_end
callback.on_epoch_end(epoch, logs)
File "...\Python38\lib\site-packages\tensorflow\python\keras\callbacks.py", line 2274, in on_epoch_end
self._log_epoch_metrics(epoch, logs)
File "...\Python38\lib\site-packages\tensorflow\python\keras\callb …

Fix crash in CLR optimizer callback

---

tensorflow_addons/optimizers/discriminative_layer_training.py
tensorflow_addons/optimizers/tests/discriminative_layer_training_test.py
tensorflow_addons/utils/test_utils.py

Fix MultiOptimizer list of layers

---

.github/CODEOWNERS
README.md

The repo maintainers have discussed and we feel that the subpackage maintainer concept has grown stale. Originally we wanted to split subpackages amongst ourselves where small groups of maintainers would serve as the failsafe for given subpackages. In practice this meant every subpackage would have had a very limited amount of people who were ultimately responsible. This created unnecessary stress on maintainers to feel like they were required to keep working on the project in order for the subpackage to remain viable. 
Ultimately all write access maintainers can help across the repo and have been doing so for an extended period of time. However, there is an added need for reliable submodule owners which is what we've discovered over the past few months. We'll be working on improving that …

Remove subpackage maintainer concept

---

build_deps/toolchains/gpu/crosstool/BUILD.tpl

Add support for building from source for ARM64 architectures. Requests for this can be seen in https://github.com/tensorflow/addons/issues/1982

Add support for ARM architecture build from source

---

tensorflow_addons/image/cutout_ops.py

cutout op is not compatible with non eager mode because of condition: (mask == 0) - it is compatible only with eager mode
fix is replace it by tf.equal(mask, 0)
```
class Cutout(tf.keras.layers.Layer):
def __init__(self,
seed=None,
**kwargs):
super(Cutout, self).__init__(**kwargs)
self.seed = seed
def call(self, inputs, training=None):
if inputs.shape.rank != 3:  # [batch, time, feature]
raise ValueError('inputs.shape.rank:%d must be 3' % inputs.shape.rank)
if training is None:
training = tf.keras.backend.learning_phase()
net = tf.keras.backend.expand_dims(inputs, axis=-1)
net = random_cutout(net, (4, 2),
seed=self.seed)
net = tf.keras.backend.squeeze(net, axis=-1)
return net
input_shape = [2, 7, 5]
seed = 4
spectrogram = np.ones(input_shape)
inputs = tf.keras.layers.Input( …
```

make cutout op compatible with non eager mode

---

tensorflow_addons/utils/resource_loader.py

Fix https://colab.research.google.com/drive/19AFVhLDcFa1OHMkaZm5K3alytnxODaGh?usp=sharing. This is not the desired warning. We are built custom ops against TF2.3.*.

Update ABI compatibility version

---

tensorflow_addons/optimizers/tests/standard_test.py

References #992. 
Aim is to create a single test file that tests all relevant classes within the optimizer module of tfa. The test will discover classes that inherit from tf.keras.optimizers.Optimizer then execute a set of standard tests on each of those classes. 
This will test for common behaviors that optimizers should have (eg. serialization, minimizes, etc.).

Standardized Testing for All Optimizers

---

MIGRATION_TO_CORE.md

Updates the migration strategy.
cc @dynamicwebpaige @karmel @tomerk @tanzhenyu

Update migration strategy

---

tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops.cc
tensorflow_addons/image/tests/resampler_ops_test.py

Empty batches are possible in distributed synchronous training. If some
replicas have run out of data while some haven't, tf.distribute produces
empty batches so that the training can proceed.
unit test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/addons/2219)

Support empty batches in ResamplerOp

---

tools/install_deps/pytest.txt

MacOS py3.8 is failing to pip install scikit-image for testing. Should be no issue in upgrading this testing dependency.

Update testing dependency

---

.github/workflows/release.yml
README.md

As found in https://github.com/tensorflow/addons/pull/2205 we are no longer TF2.2 compatible. Going forward we should make sure we include previous TF versions in the build tests. I've rewritten the doc string so the intended use of that CI Action is known.

Drop TF2.2 compatibility

---

configure.py

Fix building package on raspberry pi
Build of package in raspbian buster container did work after applying the suggested changes

Fix building on raspberry pi

---

tensorflow_addons/metrics/tests/cohens_kappa_test.py

Fixes #2235, which is a minor typo.

Fix typo in test_keras_binary_classification_model() name

---

tensorflow_addons/layers/normalizations.py
tensorflow_addons/layers/tests/normalizations_test.py

This changes the default `groups` parameter to `32`, as recommended by the authors of [Group Normalization](https://arxiv.org/abs/1803.08494).
Fixes #2240

Change GroupNormalization default groups to 32.

---

build_deps/toolchains/gpu/cuda_configure.bzl
build_deps/toolchains/gpu/find_cuda_config.py

libcudart soname in CUDA 11.x is versioned as 11.0 for backward compatability.
This part is mostly taken from https://github.com/tensorflow/tensorflow/pull/43716
find_cuda_config.py was taken directly from TF (and reformatted with
black). cusparse changed versioning in cuda11 so that part is needed.
The other changes pulled in from TF is mostly more lib/header search
paths and a few style changes.
Signed-off-by: Jason Zaman <jason@perfinion.com>
- Build
With this change I can build with cuda11.1 and TF_CUDA_COMPUTE_CAPABILITIES="8.6" and the wheel works for training and inference on my RTX 3090. (This requires >tf-2.3, ie nightly or 2.4 which isnt released yet)

Update cuda config for CUDA11.1

---

tensorflow_addons/metrics/matthews_correlation_coefficient.py
tensorflow_addons/metrics/tests/matthews_correlation_coefficient_test.py

*  
As per the [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/backend/batch_set_value), the values in `batch_set_value` should be a numpy array. Passing a `tf.Tensor` throws the following exception when not running eagerly:
`TypeError: __array__() takes 1 positional argument but 2 were given`
This can easily be reproduced by either disabling eager exeuction, or by subclassing MCC and decorating `reset_states` with `tf.function` like so:
```
class MyMCC(tfa.metrics.MatthewsCorrelationCoefficient):
@tf.function
def reset_states(self):
"""Resets all of the metric state variables."""
reset_value = …
```

Fixes MCC during graph execution.

---

tensorflow_addons/callbacks/tqdm_progress_bar.py
tensorflow_addons/layers/adaptive_pooling.py
tensorflow_addons/layers/crf.py
tensorflow_addons/layers/esn.py
tensorflow_addons/layers/maxout.py
tensorflow_addons/layers/multihead_attention.py
tensorflow_addons/layers/netvlad.py
tensorflow_addons/layers/noisy_dense.py
tensorflow_addons/layers/normalizations.py
tensorflow_addons/layers/poincare.py
tensorflow_addons/layers/polynomial.py
tensorflow_addons/layers/snake.py
tensorflow_addons/layers/sparsemax.py
tensorflow_addons/layers/spatial_pyramid_pooling.py
tensorflow_addons/layers/spectral_normalization.py
tensorflow_addons/layers/stochastic_depth.py
tensorflow_addons/layers/tlu.py
tensorflow_addons/layers/wrappers.py
tensorflow_addons/rnn/esn_cell.py
tensorflow_addons/rnn/layer_norm_simple_rnn_cell.py
tensorflow_addons/utils/keras_utils.py

I've written custom parsers and emitters for everything from docstrings to classes and functions. However, I recently came across an issue with the TensorFlow codebase: inconsistent use of `Args:` and `Arguments:` in its docstrings. It is easy enough to extend my parsers to support both variants, howevever it looks like `Arguments:` is wrong anyway, as per:
- https://google.github.io/styleguide/pyguide.html#doc-function-args @ [`ddccc0f`](https://github.com/google/styleguide/blob/ddccc0f/pyguide.md)
- https://chromium.googlesource.com/chromiumos/docs/+/master/styleguide/python.md#describing-arguments-in-docstrings @ [`9fc0fc0`](https://chromium.googlesource.com/chromiumos/docs/+/9fc0fc0/styleguide/python.md)
- https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html @ …

[*.py] Rename "Arguments:" to "Args:"

---

tensorflow_addons/text/crf.py

Addresses #2231. Note that mixed precision has already been fixed in f429133, but the behavior is different from TensorFlow semantics.
Passes original tests.
*

Change CRF layer dtype

---

tensorflow_addons/optimizers/lazy_adam.py

Swap calls to `OptimizerV2._resource_scatter_update` and `OptimizerV2._resource_scatter_add` with direct calls to `resource_variable_ops.resource_scatter_update` and `resource_variable_ops.resource_scatter_sub`.
The `OptimizerV2` methods are wrappers around the `resource_variable_ops`, except they extract and return the underlying `Tensor` from the op instead of returning the operation. This causes a big performance hit as outlined in issue #2273.
The returned tensor is not necessary for this "lazy" version of Adam sparse updates, since the op isn't used in subsequent computation. Thus we can avoid the extra `.value()` call in `OptimizerV2._resource_scatter_update/sub/add`
Fixes #2273 
- [ X] I've properly [formatted my code according to the …

fix LazyAdam resource variable ops performance issue

---

tensorflow_addons/image/cutout_ops.py
tensorflow_addons/image/tests/cutout_ops_test.py

Brief Description of the PR: Bugfix for random_cutout mask which is not fully applied when randomly chosen mask location is chosen too close to the image boundary. 
Fixes # (2276)
Additional unit test
*  Bugfix for random_cutout mask which is not fully applied when randomly chosen mask location is chosen too close to the image boundary. Unit test applies a zero mask to 10 images of ones, and verifies the total expected sum over all images is correct. i.e. all of the zeros have been applied.

Rodert fix image random cutout 2276

---

tensorflow_addons/layers/multihead_attention.py
tensorflow_addons/layers/tests/multihead_attention_test.py

I was running with mixed precision (using `float16`s) and MultiHeadAttention caused me a mismatch error (`TypeError: x and y must have the same dtype, got tf.float16 != tf.float32`).
There might be a reason this layer absolutely needs to be float32 (for better precision). But if not, it would be nice to add the flexibility by using use `query`'s dtype instead of defaulting to `tf.float32` for the `depth` constant (see commit).
I made the change on my local machine and it resolved the error I was having. Also, it should not change the default behavior, since `query` is by default `tf.float32`. It should only have an effect when using `tf.float16`, etc, and that case is currently broken anyway.

make MultiHeadAttention agnostic to dtype (float32 vs. float16)

---

tensorflow_addons/image/color_ops.py
tensorflow_addons/image/tests/color_ops_test.py

Part of #2279.
Changes:
1. Made `sharpness_image` private (`_sharpness_image` now), as `sharpness` already handles single images and `_equalize_image` is private as well.
2. Made `sharpness` compatible with grayscale images (previously only worked with RGB).
3. Added the `name` argument and applied a `tf.name_scope`.
4. Decorated with `@tf.function`. **Now runs ~60% faster.** ([colab](https://colab.research.google.com/drive/1uZzz4G-Bfme1-9jaBsMPYTzykA25GsTu#scrollTo=mFA_HXxMmvhd))
5. Removed the `clip_by_value` invocation since the sharpening kernel is already normalized.
6. Refactored the tests. `sharpness` and `equalize` now both handle all input shapes.
Also removed a faulty test for `equalize`. That test was for the now unsupported `channels_first` and was passing because it was just …

Refactor sharpness

---

.github/workflows/make_wheel_Windows.sh
.github/workflows/make_wheel_macOS.sh
.github/workflows/release.yml
configure.py
tools/docker/build_wheel.Dockerfile
tools/testing/build_and_run_tests.sh

Support AVX2 compilation by default
Fixes #1148
Don't think we need to support anything older than AVX2. Also did some cleanup on our builds

Add AVX2 support

---

tensorflow_addons/image/tests/transform_ops_test.py
tensorflow_addons/image/transform_ops.py
tensorflow_addons/image/translate_ops.py

Support fill_value and nearest fill_mode with ImageProjectiveTransformV3.
Test new features.

Use ImageProjectiveTransformV3 for TF >= 2.4.0

---

.github/workflows/make_wheel_Windows.sh
README.md
configure.py

Cleanup where `--enable_runfiles` flag is set. Previously we just put this in the documentation for all OS since it didn't hurt but now configure will handle it and users don't need to worry about it.

Move enable_runfiles flag to configure.py

---

tensorflow_addons/utils/resource_loader.py

Need to update ABI compatibility on nightly and 0.12

Update ABI compatibility

---

tensorflow_addons/utils/resource_loader.py

The backport failed:
https://github.com/tensorflow/addons/pull/2306#issuecomment-748403736

Update ABI compatibility on r0.12

---

tensorflow_addons/image/dense_image_warp.py
tensorflow_addons/image/tests/dense_image_warp_test.py
tools/testing/source_code_test.py

Seems that we are hostile to `control_dependencies` so this PR removed it. It also makes the behavior consistent with docstring -- raises `ValueError` instead of `tf.errors.InvalidArgumentError` for invalid inputs. Note that removal of runtime check will result in
```python
fn = foo.get_concreate_function(tf.TensorSpec(shape=None))
fn(invalid_inputs)
```
throws unexpected errors.

Remove control dependency

---

tensorflow_addons/optimizers/average_wrapper.py
tensorflow_addons/optimizers/moving_average.py
tensorflow_addons/optimizers/stochastic_weight_averaging.py

Calling _get_decay once per variable can greatly slow down kernel
launches as it contains control flows. By putting decay into apply state
we only need to calcuate it once per step. The same optimization
technicle is applied in keras optimizer for learning rate scheduler.
python3 -m pytest tensorflow_addons/optimizers/tests/moving_average_test.py
*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/addons/2342)

Calcuate decay once per step instead once per variable #moving_average

---

tensorflow_addons/image/dense_image_warp.py
tools/testing/source_code_test.py

This attribute will help the TFLite conversion convert the whole block to a single TFLite custom op, significantly reduce the runtime.
Add experimental_implements attribute to dense_image_warp

Add experimental_implements attribute to dense_image_warp

---

tensorflow_addons/image/cutout_ops.py
tensorflow_addons/image/tests/cutout_ops_test.py

random_cutoff
tf.random.uniform requires that minval is smaller than maxval.
*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tensorflow/addons/2348)

Handle the case when mask size is larger than the image size in

---

configure.py

Default compile with only AVX (not AVX2) support. We can release a 0.12.1 patch in the coming weeks
Fixes #2336

Default compile with AVX support

---

.github/workflows/release.yml

Typically we don't need to build against minor versions, but since 2.4.1 changes compilation settings we should align. Planning on a 0.12.1 release for TFA after these go through

Set build against 2.4.1

---

.github/workflows/backport.yml
.github/workflows/release-drafter.yml

GitHub will be dropping support for shortened hashes in Actions on Feb 15th:
https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions

 Use full length SHA per GitHub guidelines

---

tensorflow_addons/optimizers/rectified_adam.py
tensorflow_addons/optimizers/tests/rectified_adam_test.py

When restoring the RectifiedAdam optimizer from a checkpoint, restoring fails with the following error message:
```ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: <tf.Tensor: shape=(), dtype=int32, numpy=0>```
The reason is that RectifiedAdam stores `total_steps` as an integer hyper-parameter:
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/optimizers/rectified_adam.py#L134
OptimizerV2 however creates variables by calling `add_weight` without a dtype in `_create_hypers`. In other words, it assumes that all hyper-parameters are floating point parameters.
Fixes #2361
I have trained a neural network with this optimizer and resumed training in between. Without this change, restoring fails with the error message from above. With this …

RectifiedAdam: Store 'total_steps' hyperparameter as float

---

tensorflow_addons/image/color_ops.py
tensorflow_addons/image/tests/color_ops_test.py

Changes the equalization method in color_ops.py to take in a variable number of histogram bins.
Fixes #2379
Function has been sanity tested to be the same as the old equalize_image and past tests should still pass. This PR adds `bins` as an optional `int` parameter which defaults to `256` to ensure backwards compatibility. The expected use case of this parameter is for imaging data which has greater dynamic range than 8-bit.

variable histogram bins added

---

tensorflow_addons/image/distort_image_ops.py
tensorflow_addons/image/tests/distort_image_ops_test.py

Adds python fallback for adjust_hsv_in_yiq. It's just a simple matmul, I do not see any performance regression when switching to python.

Add python fallback for adjust_hsv_in_yiq

---

tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op.cc
tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op_gpu.cu.cc
tensorflow_addons/image/tests/distance_transform_test.py

Fix edt float16 and float64 kernels
*

fix float16 and float64 kernels

---

docs/overview.md

Brief Description of the PR: Fix the CUDA path in the website installation-from-source instructions
Fixes #2429

Fix CUDA path envvar in website instructions

---

tensorflow_addons/metrics/matthews_correlation_coefficient.py
tensorflow_addons/metrics/tests/matthews_correlation_coefficient_test.py

#2339 
- [ x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
The issue created by the user is perfectly solved by this

Matthew Fix

---

tensorflow_addons/metrics/r_square.py
tensorflow_addons/metrics/tests/r_square_test.py

`RSquare.reset_states()` calles `batch_set_value()`, and the later one requires a numpy array in the input argument.
However, currently the `RSquare.reset_states()` passes a `tf.Tensor` (by `tf.zeros_like()`) instead of a numpy array.
That would cause `batch_set_value()` raising following error if `RSquare.reset_states()` is called in a tf.function.
```
.../tensorflow/python/keras/backend.py: batch_set_value
x.assign(np.asarray(value, dtype=dtype_numpy(x)))
.../numpy/core/numeric.py:asarray
return array(a, dtype, copy=False, order=order)
TypeError: __array__() takes 1 positional argument but 2 were given
```
* Add a test, which calls …

Make RSquare.reset_states to be able to run in tf.function

---

tensorflow_addons/metrics/f_scores.py

Fix incorrect rendering of option "None" of F1Score's average parameter

Fix F1Score docs

---

tensorflow_addons/text/crf.py

Brief Description of the PR: Fix wrong type hinting of `crf_log_likelihood`. `crf_log_likelihood` is returning a tuple of two tensors, but type hinting is a `tf.Tensor` now.
Fixes #2470 
*

fix wrong type hinting of `crf_log_likelihood`

---

docs/tutorials/networks_seq2seq_nmt.ipynb

The order in which the parameters are printed [here](https://www.tensorflow.org/addons/tutorials/networks_seq2seq_nmt#some_important_parameters) was incorrect and thus correcting it.
@bhack , please review.

Correcting the order

---

configure.py

The build under Ubuntu on Raspberry PI fails. The gcc switch `mavx` is x86 specific:
gcc: error: unrecognized command line option '-mavx'
The compilation steps:
~~~shell
python3 ./configure.py
bazel build build_pip_pkg
bazel-bin/build_pip_pkg artifacts
~~~
are now also working on a Rasp Pi 4 using Ubuntu.

build fix Raspberry Pi 4 Linux ARM64

---

tensorflow_addons/layers/embedding_bag.py
tensorflow_addons/layers/tests/embedding_bag_test.py

Fix bugged gradients when combiner == 'MEAN'

---

build_deps/build_pip_pkg.sh

Brief Description of the PR: Apple silicon support.
Fixes #2503
The steps are as follows. 
(I installed python 3.9.5 with pyenv and pyenv-virtualenv.)
pip install tensorflow-macos
pip install tensorflow-metal
xcode-select --install || echo OK
export BAZEL_VERSION=3.7.2
curl -fLO "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-darwin-x86_64.sh"
chmod +x "bazel-${BAZEL_VERSION}-installer-darwin-x86_64.sh"
./bazel-${BAZEL_VERSION}-installer-darwin-x86_64.sh --user
(set the PATH to bazel)
git clone -b mywork https://github.com/tetsuyasu/addons.git/
cd addons
python3 ./configure.py
bazel build build_pip_pkg
pip install pathlib
bazel-bin/build_pip_pkg artifacts
pip install artifacts/tensorflow_addons-*.whl

Apple silicon support

---

tensorflow_addons/layers/stochastic_depth.py
tensorflow_addons/layers/tests/stochastic_depth_test.py

`StochasticDepth` layer throws error `TypeError: Input 'y' of 'Mul' Op has type float16 that does not match type float32 of argument 'x'.` if training in `mixed_float16` condition.
I think we need a `dtype=self._compute_dtype_object` or `dtype=self.compute_dtype` in `tf.keras.backend.random_bernoulli` here.
Minimal reproducing code:
```py
from tensorflow import keras
from tensorflow_addons.layers import StochasticDepth
import numpy as np
keras.mixed_precision.set_global_policy("mixed_float16")
inputs = keras.layers.Input([10, 10, 3])
nn = keras.layers.Conv2D(3, 1)(inputs)
sd = StochasticDepth(0.5)
nn = sd([inputs, nn])
nn = keras.layers.Flatten()(nn)
nn = keras.layers.Dense(2, activation="softmax", dtype="float32")(nn)
mm = keras.models.Model(inputs, nn) …
```

Fix StochasticDepth layer error in training mixed_float16 

---

README.md
tensorflow_addons/activations/gelu.py
tensorflow_addons/callbacks/average_model_checkpoint.py
tensorflow_addons/image/tests/transform_ops_test.py
tensorflow_addons/image/transform_ops.py

#2516 removed support for TensorFlow 2.3. This PR is a followup and removes leftover compatibility code that should no longer be needed.
/cc @seanpmorgan 
This is covered by the existing unittests running on CI

Remove compatibility code for TensorFlow < 2.4

---

docs/tutorials/layers_normalizations.ipynb

Remove bad link.

---

tools/docker/dev_container.Dockerfile

Previous container only supports up to py3.6 which TF2.7 is not built for. TF team has stopped publishing these custom-op images since TF2.5.
Using the CUDA image makes the container larger, but it still uses the cpu only version of TF so it's accurate to call it dev_cpu. Building the gpu image would be pretty trivial now, but also this limits the maintenance burden on our team.
There is no multipython container without GPU installs:
https://console.cloud.google.com/gcr/images/tensorflow-testing/GLOBAL

Use multipython image for dev container

---

.github/workflows/release.yml

Per discussion in SIG meeting we will not gait the Addons releases until tensorflow-macos provides an SLA. We will continue to publish tfa-nightly m1 wheels.

Drop macOS ARM wheels from 0.15 release

---

.github/CODEOWNERS
tensorflow_addons/layers/__init__.py
tensorflow_addons/layers/max_unpooling_2d_v2.py
tensorflow_addons/layers/tests/max_unpooling_2d_v2_test.py
tools/testing/source_code_test.py

Add MaxUnpooling2DV2 layer.
The _max_pool_with_argmax_ function can map several input sizes to the same output size. Hence, to avoid ambiguity in the inversion process, the stride and padding arguments have been replaced by the output_size argument. This has been done in a new layer rather than in the existing MaxUnpooling2D class to avoid compatibility issues.
I run the layer_test

Add MaxUnpooling2DV2 layer

---

build_deps/toolchains/gpu/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl

I've got an error related to c++14 support while building addons v0.15.0 with GPU support above tf 2.7.0
```bash
bazel-out/k8-opt/bin/external/local_config_tf/include/tensorflow/core/framework/tensor_types.h(176): error: "auto" is not allowed here
bazel-out/k8-opt/bin/external/local_config_tf/include/tensorflow/core/framework/tensor_types.h(176): error: pack expansion does not make use of any argument packs
bazel-out/k8-opt/bin/external/local_config_tf/include/tensorflow/core/framework/tensor_types.h(177): error: pack expansion does not make use of any argument packs
3 errors detected in the compilation of "tensorflow_addons/custom_ops/seq2seq/cc/kernels/beam_search_ops_gpu.cu.cc".
ERROR: /home/alex/jupyter/build/addons/tensorflow_addons/custom_ops/seq2seq/BUILD:7:18: output …
```

Allow c++14 for nvcc

---

docs/tutorials/layers_normalizations.ipynb

Brief Description of the PR: fix typos: "neual" -> "neural", and "independt" -> "independently".
*

Fix layers_normalizations.ipynb typos

---

tensorflow_addons/image/dense_image_warp.py
tensorflow_addons/image/tests/dense_image_warp_test.py
tools/testing/source_code_test.py

Enables the assertions to be included as part of the traced graph allowing functions traced with shapeless Tensors to be used for shaped instances and throw the proper exceptions.
Removed `test_symbolic_tensor_shape` because it is not supported as per KerasTensor update.
This CL prevents the updated code from being broken on the rollout of enabling subtyping for tf.function.
*

Generate Assertion Ops for interpolate_bilinear

---

tensorflow_addons/optimizers/lamb.py
tensorflow_addons/optimizers/tests/lamb_test.py

Fixes #2610 
- [x ] Bug fix
By writing a unit test
*  Ran pytest

In LAMB optimizer, rename weight_decay_rate to weight_decay

---

docs/tutorials/average_optimizers_callback.ipynb
docs/tutorials/layers_normalizations.ipynb

Brief Description of the PR: fix typo genral -> general
*

Fix typo in average optimizers callback

---

tensorflow_addons/optimizers/lamb.py

Before:
```py
import tensorflow_addons as tfa
mm = keras.models.Sequential([keras.layers.Input([32, 32, 3]), keras.layers.Flatten(), keras.layers.Dense(10)])
mm.compile(optimizer=tfa.optimizers.LAMB(learning_rate=0.1, weight_decay_rate=0.02, exclude_from_weight_decay=['/gamma', '/beta']))
mm.save('aa.h5')
bb = keras.models.load_model('aa.h5')
print(bb.optimizer.exclude_from_weight_decay, bb.optimizer.exclude_from_layer_adaptation)
```
After:
```py
import tensorflow_addons as tfa
mm = keras.models.Sequential([keras.layers.Input([32, 32, 3]), keras.layers.Flatten(), keras.layers.Dense(10)])
mm.compile(optimizer=tfa.optimizers.LAMB(learning_rate=0.1, weight_decay_rate=0.02, exclude_from_weight_decay=['/gamma', '/beta']))
mm.save('aa.h5')
bb = keras.models.load_model('aa.h5') …
```

Save exclude_from_weight_decay in config for LAMB

---

.github/workflows/release.yml
build_deps/build_pip_pkg.sh

`macos-latest` has started migrating to macos-11:
https://github.blog/changelog/2021-09-29-github-actions-jobs-running-on-macos-latest-are-now-running-on-macos-big-sur-11/
Making a PR to set these as pinned versions.

Pin mac build environment's OS version

---

tensorflow_addons/optimizers/lamb.py
tensorflow_addons/optimizers/tests/lamb_test.py
tensorflow_addons/optimizers/tests/weight_decay_optimizers_test.py
tensorflow_addons/optimizers/utils.py
tensorflow_addons/optimizers/weight_decay_optimizers.py

- Add `exclude_from_weight_decay` for `DecoupledWeightDecayExtension` optimizers including `AdamW` and `SGDW`, like `LAMB`. There are several issues on this, like [Support exclude_from_weight_decay in AdamW #1903](https://github.com/tensorflow/addons/issues/1903) and [Add decay_var_list as init option to DecoupledWeightDecayExtension #2018](https://github.com/tensorflow/addons/issues/2018).
- This PR is a mimic of current `LAMB exclude_from_weight_decay` behavior, and it has a conflict with current `DecoupledWeightDecayExtension` `_decay_var_list`. I'm actually looking forward if a better solution can be introduced.
- [Support exclude_from_weight_decay in AdamW #1903](https://github.com/tensorflow/addons/issues/1903).
- [Add decay_var_list as …

exclude_from_weight_decay for AdamW and SGDW

---

tensorflow_addons/text/crf.py
tensorflow_addons/text/tests/crf_test.py

* Addresses issue #2639 by adding the `zero_output_for_mask=True` arg in `crf_decode_forward`
* Adds two new tests to show the mask is properly applied
* Test to show that when a mask is applied, masked positions are equal to zero
* Test to show that when masking is *not* applied, no positions are equal to zero

Fix kwargs in crf_decode_forward

---

tensorflow_addons/metrics/tests/matthews_correlation_coefficient_test.py
tensorflow_addons/metrics/tests/r_square_test.py
tools/install_deps/pytest.txt

This PR upgrade `scikit-learn` and re-enables the relevant tests on CI to partially address #2666.
Let's see what CI thinks about this...

:arrow_up: `scikit-learn`

---

tensorflow_addons/optimizers/tests/weight_decay_optimizers_test.py
tensorflow_addons/optimizers/weight_decay_optimizers.py

This PR changes the handling of `exclude_from_weight_decay` to ensure that the regex is only evaluated once per step. Currently it gets called within a distributed `merge_call` which might lead to problems.
I implemented this when trying to debug a performance regression which turned out to be unrelated to this, but I think this still is a nice cleanup to have since it consolidates the handling of `decay_var_list` and `exclude_from_weight_decay`.
I adapted the unittests that where directly relying on the internal functions that had been modified.

Simplify `exclude_from_weight_decay` implementation

---

tensorflow_addons/layers/normalizations.py
tensorflow_addons/layers/tests/normalizations_test.py

Fixes #2677
Normalization layers  in `normalizations.py` have been write very well.  Thanks for the contributors.  These layers work well in most cases, but their behavor in `compute_output_shape` is very smallly different from their description and  different from `tf.keras.layers.Layer`'s design ideas about `compute_output_shape` .
Since  `tfa.layers.GroupNormalization`, `tfa.layers.InstanceNormalization` and `tfa.layers.FilterResponseNormalization` are all inherited from `tf.keras.layers.Layer`, they all override `compute_output_shape` function. 
However, there is no need to override this function, because  `tf.keras.layers.Layer` has done it well, i.e., if `call` and `build` functions have been overrided, the layer can automaticly give out correct output_shape buy …

fix compute_output_shape behavior in normalizations.py

---

configure.py
requirements.txt
tensorflow_addons/text/tests/crf_test.py
tensorflow_addons/utils/ensure_tf_install.py
tensorflow_addons/utils/resource_loader.py

migrate api and fix build issue

---

tensorflow_addons/layers/optical_flow.py

The link to the paper appears correctly as https://arxiv.org/abs/1504.06852 in the docstring of `_correlation_cost`. The docstring of `CorrelationCost` however contained a truncated and therefore broken version of this link.
Fixes # (issue) - N/A
Generating the documentation was not tested.

Docs: Fix one link to the FlowNet paper

---

build_deps/toolchains/gpu/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl

Avoids binary bloat by only generating PTX for the highest compute capability in the list.

Only generate ptx for highest compute capability

---

tensorflow_addons/optimizers/adabelief.py
tensorflow_addons/optimizers/tests/adabelief_test.py

Brief Description of the PR: 
This PR solves the same issue reported in https://github.com/tensorflow/addons/issues/2361, by avoiding storing a int32 variable.

Failing to restore AdaBelief optimizer from checkpoint 

---

tensorflow_addons/optimizers/discriminative_layer_training.py
tensorflow_addons/optimizers/tests/discriminative_layer_training_test.py
tools/testing/source_code_test.py

MultiOptimizer does not call `super().apply_gradients`, and therefore does not update its `iterations: tf.Variable<type=int, shape=[]>` as the other optimizers in Tensorflow.
This leads to buggy behavior when training with a more complex `train_step` that relies on this variable for scheduling *learning rate* or other hyper-parameters such as *increasing/decreasing weights* for individual losses.

Increment MultiOptimizer iterations after each apply_gradients

---

tensorflow_addons/optimizers/discriminative_layer_training.py
tensorflow_addons/optimizers/tests/discriminative_layer_training_test.py

The current implementation of `MultiOptimizer` puts grads and vars inside the `optimizer_specs` variable. Since the grads and vars are not serializable, any model that uses `MultiOptimizer` class cannot be saved or checkpointed. This PR will only extract the necessary `optimizer_specs` components that are useful for re-instantiating the `MultiOptimizer` instance inside `get_config()` method, leading to a serializable `MultiOptimizer` implementation.
*  
I have tested `model.save()` method after this change. Prior to this change, a trained model (has run training iteration for at least 1 step) with `MultiOptimizer` cannot be saved because of the un-serializable grads and …

Make MultiOptimizer serializable

---

tools/docker/sanity_check.Dockerfile

The CI is failing with the error  (e.g. https://github.com/tensorflow/addons/pull/2739): 
```
#20 2.103   File "/usr/local/lib/python3.7/site-packages/tensorflow_docs/api_generator/reference_resolver.py", line 88, in ReferenceResolver
#20 2.103     physical_path: Optional[dict[str, str]] = None,
#20 2.103 TypeError: 'type' object is not subscriptable
```
because `tensorflow_docs` is using a feature introduced in python3.9. This fix bumps the python version for the `docs_tests` target in `tools/docker/sanity_check.Dockerfile`.
Locally the command `bash tools/run_build.sh` run successfully after the change.

tensorflow_docs requires python3.9

---

tensorflow_addons/metrics/kendalls_tau.py
tensorflow_addons/metrics/tests/kendalls_tau_test.py

~Blocked by https://github.com/tensorflow/addons/pull/2740~
The metric was only working in eager mode. This fix makes it work in graph mode too.
The metric was giving NaNs when running in graph mode. I modified the test to check against the NaN values.

Fix the Kendalls Tau metric when used in graph mode

---

tensorflow_addons/optimizers/weight_decay_optimizers.py

Use consistent markdown formatting for the AdamW paper

---

.github/workflows/make_wheel_macOS_arm64.sh
.github/workflows/make_wheel_macOS_x86.sh

The rpaths in the `custom_ops` libraries are invalidated once packaged into the wheel, this prevents delocate from retrieving the tensorflow dependency. This PR solves the issue by setting the env variable `DYLD_LIBRARY_PATH`.
`delocate==0.9.1` was failing silently with older version of `setuptools` (the packaged libraries were not processed). Upgrading to the lastest version solves the issue.
This fixes the current CI issue.

Fix wheel building for macos

---

tensorflow_addons/metrics/streaming_correlations.py

Optimizes the streaming correlation metrics by removing a while loop as well as usage of `tf.sparse.add` that computes only on CPU.

Correlation metrics optimization

---

README.md

```
tf-docker / > /dt9/usr/bin/gcc --version
gcc (GCC) 9.3.1 20200408
```

Correct GCC version on README

---

build_deps/toolchains/gpu/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl

Allow local build with GPU support against TF 2.10
Partly fixes #2712
To build locally it still required to manually replace crosstool_top value in .bazelrc with "@local_config_cuda//crosstool:toolchain"
Local build with GPU support finished successful with these changes

Fix local build with GPU support

---

tensorflow_addons/custom_ops/image/cc/ops/resampler_ops.cc
tensorflow_addons/custom_ops/layers/cc/kernels/correlation_cost_op.cc
tensorflow_addons/custom_ops/layers/cc/kernels/correlation_cost_op_gpu.cu.cc
tensorflow_addons/custom_ops/layers/cc/ops/correlation_cost_op.cc
tensorflow_addons/custom_ops/layers/cc/ops/embedding_bag_ops.cc
tensorflow_addons/custom_ops/seq2seq/cc/ops/beam_search_ops.cc
tensorflow_addons/custom_ops/text/cc/ops/skip_gram_ops.cc

The OkStatus() symbols was added on May 2022, between the 2.9 and 2.10 releases of Tensorflow. The Tensorflow v2.10 release happened on September 6, 2022.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tsl/platform/status.h#L102
Code cleanup.
- [ x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
- [] This PR addresses an already submitted issue for TensorFlow Addons
python3 -m pytest tensorflow_addons.
Failures are the same.

Replace tensorflow::Status::OK() with tensorflow::OkStatus().

---

tensorflow_addons/optimizers/adabelief.py
tensorflow_addons/optimizers/average_wrapper.py
tensorflow_addons/optimizers/constants.py
tensorflow_addons/optimizers/lookahead.py
tensorflow_addons/optimizers/tests/moving_average_test.py
tensorflow_addons/optimizers/tests/stochastic_weight_averaging_test.py
tensorflow_addons/optimizers/weight_decay_optimizers.py
tools/testing/source_code_test.py

Optimizer code change to get compatible with the optimizer migration in TF 2.11. 
As a summary the following changes are made:
1. Adjust how `KerasLegacyOptimizer` is determined. Now we check if `optimizers.experimental` and `optimizers` point to the same module. 
2. In unit tests we should use the legacy optimizer if it is available. 
3. some auto formatting.

Get compatible with optimizer migration in TF 2.11

---

tensorflow_addons/metrics/tests/streaming_correlations_test.py

fix metrics testing failure due to optimizer change

---

tensorflow_addons/layers/embedding_bag.py

`self.input_length` is not defined, which affects the pickling / unpickling of this layer in `tf` model mode.
Of the two options of adding `input_length` or removing it entirely, it seems more elegant to remove it. The attribute `input_length` was likely ported from [TF Embedding Layer](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding), where it might be necessary; however, in EmbeddingBag there does not appear to be such requirements. 
The alternative way to solve the issue is to take `input_length` as an `int` argument set to `None` but this seems likely to be more confusing and would additionally require a modification to the documentation
`2803`
- [x ] Bug fix
- [x ] I've properly [formatted my code according to the …

Update embedding_bag.py for save_model in 'tf' mode

---

tensorflow_addons/image/cutout_ops.py

Fixes #2814
By running the code from the issue reproducing the memory leak, here are the outputs now:
```
1.32 GB
1.32 GB
1.32 GB
1.32 GB
1.32 GB
1.32 GB
1.32 GB
1.32 GB
1.32 GB
1.32 GB
1.32 GB
1.33 GB
```

Fix Cutout memory leak

---

tensorflow_addons/optimizers/discriminative_layer_training.py
tensorflow_addons/utils/test_utils.py
tensorflow_addons/utils/types.py

Recently, Keras changed how you must import internal symbols. Now, you must import private symbols from `keras.src` instead of `keras`, e.g. you must use `from keras.src.utils import tf_utils` instead of `from keras.utils import tf_utils`. See slide 12 of the [April Keras community meeting slides](https://drive.google.com/file/d/1uY4aJtYYnHOgmvBQO5yz_o36dsah4_8u/view) for details Because old versions of Keras, including the current stable version, require the old import form, this PR changes every file importing internal Keras symbols to try both import forms: first it tries importing the new version (with `keras.src`), and if that fails, it tries importing the old version (with `keras`)
Without this change, TF Addons cannot be imported with the latest …

Fix Keras imports.

---

tensorflow_addons/image/dense_image_warp.py

Using experimental_implements feature now enforces purity on tf.function (all inputs must be Tensors). However, the default value here is None which is not allowed.
- [ x] Bug fix
*

Pure tf.functions can't have None inputs

---

.github/workflows/backport.yml
.github/workflows/ci_test.yml
.github/workflows/notify_codeowners.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml
.github/workflows/validate_codeowners.yml

Setting GITHUB_TOKEN permissions for all workflows.
I was not sure how to flag the type of change.
Fixes #2847 
The permissions were mostly generated from the Step Security tool, which has a database for actions needed permissions. To the workflows that used github api calls, I've checked the needed permissions by looking at https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview

Set permissions to GITHUB_TOKEN

---

WORKSPACE
build_deps/tf_dependency/tf.patch

Create a patch to use non_hermetic python in TF, bump workspace TF version to 2.14.0

Build with TF 2.14

---

tensorflow_addons/image/tests/distort_image_ops_test.py
tensorflow_addons/optimizers/discriminative_layer_training.py
tensorflow_addons/optimizers/lazy_adam.py
tensorflow_addons/rnn/abstract_rnn_cell.py
tensorflow_addons/rnn/esn_cell.py
tensorflow_addons/rnn/nas_cell.py
tensorflow_addons/seq2seq/BUILD
tensorflow_addons/seq2seq/attention_wrapper.py
tensorflow_addons/text/BUILD
tensorflow_addons/text/crf.py
tensorflow_addons/utils/test_utils.py
tensorflow_addons/utils/tf_inspect.py
tensorflow_addons/utils/tf_test_utils.py
tensorflow_addons/utils/types.py

Keras 3.0 will become default in TF 2.16 (and is currently default in tf-nightly).  This breaks this tf-addons package.  Here we make minimal changes to return functionality in a backward-compatible way.
None known reported.
- [] By running Black + Flake8
Imported with tf-nightly, keras-nightly, tf_keras-nightly, setting both `TF_USE_LEGACY_KERAS=0` and `1`.

Fix tf-addons for upcoming keras 3 default.

---

tensorflow_addons/custom_ops/image/cc/kernels/adjust_hsv_in_yiq_op.h
tensorflow_addons/custom_ops/image/cc/kernels/connected_components.h
tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op.h
tensorflow_addons/custom_ops/seq2seq/cc/kernels/beam_search_ops.cc
tensorflow_addons/custom_ops/seq2seq/cc/kernels/beam_search_ops.h

Eigen header path was changed in TF 2.16. This PR fixes the build error.
Fixes #2860
*

Update eigen header locations for TF 2.16
