tensorflow_addons/layers/BUILD, tensorflow_addons/layers/python/maxout.py, tensorflow_addons/layers/python/poincare.py, tensorflow_addons/utils/BUILD, tensorflow_addons/utils/README.md, tensorflow_addons/utils/python/keras_utils.py
=> add register_keras_custom_object

tensorflow_addons/crf/BUILD, tensorflow_addons/crf/README.md
This was originally added just to build out the directory structure. As we're nearing a release this shouldn't clutter the repo. 
When #22 is complete it can be added again.
=> FIX: Remove crf placeholder

README.md
=> DOC: Add calendar invite info

tensorflow_addons/custom_ops/image/python/transform.py, tensorflow_addons/custom_ops/image/python/transform_test.py, tensorflow_addons/custom_ops/text/python/skip_gram_ops.py, tensorflow_addons/custom_ops/text/python/skip_gram_ops_test.py, tensorflow_addons/layers/python/maxout.py, tensorflow_addons/layers/python/maxout_test.py, tensorflow_addons/layers/python/poincare.py, tensorflow_addons/layers/python/poincare_test.py, tensorflow_addons/layers/python/wrappers.py, tensorflow_addons/layers/python/wrappers_test.py, tensorflow_addons/losses/python/lifted.py, tensorflow_addons/losses/python/lifted_test.py, tensorflow_addons/losses/python/metric_learning.py, tensorflow_addons/losses/python/triplet.py, tensorflow_addons/losses/python/triplet_test.py, tensorflow_addons/optimizers/python/lazy_adam_optimizer.py, tensorflow_addons/optimizers/python/lazy_adam_optimizer_test.py
Couple of different ways this could be done so wanted to submit the PR and discuss. When we merge this we should probably start a STYLE doc and add this.
Closes #50
=> FIX: Use correct TF imports

BUILD, README.md, tensorflow_addons/activations/BUILD, tensorflow_addons/activations/README.md, tensorflow_addons/activations/__init__.py, tensorflow_addons/activations/python/sparsemax.py, tensorflow_addons/activations/python/sparsemax_test.py, tensorflow_addons/layers/BUILD, tensorflow_addons/layers/__init__.py, tensorflow_addons/layers/python/sparsemax.py, tensorflow_addons/layers/python/sparsemax_test.py, tensorflow_addons/losses/BUILD, tensorflow_addons/losses/README.md, tensorflow_addons/losses/__init__.py, tensorflow_addons/losses/python/sparsemax_loss.py, tensorflow_addons/losses/python/sparsemax_loss_test.py, tensorflow_addons/utils/BUILD, tensorflow_addons/utils/python/keras_utils.py, tensorflow_addons/utils/python/test_utils.py
* ENH: Including a Sparsemax Later and A SparsemaxLoss class
=> implement sparsemax and sparsemax_loss

CONTRIBUTING.md, README.md, STYLE_GUIDE.md
=> introduction about coding style

README.md
Add pypi and gitter badges to help community
=> DOC: Add pypi and gitter badges

tools/ci_testing/addons_gpu.sh
Open to any additional changes or requests. All I did was enable CUDA.
=> Adding a GPU test script.

README.md
Adding continuous build badges to TensorFlow Addons.
=> Adding Continuous build badges.

tensorflow_addons/activations/README.md, tensorflow_addons/layers/README.md, tensorflow_addons/losses/README.md
PS: I think you need lint/check for trailing spaces.
=> set AndreasMadsen as sparsemax maintainer

tensorflow_addons/seq2seq/__init__.py, tensorflow_addons/seq2seq/attention_wrapper.py, tensorflow_addons/seq2seq/basic_decoder.py, tensorflow_addons/seq2seq/beam_search_decoder.py, tensorflow_addons/seq2seq/decoder.py, tensorflow_addons/seq2seq/loss.py, tensorflow_addons/seq2seq/sampler.py
=> Define the seq2seq module API

tensorflow_addons/layers/README.md
I added myself to the submodule Maintainer list. 
Greets
=> Added Submodule Maintainer

.github/CODEOWNERS, tensorflow_addons/image/README.md, tensorflow_addons/losses/README.md
Add maintainer of `dense_image_warp*`, `distort_image_ops*` and `contrastive*`.
=> Add maintainer

tensorflow_addons/losses/contrastive_test.py, tensorflow_addons/losses/lifted_test.py, tensorflow_addons/losses/sparsemax_loss_test.py, tensorflow_addons/losses/triplet_test.py, tensorflow_addons/seq2seq/attention_wrapper_test.py, tensorflow_addons/seq2seq/beam_search_decoder_test.py, tools/ci_build/pylintrc
=> BLD: disable pylint not-callable checker temporarily

requirements.txt
Pin to nightly version until a fix for https://github.com/tensorflow/tensorflow/issues/27697 is in nightly whl. This has been hindering progress on our repo because we can't run CI
=> Pin nightly version until fix is in place

tensorflow_addons/image/dense_image_warp.py, tensorflow_addons/image/distort_image_ops.py
Addresses #156 and corrects some docstrings. It's better to merge this after merging #157.
=> unify style for image operations

STYLE_GUIDE.md
added link to TensorFlow coding style guide
=> updated style guide

tensorflow_addons/layers/README.md, tensorflow_addons/layers/__init__.py, tensorflow_addons/layers/normalizations.py, tensorflow_addons/layers/normalizations_test.py
I removed LayerNorm from layers/Normalizations.py since it moved to core. This resolves #172
=> removed layernorm

.github/CODEOWNERS, tensorflow_addons/image/BUILD, tensorflow_addons/image/README.md, tensorflow_addons/image/__init__.py, tensorflow_addons/image/filters.py, tensorflow_addons/image/filters_test.py
=> Restructure filters

tensorflow_addons/examples/optimizers_lazyadam.ipynb
=> Fix colab link

tensorflow_addons/image/transform_ops.py
=> FIX: Use public API for name_scope and convert_to_tensor

requirements.txt
Until https://github.com/tensorflow/tensorflow/issues/27955 is fixed.
=> Pin to old nightly version

requirements.txt
=> Unpin nightly

tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op.h
=> FIX: Explicitly cast minDistance to float

tensorflow_addons/image/filters.py
New function names:
https://github.com/tensorflow/tensorflow/commit/52d006a310b8ef6b8bbe48911a183215c4494943#diff-68052049ee5dc7573829a5fdb7a57310
This broke on the 20190419 nightly so #191 should be merged before these tests will pass.
cc @Mainak431 for visibility
=> Utilize new tf.image function names

tensorflow_addons/image/distance_transform.py, tensorflow_addons/losses/lifted.py, tensorflow_addons/losses/triplet.py, tensorflow_addons/optimizers/lazy_adam_test.py, tensorflow_addons/text/skip_gram_ops_test.py, tensorflow_addons/utils/keras_utils.py
While prepping for the issue to core I did some cleanup of private APIs
=> CLN: Use public APIs

tensorflow_addons/image/transform_ops_test.py
=> CLN: API fix

examples/layers_weightnormalization.ipynb
=> FIX: x_test scaling

requirements.txt, tensorflow_addons/seq2seq/attention_wrapper.py, tensorflow_addons/seq2seq/attention_wrapper_test.py, tensorflow_addons/seq2seq/basic_decoder.py, tensorflow_addons/seq2seq/basic_decoder_test.py, tensorflow_addons/seq2seq/beam_search_decoder.py, tensorflow_addons/seq2seq/beam_search_decoder_test.py, tensorflow_addons/seq2seq/beam_search_ops_test.py, tensorflow_addons/seq2seq/decoder.py, tensorflow_addons/seq2seq/decoder_test.py, tensorflow_addons/utils/test_utils.py
Closes #134 as best it can be at the moment.
=> CLN: seqs2seq use public apis

tensorflow_addons/seq2seq/decoder.py, tensorflow_addons/seq2seq/sampler.py
Due to the change of broadcast behavior change in TF v2, the code
has been updated to first expand_dim() with -1, and then followed by
a tf.broadcast_to().
This is trying to fix https://github.com/tensorflow/addons/issues/254
=> Update the tf.compat.v1.where to tf.where in v2.

tensorflow_addons/losses/README.md, tensorflow_addons/losses/contrastive.py, tensorflow_addons/losses/focal_loss.py, tensorflow_addons/losses/lifted.py, tensorflow_addons/losses/sparsemax_loss.py, tensorflow_addons/losses/triplet.py, tensorflow_addons/utils/keras_utils.py
=> Refactor loss to inherit from tf.keras.losses.Loss

tensorflow_addons/activations/sparsemax.py
=> Update sparsemax to use where v2

tensorflow_addons/version.py
In preparation for building against TF2 release candidate
=> Increase to 0.4 version

tensorflow_addons/image/dense_image_warp_test.py, tensorflow_addons/layers/wrappers_test.py, tensorflow_addons/optimizers/weight_decay_optimizers_test.py
Fix broken nightlies and ensure we're only using tf.keras optimizers in test cases
=> FIX: Use all keras optimizers

tensorflow_addons/image/dense_image_warp.py, tensorflow_addons/image/dense_image_warp_test.py
=> Fix shape checking

.gitignore
Is it ok if we add `.DS_store` to .gitignore file for convenience?
=> adding .DS_store to gitignore

tensorflow_addons/image/distance_transform.py
=> Minor: fix typo in distance_transform TypeError message

tensorflow_addons/image/README.md
* Assume maintainership of unmaintained submodules transform_ops
and distance_transform_ops
=> Add @mels630 as tfa.image submodule maintainer

.github/CODEOWNERS, README.md, tensorflow_addons/BUILD, tensorflow_addons/__init__.py, tensorflow_addons/callbacks/BUILD, tensorflow_addons/callbacks/README.md, tensorflow_addons/callbacks/__init__.py
cc: @seanpmorgan @facaiy @WindQAQ 
Closes #61.
Overriding #286 due to inactivity.
=> Initial folder setup for callbacks

requirements.txt
Pin tf2-nightly version until fix #321
=> BUG: pin tf2-nightly version until fix

examples/layers_weightnormalization.ipynb, examples/optimizers_lazyadam.ipynb
Updating tf dependency versions
=> Bump tf version in examples

makefile, tools/ci_testing/addons_cpu.sh, tools/ci_testing/addons_gpu.sh, tools/run_docker.sh
Based on #325 . Related with #294.
@seanpmorgan @av8ramit Hi, does it look complicated?
```bash
bash tools/run_docker.sh -c 'make code-format' 
bash tools/run_docker.sh -c 'make sanity-check'  # Ubuntu Sanity Check
bash tools/run_docker.sh -s linux -d cpu -p py2 -c 'make unit-test'  # Ubuntu Python2
bash tools/run_docker.sh -s linux -d cpu -p py3 -c 'make unit-test'  # Ubuntu Python3
bash tools/run_docker.sh -s linux -d gpu -p py2 -c 'make gpu-unit-test'  # Ubuntu GPU Python2
bash tools/run_docker.sh -s linux -d gpu -p py3 -c 'make gpu-unit-test'  # Ubuntu GPU Python3
```
=> add run_docker.sh script

tensorflow_addons/losses/README.md, tensorflow_addons/optimizers/README.md
Hi @seanpmorgan 
Just read TF Addons newsletter. Would like to maintain `focal loss` and `lazy adam` module if that is ok
=> Maintain focal loss and lazy adam

tensorflow_addons/image/distance_transform.py, tensorflow_addons/image/distance_transform_test.py
Update `euclidean_dist_transform` as per #332
=> Add unknown shape support to distance_transform_ops

tensorflow_addons/image/filters.py, tensorflow_addons/image/filters_test.py
=> [image/filters] convert unknown rank to 4d

tensorflow_addons/seq2seq/loss.py, tensorflow_addons/seq2seq/loss_test.py
Copying the error messages from above (and adding a little phrase to explain why this isn't possible).
=> Fix #329 by adding ValueError for mixed aggregation modes

tensorflow_addons/optimizers/__init__.py, tensorflow_addons/optimizers/moving_average_test.py
Wrap the class in `run_all_in_graph_and_eager_modes` instead of wrapping each method in `run_in_graph_and_eager_modes`
=> CLN: moving_average_test

tools/run_docker.sh
Third times a charm. Though I don't think this will fix #387 it is a better implementation anyway as suggested by @facaiy
=> Install python3.6 only when testing with python3

README.md, tensorflow_addons/seq2seq/README.md
Let me know if I missed something.
=> Adding @guillaumekln to the seq2seq maintainers list

tensorflow_addons/image/interpolate_spline_test.py, tensorflow_addons/image/sparse_image_warp_test.py
Make tests compatible with graph and eager modes.
=> [image/sparse_image_warp] make tests compatible with graph and eager modes

tensorflow_addons/custom_ops/image/BUILD, tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op.cc, tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op.h, tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op_gpu.cu.cc
Finally, the last gpu kernel :-)
=> [image/distance_transform] build gpu kernel

.travis.yml, README.md, tools/ci_build/builds/release_linux.sh
Closes #449 and #447 
Tested using our pypi test build `pip install --index-url https://test.pypi.org/simple/ tfa-nightly`
Output of Correlation Cost Layer (With `tf-nightly-gpu-2.0-preview`)
```
2019-08-28 11:02:04.075147: I tensorflow/core/common_runtime/eager/execute.cc:568] Executing op Cast in device /job:localhost/replica:0/task:0/device:GPU:0
2019-08-28 11:02:04.768506: I tensorflow/core/common_runtime/eager/execute.cc:568] Executing op __inference_correlation_cost_13 in device /job:localhost/replica:0/task:0/device:GPU:0
input_a: (_Arg): /job:localhost/replica:0/task:0/device:GPU:0
2019-08-28 11:02:04.769124: I tensorflow/core/common_runtime/placer.cc:54] input_a: (_Arg): /job:localhost/replica:0/task:0/device:GPU:0
input_b: (_Arg): /job:localhost/replica:0/task:0/device:GPU:0 …
```
=> BLD: Package GPU Ops

tensorflow_addons/version.py
we need to increase version for tfa-nightly
=> BLD: increase minor version after 0.5.0 release

tensorflow_addons/metrics/f1_test.py, tensorflow_addons/metrics/f_scores.py, tensorflow_addons/metrics/fbeta_test.py
=> Adding sample weight param to f1 score

README.md, setup.py, tensorflow_addons/__init__.py
=> BLD: add tf 2.0 dependency for addons

examples/image_ops.ipynb, examples/layers_normalizations.ipynb, examples/layers_weightnormalization.ipynb, examples/losses_triplet.ipynb, examples/optimizers_lazyadam.ipynb, examples/template.ipynb
Updated versions. 
Had a strange issue trying to save these to a branch from Colab which I'll bring up at this months meeting
=> DOC: update examples

.github/ISSUE_TEMPLATE/bug-performance-report.md, .github/ISSUE_TEMPLATE/feature-request.md
Improvements based on the information we actually require. Happy to make some changes to this if there are other thoughts.
=> Improve issue templates

README.md, setup.py, tensorflow_addons/__init__.py
cherry-pick for 0.5.1
* BLD: add tf dependency for addons
* DOC: remove note in readme
* BLD: support tfa-nightly
* BLD: pin to 2.0.0-rc0
=> BLD: add tf 2.0 dependency for addons (#474)

tensorflow_addons/optimizers/rectified_adam.py
Remove the add operator between assignments.
=> Fix group operator for RectifiedAdam

tensorflow_addons/image/filters.py
=> Efficient operation

tensorflow_addons/custom_ops/activations/BUILD, tensorflow_addons/custom_ops/image/BUILD, tensorflow_addons/custom_ops/layers/BUILD, tensorflow_addons/custom_ops/seq2seq/BUILD
=> Cherry-pick to r0.5: Link to cudart_static and remove cuda_libs

build_deps/requirements.txt, build_deps/requirements_gpu.txt, setup.py, tensorflow_addons/version.py, tools/ci_build/pylintrc
=> RELEASE: 0.5.2

docs/tutorials/losses_triplet.ipynb
In order to have a good picture with https://projector.tensorflow.org/
=> Remove shuffling for the test dataset

tensorflow_addons/activations/README.md, tensorflow_addons/callbacks/README.md, tensorflow_addons/layers/README.md, tensorflow_addons/losses/README.md, tensorflow_addons/metrics/README.md, tensorflow_addons/rnn/README.md, tensorflow_addons/seq2seq/README.md
=> correct link

MIGRATED_TO_CORE.md
=> DOC: Add migration documentation

configure.sh
Per https://groups.google.com/a/tensorflow.org/forum/#!topic/addons/2sS8FqhhU2w
=> BLD: always install the latest tf in configure.sh

build_deps/requirements.txt, setup.py
Quick temp fix while we wait for https://github.com/tensorflow/tensorflow/pull/33353 to merge
=> Temporarily pin protobuf to return CI

setup.py
Closes #454 . As of now there are should be no breaking changes. If that changes we'll need to update this.
=> Pin to greater than tensorflow core

build_deps/requirements.txt
=> Revert requirements patch

tensorflow_addons/image/transform_ops.py
=> Minor correction

tensorflow_addons/optimizers/lookahead.py, tensorflow_addons/optimizers/lookahead_test.py, tensorflow_addons/optimizers/moving_average.py, tensorflow_addons/optimizers/moving_average_test.py
=> Add lr setters/getters to optimizer wrappers

tensorflow_addons/layers/optical_flow.py, tensorflow_addons/layers/optical_flow_test.py
Nightly breaks when passing list to predict. No reason this test should have been doing that.
=> FIX: pass numpy arrays to keras model

tensorflow_addons/optimizers/lookahead.py, tensorflow_addons/optimizers/moving_average.py
This PR fix the redundant part of getter and setter in `lr` (it recommended to use `learning_rate`).
=> Refactoring learning rate (lr)

tensorflow_addons/layers/wrappers.py, tensorflow_addons/rnn/cell.py
Update [deprecated  API](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/engine/base_layer.py#L1697)
=> update deprecated API

docs/tutorials/tqdm_progress_bar.ipynb
@seanpmorgan I found a small typo in the tqdm_progress_bar.ipynb in the "Run in Colab" and "Download Notebook" link, here is a quick fix. Thank you so much for your time!
Edit: typo
=> [Small typo] fixed typo in tqdm_progress_bar colab tutorial

docs/tutorials/_toc.yaml
Just a quick update of _toc.yaml for the path to TQDM Progress Bar, thanks!
=> update _toc.yaml with path to TQDM Progress Bar colab

tensorflow_addons/optimizers/lookahead_test.py
=> Set random seed for TensorFlow to make test reproducible 

tensorflow_addons/metrics/BUILD, tensorflow_addons/metrics/README.md, tensorflow_addons/metrics/__init__.py, tensorflow_addons/metrics/matthews_correlation_coefficient.py, tensorflow_addons/metrics/matthews_correlation_coefficient_test.py
This is still in progress about (https://github.com/tensorflow/addons/issues/457). I'm trying to use colab to compare&test to make sure the correctness.
=> MatthewsCorrelationCoefficient 

LICENSE
Restore Apache license, Ref: http://www.apache.org/dev/apply-license.html#new
We should not modify the license file, another reference: kubernetes/kubernetes@d30db1f
=> Remove copyright notice

build_deps/requirements.txt
Checking https://github.com/tensorflow/tensorflow/commit/f6a40276a1eaa472b25e87a6371310bc80e3fb56 fix
=> Revert pinned nightly

tensorflow_addons/optimizers/conditional_gradient.py, tensorflow_addons/optimizers/lamb.py, tensorflow_addons/optimizers/lazy_adam.py, tensorflow_addons/optimizers/rectified_adam.py
- Follow https://github.com/tensorflow/tensorflow/commit/f5866078ee935cad8e0be0879316c22fdd379777.
- Some nit on documentation.
=> Update documentation of optimizers

tensorflow_addons/custom_ops/text/BUILD, tensorflow_addons/text/BUILD, tensorflow_addons/text/__init__.py
PR to merge after #663 is fixed.
=> Revert "Don't build parse_time till TF r2.1 (#710)"

tensorflow_addons/custom_ops/text/cc/kernels/skip_gram_kernels.cc
[Log with warning](https://source.cloud.google.com/results/invocations/43e9a131-498d-4e01-80c5-6100c2c82313/targets/tensorflow_addons%2Fubuntu%2Fgpu%2Fpy2%2Fpresubmit/log).
=> Prevent warning of signed-unsigned comparison

.travis.yml, tools/ci_build/builds/release_macos.sh
Fix issues found in today's nightly build
=> BLD: fix release

.travis.yml, build_pip_pkg.sh, tools/ci_build/builds/wheel_verify.sh
Last fix... should have ran through travis the first time around. But now fully works:
https://travis-ci.org/seanpmorgan/addons/builds/622164041
=> BLD: fix release nightly

setup.py
Should wait for #730 to merge prior.
=> Consolidate pip packages now that TF2.1 supports GPU and CPU

tensorflow_addons/optimizers/moving_average.py
=> Removing int check in moving average

CONTRIBUTING.md
According to @seanpmorgan s comment on gitter I improved the descrition on how to run individual tests.
=> Small update on how to run individual tests

tensorflow_addons/layers/wrappers.py, tensorflow_addons/layers/wrappers_test.py
=> Add WeightNorm support for RNNs

CONTRIBUTING.md, tools/ci_testing/addons_gpu.sh, tools/ci_testing/parallel_gpu_execute.sh
=> run gpu tests in parallel

tensorflow_addons/seq2seq/attention_wrapper_test.py
Temporary hotfix for failing nightly test to return CI.
See #781
=> Skip failing tests

tensorflow_addons/text/crf.py
fixes https://github.com/tensorflow/addons/issues/778, where sequences of true length 1 got positive likelihood
=> fix crf for sequences of length 1

tensorflow_addons/text/crf.py, tensorflow_addons/text/crf_test.py
Replacement for #697 
Fixes #694
=> FIX: Add unknown seq-len support for CRF functions

tensorflow_addons/losses/lifted.py, tensorflow_addons/losses/lifted_test.py, tensorflow_addons/losses/triplet.py, tensorflow_addons/losses/triplet_test.py
=> FIX: Add kwargs to loss to prevent serialize error

Broken_Template.ipynb
=> Temporarily add broken tutorial for testing

tensorflow_addons/layers/BUILD
=> Mark wrappers test as flaky

.github/boring-cyborg.yml
This will automatically label PR's based on what files they modify. Recently created by the Apache AirFlow team:
https://github.com/kaxil/boring-cyborg
=> Add config for labeler

docs/tutorials/temp_broken_tutorial.ipynb
For verification as part of #768
=> Add broken tutorial do docs for testing verification

README.md
Waiting on #847 merge and release.
=> DOC: Update build matrix

tensorflow_addons/version.py
Waiting for #847 merge and release.
=> Increment minor version to 0.8

.github/workflows/ci_test.yml
https://github.com/tensorflow/addons/issues/852
=> sanity checks for Github Actions

tensorflow_addons/custom_ops/activations/cc/kernels/gelu_op.h, tensorflow_addons/custom_ops/image/cc/kernels/adjust_hsv_in_yiq_op.h, tensorflow_addons/custom_ops/text/cc/kernels/skip_gram_kernels.cc, tensorflow_addons/tensorflow_addons.bzl
=> CLN: define _USE_MATH_DEFINES for windows build

.gitignore
To avoid pushing it in the future, see #889
=> Added the buildifier to the gitignore.

tensorflow_addons/losses/focal_loss.py, tensorflow_addons/losses/focal_loss_test.py
Address #876. This is the same with #298.
=> FIX: sigmoid focal cross entropy model compile

tensorflow_addons/callbacks/time_stopping.py, tensorflow_addons/callbacks/tqdm_progress_bar.py, tensorflow_addons/layers/gelu.py, tensorflow_addons/layers/maxout.py, tensorflow_addons/layers/normalizations.py, tensorflow_addons/layers/optical_flow.py, tensorflow_addons/layers/poincare.py, tensorflow_addons/layers/sparsemax.py, tensorflow_addons/layers/tlu.py, tensorflow_addons/layers/wrappers.py, tensorflow_addons/losses/contrastive.py, tensorflow_addons/losses/focal_loss.py, tensorflow_addons/losses/lifted.py, tensorflow_addons/losses/quantiles.py, tensorflow_addons/losses/sparsemax_loss.py, tensorflow_addons/losses/triplet.py, tensorflow_addons/metrics/cohens_kappa.py, tensorflow_addons/metrics/f_scores.py, tensorflow_addons/metrics/matthews_correlation_coefficient.py, tensorflow_addons/metrics/multilabel_confusion_matrix.py, tensorflow_addons/metrics/utils.py, tensorflow_addons/optimizers/average_wrapper.py, tensorflow_addons/optimizers/conditional_gradient.py, tensorflow_addons/optimizers/lookahead.py, tensorflow_addons/optimizers/moving_average.py, tensorflow_addons/optimizers/stochastic_weight_averaging.py, tensorflow_addons/rnn/cell.py, tensorflow_addons/seq2seq/attention_wrapper.py
Idea proposed by @ulf1 in #743
=> Used dict expension.

tensorflow_addons/__init__.py
=> Fix deletion of futures.

.github/workflows/ci_test.yml
I don't know how to fix the Windows one though.
=> Fix the macos build.

docs/tutorials/_template.ipynb, docs/tutorials/image_ops.ipynb, docs/tutorials/layers_normalizations.ipynb, docs/tutorials/layers_weightnormalization.ipynb, docs/tutorials/losses_triplet.ipynb, docs/tutorials/networks_seq2seq_nmt.ipynb, docs/tutorials/optimizers_conditionalgradient.ipynb, docs/tutorials/optimizers_lazyadam.ipynb, docs/tutorials/time_stopping.ipynb, docs/tutorials/tqdm_progress_bar.ipynb
V2 of #895
I didn't find any better way of being diff friendly than than to edit the json directly :(
=> Removing unused imports, cells and __future__ from the notebooks.

.github/workflows/ci_test.yml, .github/workflows/windows_nightly.yml
Switch to bash to address #909.
=> Switch windows shell to bash

CONTRIBUTING.md
I made this guide a few weeks ago, we added it to the CONTRIBUTING section of keras tuner and autokeras. I think it's helpful for people who don't know where to start.
=> Added a guide for open-source beginners.

.github/CODEOWNERS, README.md
As per conversation with @seanpmorgan, I would like to add my handle to the list of contacts for callbacks sub-package maintainer, thanks!
=> adding shun's github handle to callback maintainers list

README.md
* Remove py3 from test status
* Add tfa-nightly to linux build matrix
=> DOC: Update central README

tensorflow_addons/optimizers/__init__.py, tensorflow_addons/version.py
Prepping for a 0.7.1 release
(cherry picked from commit 0a23fd2dc41be4725da27e8f68ddfb71cef72bc1)
=> Fix Yogi import (#875) on r0.7 branch

README.md
* DOC: Add style badge
* DOC: Update nightly build matrix
=> DOC: Update central README 

.github/workflows/ci_test.yml, .github/workflows/macos_nightly.yml, .github/workflows/release.yml, .github/workflows/ubuntu_nightly.yml, .github/workflows/windows_nightly.yml, tools/ci_build/builds/release_macos.sh, tools/ci_build/builds/wheel_verify.sh
Expected this to take an iteration or two...
* Windows failed due to not specifying bash as shell
* Mac failed due to using pyenv (this PR replaces with build matrix)
* Linux failed due to pypa action not picking up the token correctly
=> BLD: Fix github actions build

.flake8, tensorflow_addons/losses/focal_loss_test.py, tensorflow_addons/optimizers/moving_average.py, tensorflow_addons/optimizers/stochastic_weight_averaging.py
Those rules will be handled by black in the future. I've done it manually because black isn't applied to all files yet.
=> Enabling some flake8 rules

.github/workflows/macos_nightly.yml, .github/workflows/ubuntu_nightly.yml, .github/workflows/windows_nightly.yml
Hacky way to get another run in tonight.
=> Modify cron times for debug

tensorflow_addons/optimizers/lazy_adam.py, tensorflow_addons/optimizers/novograd.py, tensorflow_addons/optimizers/rectified_adam.py
=> Optimizer typing

configure.py
=> Clean up of configure.py

configure.py
Trying to improve the readability of configure.py, one step at a time.
=> Refactoring of configure.py

tensorflow_addons/utils/BUILD
=> Add new util file to BUILD

docs/tutorials/losses_triplet.ipynb
Addresses #983. Accidentally modified in
https://github.com/tensorflow/addons/pull/908/files#diff-56e3fae32a6d8542708571f3cf697d79R202
=> DOC: triplet loss tutorial json format

tensorflow_addons/custom_ops/image/cc/kernels/adjust_hsv_in_yiq_op.cc, tensorflow_addons/custom_ops/image/cc/kernels/connected_components.cc, tensorflow_addons/custom_ops/image/cc/kernels/resampler_ops.cc, tensorflow_addons/custom_ops/layers/cc/kernels/correlation_cost_op.cc, tensorflow_addons/custom_ops/seq2seq/cc/kernels/beam_search_ops.cc
=> replace Shard with ParallelFor

pyproject.toml, setup.py, tensorflow_addons/activations/gelu.py, tensorflow_addons/activations/gelu_test.py, tensorflow_addons/callbacks/tqdm_progress_bar.py
=> Used black on some files which are not being worked on.

pyproject.toml, tensorflow_addons/image/sparse_image_warp.py, tensorflow_addons/image/sparse_image_warp_test.py, tensorflow_addons/layers/gelu.py, tensorflow_addons/layers/gelu_test.py, tensorflow_addons/layers/maxout.py, tensorflow_addons/layers/maxout_test.py, tensorflow_addons/layers/optical_flow.py, tensorflow_addons/layers/optical_flow_test.py, tensorflow_addons/losses/focal_loss_test.py, tensorflow_addons/metrics/matthews_correlation_coefficient_test.py, tensorflow_addons/metrics/multilabel_confusion_matrix_test.py, tensorflow_addons/metrics/r_square_test.py, tensorflow_addons/optimizers/lamb.py, tensorflow_addons/optimizers/lamb_test.py, tensorflow_addons/seq2seq/attention_wrapper.py
=> Used black on some more files not being worked on.

.github/workflows/ci_test.yml, CONTRIBUTING.md, makefile, tools/ci_build/install/install_ci_dependency.sh
=> Clean up of the sanity check.

docs/tutorials/networks_seq2seq_nmt.ipynb
The current version has the following updates:
- Dataset integration verified
- Attention mechanism added
- tfa.seq2seq is used
Solves queries added in #986
=> Updated the Tutorial

tensorflow_addons/metrics/cohens_kappa.py, tensorflow_addons/metrics/f_scores.py, tensorflow_addons/metrics/utils.py, tensorflow_addons/rnn/cell_test.py, tensorflow_addons/seq2seq/attention_wrapper.py, tensorflow_addons/seq2seq/sampler.py, tensorflow_addons/utils/types.py, tools/ci_build/verify/check_typing_info.py
See https://github.com/tensorflow/tensorflow/blob/dea01bb56459c35b77730ff1261c6306b75314d4/tensorflow/python/framework/dtypes.py#L607 for the type of dtype.
I don't usually like to do multiple things in the same pull request but here I am... :p
=> Added type of dtype and fix unused parameter and fix broken master branch

docs/tutorials/_toc.yaml, tools/docs/build_docs.py
Add seq2seq to TOC and fix the api-generator.
=> Add seq2seq to TOC and fix the api-generator.

pyproject.toml, tensorflow_addons/metrics/cohens_kappa_test.py, tensorflow_addons/optimizers/lookahead_test.py, tensorflow_addons/optimizers/moving_average_test.py, tensorflow_addons/optimizers/weight_decay_optimizers_test.py, tensorflow_addons/rnn/cell.py, tensorflow_addons/rnn/cell_test.py
=> Used black on other unused files.

tensorflow_addons/version.py
Release process is extremely simple now. After merging I'll publish a release and after confirming it all works I'll update https://github.com/tensorflow/community/blob/master/sigs/addons/RELEASE.md
=> Remove dev from r0.8 branch

.github/workflows/release.yml
Will cherry pick this onto r0.8 after merge
=> Add env variables to windows release

pyproject.toml, tensorflow_addons/image/distance_transform_test.py, tensorflow_addons/optimizers/lazy_adam_test.py
=> run black on /image/distance_transform_test.py and optimizers/lazy_adam_test.py

README.md
Was waiting to drop python2 to add this.
=> DOC: Add pyversions badge

.github/workflows/ci_test.yml, tools/ci_build/verify/check_typing_info.py, tools/docker/sanity_check.Dockerfile
Having a TODO list of functions/classes to be typed is very useful, and I'd like to be able to use it in autokeras. See https://github.com/keras-team/autokeras/issues/918 . I moved the code in an external repository to avoid code duplication.
=> Used an external repo to check that the API is typed.

pyproject.toml, tensorflow_addons/activations/rrelu.py, tensorflow_addons/activations/rrelu_test.py, tensorflow_addons/image/filters.py, tensorflow_addons/image/filters_test.py
related to https://github.com/tensorflow/addons/issues/988
=> Black rrelu.py filter.py with their associated test

configure.py
I believe this file needs a bit of a refactoring. By putting the code in classes it's more readable and we'll be able to import it from other files.
Sorry for the big diff. It's mostly an indent change. I didn't change any code except from the following variables being moved:
```python
_TF_NEED_CUDA = os.getenv("TF_NEED_CUDA")
_TF_CUDA_VERSION = os.getenv("TF_CUDA_VERSION")
_CUDA_TOOLKIT_PATH = os.getenv("CUDA_TOOLKIT_PATH")
_TF_CUDNN_VERSION = os.getenv("TF_CUDNN_VERSION")
_CUDNN_INSTALL_PATH = os.getenv("CUDNN_INSTALL_PATH")
```
=> Moved all the code in configure.py in a function.

tools/pre-commit.sh, tools/run_build.sh, tools/run_cpu_tests.sh, tools/run_google_cloud_tests.sh, tools/run_gpu_tests.sh, tools/run_sanity_check.sh
=> Respect the DOCKER_BUILDKIT env variable in all scripts.

tensorflow_addons/seq2seq/attention_wrapper_test.py
The tests should now pass. Let's see what the CI is saying.
Fixes #781.
=> Re-enable Luong monotonic tests

tensorflow_addons/utils/types.py
Add tf.Variable into TensorLike type (`tensorflow_addons/utils/types.py`)
=> Add tf.Variable into TensorLike type

.github/workflows/backport.yml
Fix #1072
@seanpmorgan I'll send you the BOT_TOKEN by email. You don't have to set the GITHUB_TOKEN . It's automatic.
You can look at the folks of https://github.com/qgis/QGIS who are making heavy use of this bot.
You need to add a label to the PR you want to backport: e.g. https://github.com/qgis/QGIS/pull/34436
See https://github.com/marketplace/actions/backport-bot
=> Add a backport bot.

tools/docs/doc_requirements.txt
Discussion at https://github.com/tensorflow/addons/pull/1096#discussion_r380382137
=> remove pathlib

.github/workflows/ci_test.yml, .github/workflows/macos_nightly.yml, .github/workflows/manylinux_nightly.yml, .github/workflows/release.yml, .github/workflows/windows_nightly.yml
To fix the bug we had in https://github.com/tensorflow/addons/pull/1111
=> Used v2 of actions/checkout

tools/docker/gpu_tests.Dockerfile
=> Used the official supported docker image for the gpu tests

.github/workflows/ci_test.yml, .github/workflows/release.yml
=> We now test the release code at each commit.

build_deps/build-requirements-cpu.txt, tools/docker/cpu_tests.Dockerfile, tools/docker/sanity_check.Dockerfile
=> Grouped the versions for tensorflow-cpu.

.github/workflows/release.yml
Part of #1116
We still need to change the nightly build.
=> Used the official tf gpu image.

tensorflow_addons/activations/mish.py, tensorflow_addons/activations/mish_test.py
=> Added python implementation for mish

tensorflow_addons/activations/softshrink.py, tensorflow_addons/activations/softshrink_test.py
=> Add python implementation of softshrink

tensorflow_addons/activations/lisht.py, tensorflow_addons/activations/lisht_test.py
=> Added pure python implementation of lisht

docs/tutorials/average_optimizers_callback.ipynb
=> Average Callback and Optimizers example 

tensorflow_addons/layers/wrappers_test.py
37.3 -> 27.7s
related to [1143](https://github.com/tensorflow/addons/issues/1143)
=> [Test] Speed up layers_wrappers_test

tensorflow_addons/version.py
=> Update 0.8.3 version

.github/workflows/release.yml, tools/ci_build/builds/release_linux.sh
=> Make release_linux.sh configurable for python version

.github/workflows/make_wheel_Linux.sh, .github/workflows/make_wheel_Windows.sh, .github/workflows/make_wheel_macOS.sh, .github/workflows/release.yml
Some refactoring to help with future changes.
=> Use matrix for building.

tensorflow_addons/activations/activations_test.py, tensorflow_addons/activations/sparsemax.py
=> fix activations test

.github/workflows/release.yml, setup.py
=> Upload the nightlies at every commit

docs/tutorials/networks_seq2seq_nmt.ipynb, tensorflow_addons/optimizers/weight_decay_optimizers.py
=> Change H1 subheadings to H2 and delete unused styles.

tensorflow_addons/metrics/hamming_test.py
Related to #1200 but does not fix it. It's just enable some correct tests in the CI
=> Enable 2 tests out of 6 in hamming_test.py

tensorflow_addons/layers/BUILD, tensorflow_addons/layers/wrappers.py, tensorflow_addons/layers/wrappers_test.py
=> fix wrapper test

.github/workflows/make_wheel_Linux.sh, .github/workflows/make_wheel_macOS.sh
=> No need for a for loop when repairing wheels

tools/ci_testing/addons_cpu.sh, tools/ci_testing/addons_gpu.sh, tools/tests_dependencies/pytest.txt
See https://github.com/tensorflow/addons/pull/1243#issuecomment-596510466 
Fix the broken master branch.
=> Remove code coverage from the CI.

docs/build_docs.py
=> Small docstring fix for doc gen

CONTRIBUTING.md, README.md
Time to give the future contributors some love!
=> Some more ways of contributing.

CONTRIBUTING.md, tensorflow_addons/register_test.py
More and more love for the contributors.
=> Added more info in the CONTRIBUTING.md

.github/workflows/ci_test.yml, tools/docker/cpu_tests.Dockerfile
testing the tests to test the test  script because we don't have enough tests
Fix #1283
=> Added tests for minimal cpu tests.

.github/CODEOWNERS
Following up on maintainership email
=> Adopt triplet loss

configure.py
Pull variables which have the same purpose into a separate function for better readability.
=> Less free variables in the configure.py for better readability.

CONTRIBUTING.md
I tried to make the process as logical as possible. From easiest to hardest in the workflows.
1) Docker only tests
2) Locall dev with python only
3) IDE use
4) Compiling custom ops
5) Work interactively in docker
6) For googlers: run with bazel
=> Improving the contributing.md

configure.py
=> Simplify configure.py

setup.py
Everything is in functions now, which should help with readability.
=> Refactoring the setup.py for better readability

configure.py
It's easier to read and modify.
=> Isolated the logic concerning fetching the paths in configure.py

.github/CODEOWNERS
Hi @AakashKumarNain not sure how this was missed when we updated the CODEOWNERS. Want to confirm that you're still willing to maintain?
=> Update cohens kappa maintainer

README.md
=> Strict version requirements for build matrix

tensorflow_addons/losses/giou_loss.py
cc @gabrieldemarmiesse .
Related #1324.
=> use loss wrapper

tensorflow_addons/image/compose_ops_test.py
See #1328
@abhichou4 could you review if you have the time? Thank you!
=> Used pytest instead of tf.test.TestCase in blending tests

tensorflow_addons/layers/optical_flow_test.py
=> Moving the function out of the class.

tensorflow_addons/image/__init__.py, tensorflow_addons/image/transform_ops.py, tensorflow_addons/image/transform_ops_test.py, tensorflow_addons/image/translate_ops.py, tensorflow_addons/image/translate_ops_test.py, tensorflow_addons/image/utils.py, tools/install_deps/pytest.txt
=> Added helper ops, translate, shear

tensorflow_addons/layers/poincare_test.py
See #1328 
So practically only a few things changed. It's just that the indentation makes the diff hard to read. self.assert* are becoming assert and I renamed the functions and added the fixture.
=> Removed run_all_in_eager_and_graph_mode from pointcare_test.

tensorflow_addons/utils/keras_utils_test.py
=> Use pytest functions instead of classes in keras_utils_test.py

tensorflow_addons/seq2seq/beam_search_decoder_test.py
Same as #1367 
It's mostly just a call to a custom op so no need to test with graph mode.
=> test gather_tree_from_array in eager mode only.

tensorflow_addons/seq2seq/beam_search_decoder_test.py
The function is simple enough so that we don't have to test in graph mode.
=> Test eos masking in eager mode only.

tensorflow_addons/seq2seq/beam_search_ops_test.py
I the future, for gpu tests, I believe we'll make a fixture that will run some selected tests multiple times. And then we can skip some if we see that no gpu is available.
=> Use eager mode for a gather tree test because it's only a custom op.

tensorflow_addons/seq2seq/loss_test.py
Follow-up on #1374 
@guillaumekln
=> Test ambiguous order in eager mode.

tensorflow_addons/seq2seq/loss_test.py
Follow-up on #1374 
cc @guillaumekln
=> Moved test_sequence_loss outside the run_all_in_graph_and_eager_mode.

tensorflow_addons/seq2seq/loss_test.py
=> Moved test_sequence_loss outside run_all_in_graph_and_eager_mode.

tensorflow_addons/seq2seq/loss_test.py
=> Migrated some tests out of run_all_in_graph_and_eager_mode in seq2seq

tensorflow_addons/text/skip_gram_ops_test.py
=> Moved code out of tf.test.TestCase in skip_gram_ops_test.py

tensorflow_addons/seq2seq/loss_test.py
=> Removed the run_all_in_graph_and_eager_mode from the testsumreduction.

tensorflow_addons/activations/sparsemax_test.py
=> Moving out of tf.test.TestCase in sparsemax_test.py

tensorflow_addons/layers/netvlad_test.py
=> Removed test_utils.run_all_in_graph_and_eager_modes in netvlad_test.py

tensorflow_addons/activations/activations_test.py
=> Removed run_all_in_graph_and_eager_modes from activation_test.py

tensorflow_addons/activations/gelu_test.py
=> Moved a function out of run_all_in_eager_and_graph_mode in gelu tests.

tensorflow_addons/activations/hardshrink_test.py
=> Move test out of run_all_in... well you get the idea :)

tensorflow_addons/activations/lisht_test.py
=> Moved test out of run_in_graph_and_eager_mode in lisht.

tensorflow_addons/activations/sparsemax_test.py
=> Move test out of run_in_graph_and_eager_mode in sparsemax.

tensorflow_addons/activations/softshrink_test.py
=> Moved test out of run_in_graph_and_eager_mode in softshrink.

tensorflow_addons/activations/hardshrink_test.py
=> Move test out of run_in_graph_and_eager_mode in hardshrink.

tensorflow_addons/activations/mish_test.py
=> Moved test out of run_all_in_graph_and _eager_mode in mish.

tensorflow_addons/activations/softshrink_test.py
=> Moved test out of run_all_in_graph_and_eager_mode in softshrink.

tensorflow_addons/activations/rrelu_test.py
=> Moved test out of run_all_in_graph_and_eager_mode in rrelu.

tensorflow_addons/activations/gelu_test.py
=> Moved functions in gelu_test.py out of the run_all_in_graph_and_eager_mode.

tensorflow_addons/activations/mish_test.py
=> Moved tests out of run_in_graph_and_eager_mode in mish.

tensorflow_addons/activations/sparsemax_test.py
=> Moved test out of run_in_graph_and_eager_mode in sparsemax.

tensorflow_addons/image/connected_components_test.py
=> Moved tests out of run_in_graph_and_eager_mode in connected components.

tensorflow_addons/image/dense_image_warp_test.py
=> Moved test out of run_in_graph_and_eager_mode in dense_image_warp.

tensorflow_addons/layers/wrappers_test.py
=> Moved test out of run_in_graph_and_eager_mode in wrapper.

tensorflow_addons/activations/hardshrink_test.py
=> Moved test out of run all in graph and eager mode in hardshrink.

tensorflow_addons/activations/rrelu_test.py
=> Moved test out of run_in_graph_and_eager_mode n rrelu.

tensorflow_addons/losses/focal_loss_test.py
=> Removed run_all_in_graph_and_eager_mode in focal_loss_test.py

tensorflow_addons/image/filters_test.py
=> move filter tests out of 'run_all_in_graph_and_eager_modes' 

tensorflow_addons/losses/giou_loss_test.py
=> Moved test out of run_in_graph_and_eager_mode in giou

tensorflow_addons/losses/metric_test.py
=> Removed run_in_graph_and_eager_mode from the pairwise_distance tests.

tensorflow_addons/image/distance_transform_test.py
=> Moved test out of run_in_graph_and_eager_mode in distance_transform.

tensorflow_addons/image/dense_image_warp_test.py
=> Moved function out of run_in_graph_and_eager_mode in dense_image_wrap

tensorflow_addons/image/distort_image_ops_test.py
=> Moved tests out of run_in_graph_and_eager_mode in distort_image.

tensorflow_addons/layers/wrappers_test.py
=> Moved tests out of run_in_graph_and_eager_mode in wrappers tests.

tensorflow_addons/image/sparse_image_warp_test.py
=> Moved test out of run_all_in_graph_and_eager_mode sparse_image_wrap.

tensorflow_addons/losses/contrastive_test.py
=> Moved tests out of run_in_graph_and_eager_mode in contrastive_test

tensorflow_addons/losses/quantiles_test.py
=> Moved tests out of run_in_graph_and_eager_mode in quantilies_test

tensorflow_addons/image/utils_test.py
=> Move test out of run_all_in_graph_and_eager_mode in utils_test

tensorflow_addons/image/dense_image_warp_test.py
=> Moved test out of run_in_graph_and_eager_mode in dense_image_warp

tensorflow_addons/image/interpolate_spline_test.py
=> Moved tests out of run_in_graph_and_eager_mode in interploate_spline

tensorflow_addons/image/utils_test.py
=> Move test out of run_all_in_graph_and_eager_mode in utils_test.py

tensorflow_addons/image/interpolate_spline_test.py
=> Moved test out of run_in_graph_and_eager_mode in interpolate_spline_test.py

tensorflow_addons/image/sparse_image_warp_test.py
=> Moved test out of run_all_in_graph_and_eager_mode sparse_image_warp_test

tensorflow_addons/image/sparse_image_warp_test.py
=> Moved test out of run_all_in_graph_and_eager_mode sparse_image_warp

tensorflow_addons/losses/contrastive_test.py
=> Fixing the gpu build.

tensorflow_addons/layers/gelu_test.py
=> Removed run_in_graph_and_eager_mode in gelu_test.py

tensorflow_addons/layers/multihead_attention_test.py
=> Moved tests out of run_in_graph_and_eager_mode in multithread attendion

tensorflow_addons/layers/multihead_attention_test.py
=> Moved tests out of run_in_graph_and_eager_mode in multithread attention

tensorflow_addons/layers/normalizations_test.py
=> Moved some tests out of run_in_graph_and_eager_mode in normalization

setup.py
Attempting for GitHub "used-by" to utilize `tensorflow-addons`
=> Re-order variable declaration for GitHub "Used By" feature

tensorflow_addons/layers/normalizations_test.py
=> Moved tests out of run_in_graph_and_eager_mode in normalizatoin_test

tensorflow_addons/image/sparse_image_warp_test.py
=> Moved tests out of run_in_graph_and_eager_mode in sparse_image_warp_test

tensorflow_addons/layers/sparsemax_test.py
=> Moved tests out of run_in_graph_and_eager_mode in sparsemax_test

tensorflow_addons/layers/normalizations_test.py
=> Moved tests out of run_in_graph_and_eager_mode in normalizations

tensorflow_addons/layers/normalizations_test.py
=> Move test out of run_all_in_graph_and_eager_mode in normalizations_test

tensorflow_addons/layers/wrappers_test.py
=> Moved tests out of run_in_graph_and_eager_mode in wrappers

tensorflow_addons/layers/wrappers_test.py
=> Moved test out run_in_graph_and_eager_mode in wrapper

tensorflow_addons/layers/wrappers_test.py
=> Moved tests out of run_in_graph_and_eager_mode in wrapers_test

tensorflow_addons/layers/normalizations_test.py
cc @gabrieldemarmiesse. This may complete the normalization test.
=> Removed run_in_graph_and_eager_mode in normalization_test

tensorflow_addons/losses/contrastive_test.py
=> Removed run_in_graph_and_eager_mode in contrastive_test

tensorflow_addons/metrics/BUILD, tensorflow_addons/metrics/README.md, tensorflow_addons/metrics/cohens_kappa_test.py, tensorflow_addons/metrics/f_test.py, tensorflow_addons/metrics/hamming_test.py, tensorflow_addons/metrics/matthews_correlation_coefficient_test.py, tensorflow_addons/metrics/metrics_test.py, tensorflow_addons/metrics/multilabel_confusion_matrix_test.py, tensorflow_addons/metrics/r_square_test.py, tensorflow_addons/metrics/run_all_test.py
=> Remove the need of declaring the metrics tests in the BUILD.

tensorflow_addons/text/BUILD, tensorflow_addons/text/README.md, tensorflow_addons/text/crf_test.py, tensorflow_addons/text/parse_time_op_test.py, tensorflow_addons/text/run_all_test.py, tensorflow_addons/text/skip_gram_ops_test.py
cc @gabrieldemarmiesse and @seanpmorgan
=> Remove the need to declare text tests in BUILD

tensorflow_addons/losses/triplet_test.py
=> Moved test out of run_in_graph_and_eager_mode in triplet_test

tensorflow_addons/optimizers/conditional_gradient_test.py
=> Moved test out of run_in_graph_and_eager_mode in conditional_gradient

tensorflow_addons/image/interpolate_spline_test.py
=> Reoved tests out of run_in_graph_and_eager_mode in interpolate spline

tensorflow_addons/image/distance_transform_test.py
=> Moved tests out of run_in_graph_and_eager_mode in distance transorm

tensorflow_addons/image/distort_image_ops_test.py
=> Moved tests out of run_in_graph_and_eager_mode in distor image ops

tensorflow_addons/image/connected_components_test.py
=> Moved tests out of run_in_graph_and_eager_mode in connected component

tensorflow_addons/image/sparse_image_warp_test.py
=> Reoved tests out of run_in_graph_and_eager_mode in sparse image warp

.github/workflows/release.yml
=> Trying to fix the release.

tensorflow_addons/rnn/BUILD, tensorflow_addons/rnn/README.md, tensorflow_addons/rnn/cell_test.py, tensorflow_addons/rnn/run_all_test.py
cc @gabrieldemarmiesse, please close this, if it's not necessary since it's only one small test here.
=> To be consistent with other tests in BUILD

tensorflow_addons/image/distort_image_ops_test.py
=> Removed tests out of run_in_graph_and_eager_mode in distor image ops

tensorflow_addons/callbacks/BUILD, tensorflow_addons/callbacks/README.md, tensorflow_addons/callbacks/run_all_test.py, tensorflow_addons/callbacks/tqdm_progress_bar_test.py, tools/install_deps/pytest.txt
Fixes #1500 
This should be merged before #1365 is merged. It contains tests for validation metrics too.
=> Added extensive tests for the tqdm progress bar.

tensorflow_addons/losses/sparsemax_loss_test.py
=> Moved tests out of run_in_graph_and_eager_mode in sparsemax loss

tensorflow_addons/image/resampler_ops_test.py
=> Moved tests out of run_in_graph_and_eager_mode in resampler ops

tensorflow_addons/losses/sparsemax_loss_test.py
=> Removed tests out of run_in_graph_and_eager_mode in sparsemax loss

tensorflow_addons/optimizers/conditional_gradient_test.py
=> Removing tests out of run_in_graph_and_eager_mode in conditional_gradient

tensorflow_addons/optimizers/lamb_test.py
=> Moved test out of run_in_graph_and_eager_mode in lamb test

tensorflow_addons/optimizers/lamb_test.py
=> Moved tests out of run_in_graph_and_eager_mode in lamb

tensorflow_addons/optimizers/lookahead_test.py
=> Removed tests out of run_in_graph_and_eager_mode in lookahead

tensorflow_addons/optimizers/conditional_gradient_test.py
=> Moved tests out of run_in_graph_and_eager_mode in conditional gradient

tensorflow_addons/optimizers/lamb_test.py
=> Removed tests out of run_in_graph_and_eager_mode in lamb test

README.md
We're compatible. We have it running in the CI for windows.
=> Added 3.8 for tf-nightly in the readme.

tensorflow_addons/optimizers/tests/moving_average_test.py
=> Moved tests out of run_in_graph_and_eager_mode in moving average

tensorflow_addons/optimizers/tests/novograd_test.py
=> Moved tests out of run_in_graph_and_eager_mode in novograd

tensorflow_addons/optimizers/tests/cyclical_learning_rate_test.py
There was an attribute error on learning_rate_schedule and an off by one error in the tests. The step size was also doubled.
I also reduced the step size to make the test much faster.
=> Fixed one of the tests in cyclical learning rate.

tensorflow_addons/optimizers/tests/conditional_gradient_test.py
=> Removed tests out of run_in_graph_and_eager_mode in conditional gradient

tensorflow_addons/optimizers/tests/rectified_adam_test.py
=> Removed tests out of run_in_graph_and_eager_mode in recitified adam

tensorflow_addons/version.py
=> Update 0.9 Version for release

.github/workflows/make_wheel_Linux.sh, .github/workflows/release.yml, README.md, setup.py, tools/docker/build_wheel.Dockerfile
Re-trying #1233 with different strategy
=> Unify nightly version number

tensorflow_addons/optimizers/tests/yogi_test.py
cc @gabrieldemarmiesse and @seanpmorgan
=> Removed tests out of run_in_graph_and_eager_mode in yogi test

README.md
=> Fix the build badges on the central README

tensorflow_addons/optimizers/tests/weight_decay_optimizers_test.py
=> Removed tests out of graph mode in weight decay optimizer test

README.md, configure.py
We shouldn't ask for user input, it's source of too many issues in the CI and hurts readability.
=> Fix configure.py (fixes the gpu build hanging).

.github/workflows/make_wheel_macOS.sh, build_deps/build_pip_pkg.sh, build_deps/toolchains/gpu/cuda_configure.bzl, tools/docker/build_wheel.Dockerfile, tools/releases/tf_auditwheel_patch.sh, tools/testing/build_and_run_tests.sh
=> Used python all the time instead of python3.

tensorflow_addons/rnn/tests/cell_test.py
=> Remove run all in eager and graph mode in rnn cell

.flake8, tensorflow_addons/layers/tests/normalizations_test.py, tensorflow_addons/losses/tests/sparsemax_loss_test.py, tensorflow_addons/optimizers/tests/weight_decay_optimizers_test.py, tensorflow_addons/rnn/tests/cell_test.py, tools/install_deps/flake8.txt
We'll remove elements from the exception list progressively.
By adding this check in the CI, that's a check less than reviewers have to do, and it remove iterations cycles.
From what I see in OSS projects, reviewers bandwidth is often the bottleneck, so everything that we can offload to the CI should help.
=> Ensure in the CI that the naming of variables, classes and functions respects pep8

.github/workflows/release-drafter.yml, .github/workflows/release-template.yml
Based on https://github.com/release-drafter/release-drafter as per @seanpmorgan 's suggestion. 
Note that it's very basic, maybe we'd like to verify first that it works well, and then we can incrementally add more things to the release template.
=> Added a simple release template.

CONTRIBUTING.md
* Enforcing docstring
* Strongly suggest to expand or add new tutorials
=> Request samples in CONTRIBUTING.md

tensorflow_addons/seq2seq/tests/decoder_test.py
=> Removed tests out of run_in_graph_and_eager_mode in decoder

tensorflow_addons/text/tests/skip_gram_ops_test.py
cc @gabrieldemarmiesse. This pr also involves `run_deprecated_v1` removal.
=> Removed tests out of run_in_graph_and_eager_mode in skip gram ops

docs/tutorials/_template.ipynb
Change 2019 -> 2020, change small typo of tfo to tfa, remove unnecessary tensorflow version magic as TF 2 is now default.
=> Update year and delete unnecessary tensorflow magic in _template.ipynb

tensorflow_addons/seq2seq/tests/beam_search_ops_test.py
=> Remove tf.test.TestCase in beam search ops

tensorflow_addons/callbacks/tests/avg_model_checkpoint_test.py
Fixes #1502 .  
@gabrieldemarmiesse, @shun-lin and @Squadrick , Please review.
=> Added tests for AverageModelCheckpoint() callback

tensorflow_addons/seq2seq/tests/basic_decoder_test.py
=> Remove tf.test.TestCase in basic decoder

tensorflow_addons/layers/tests/multihead_attention_test.py
=> Removed run_all_in_graph_and_eager_mode in multihead_attention.

tensorflow_addons/seq2seq/tests/beam_search_decoder_test.py
=> Removed run_all_in_graph_and_eager_mode in beam search decoder

tensorflow_addons/metrics/tests/hamming_test.py
Fix #1200
I'm a wizard.
Actually the issue was with a weird usage of tf.session. Now that we run the test in eager mode, it works. (This shows why it's better to mark tests with xfail than skip, because then we know if the test is passing unexpectedly)
=> Fix hamming tests.

tensorflow_addons/image/tests/resampler_ops_test.py
Needs #1677 to be merged first.
=> Removed run_all_in_graph_and_eager_mode from resampler_ops_test.py

tensorflow_addons/optimizers/tests/lazy_adam_test.py
=> Removed a run_deprecated_v1 in lazy adam.

tensorflow_addons/optimizers/tests/lazy_adam_test.py, tensorflow_addons/utils/test_utils.py
Also removed the run_deprecated_v1!
=> Finish the  conversion of lazy adam to pytest.

tools/testing/source_code_test.py
Maybe a better phrasing would help contributors to understand that they shouldn't add elements to those list unless there is an absolute necessity to do so and all other options are impossible to implement.
=> Comments to clarify the purpose of the blacklists in source_code_test.py

tensorflow_addons/text/tests/skip_gram_ops_test.py, tools/testing/source_code_test.py
=> Removed all tf.compat.v1 in skip_gram_ops_test.py

tensorflow_addons/activations/BUILD, tensorflow_addons/callbacks/BUILD, tensorflow_addons/image/BUILD, tensorflow_addons/layers/BUILD, tensorflow_addons/losses/BUILD, tensorflow_addons/optimizers/BUILD, tensorflow_addons/rnn/BUILD, tensorflow_addons/seq2seq/BUILD, tensorflow_addons/text/BUILD
So this is not currently needed but as we expand #992 contributors will run into this issue. See #1728 as an example
=> Add testing dependency for bazel tests

docs/tutorials/_toc.yaml
While we determine the best path to generate and test this table (#1653), I would like to merge in the updates. It's likely we'll have a 0.10 release in the very near future and want to make sure the documentation update has all of the new tutorials.
=> Update tutorial TOC

docs/tutorials/average_optimizers_callback.ipynb
Add a title to average_optimizers_callback.ipynb
=> Add title.

.github/workflows/make_wheel_Windows.sh, .github/workflows/release.yml
=> Remove unnecessary Bazel installations

tensorflow_addons/image/filters.py
Some minor documentation:
- returns 2D, 3D or 4D tensor
- typo for gaussian filter
=> DOC: unify doc of filters

.github/workflows/release.yml, CONTRIBUTING.md, tools/docker/cpu_tests.Dockerfile, tools/install_deps/tensorflow-cpu.txt, tools/install_deps/tensorflow.txt, tools/run_gpu_tests.sh
Also want to troubleshoot what is going on with broken master branch
=> Bump dependency to tf2.2rc4

.github/workflows/release.yml, tools/update_release_version.sh, update_release_version.sh
In the meantime that we centralize/refactor the versioning this script could be helpful.
`./update_release_version.sh 2.2.0rc5`
=> Add a small script to change version

README.md, tools/testing/source_code_test.py
=> Prohibit the use of tf.control_dependencies.

tools/testing/source_code_test.py
=> Prohibiting the use of tf.cond in the codebase.

tensorflow_addons/metrics/cohens_kappa.py
fix issue, https://github.com/tensorflow/addons/issues/1821
See code: https://colab.research.google.com/drive/1rLIKY0Y8VkzdsP71vUNvjIM-_XlJ_RZU?usp=sharing
=> Fix Cohen kappa 

tensorflow_addons/image/translate_ops.py
Translate x and y direction simultaneously rather than separately. Related to https://github.com/tensorflow/addons/issues/1724.
=> Translate x and y in only one call

tensorflow_addons/custom_ops/image/cc/kernels/adjust_hsv_in_yiq_op_gpu.cu.cc
Similar function defined in [stream_executor_util.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/stream_executor_util.h).
=> Use AsDeviceMemory from StreamExecutorUtil

tensorflow_addons/losses/contrastive.py, tensorflow_addons/losses/focal_loss.py, tensorflow_addons/losses/giou_loss.py, tensorflow_addons/losses/lifted.py, tensorflow_addons/losses/quantiles.py, tensorflow_addons/losses/triplet.py, tensorflow_addons/utils/keras_utils.py, tools/testing/source_code_test.py
=> remove internal modules

tensorflow_addons/layers/polynomial.py, tensorflow_addons/layers/tests/polynomial_test.py
It supports a low-rank kernel W = U * V, where U \in R^{last_dim x
projection_dim} and V \in R^{projection_dim x last_dim};
Introduces a flag diag_scale that increases the diagonal of kernel W by
diag_scale.
=> Incorporate low-rank techniques into DCN.

tensorflow_addons/optimizers/rectified_adam.py
=> Remove RAdam optional float total steps

tensorflow_addons/seq2seq/attention_wrapper.py, tensorflow_addons/seq2seq/tests/attention_wrapper_test.py
=> Fix AttentionWrapper type annotation for multiple attention mechanisms

tensorflow_addons/losses/focal_loss.py
=> fix docstring in focal loss

tools/docker/build_wheel.Dockerfile
This will be the same namespace that houses the dev docker image
=> Move docker image to new namespace

tensorflow_addons/seq2seq/beam_search_decoder.py, tensorflow_addons/seq2seq/tests/beam_search_decoder_test.py
=> Fixup returned cell state structure in BeamSearchDecoder

tensorflow_addons/seq2seq/beam_search_decoder.py, tensorflow_addons/seq2seq/tests/beam_search_decoder_test.py
Also update some related docstrings.
Closes #1868.
=> Allow resetting embedding_fn when calling BeamSearchDecoder

tensorflow_addons/seq2seq/basic_decoder.py, tensorflow_addons/seq2seq/beam_search_decoder.py
=> Add missing documentation for some output tuples

tensorflow_addons/seq2seq/tests/beam_search_decoder_test.py
This is more in line with how these functions would actually be called.
=> Use a tf.function with an input signature instead of tf.placeholder

tensorflow_addons/seq2seq/decoder.py, tensorflow_addons/seq2seq/tests/decoder_test.py
0 does not make much sense here and the function does not support this value in graph mode with non fully defined shapes.
=> Remove 0 as a valid value for maximum_iterations

tensorflow_addons/optimizers/stochastic_weight_averaging.py, tools/testing/source_code_test.py
Also: clean up the code a bit by replacing tf conds with regular python conditions.
=> Remove tf.control_dependencies from SWA

tensorflow_addons/losses/focal_loss.py
=> Fix docstring with incorrect API usage

tensorflow_addons/metrics/cohens_kappa.py, tensorflow_addons/metrics/tests/cohens_kappa_test.py
Here is a proposal to fix issue #1962
=> Fixes exception when batch_size=1

tensorflow_addons/optimizers/novograd.py, tools/testing/source_code_test.py
=> Use tf.raw_ops instead of private API for novograd

tensorflow_addons/metrics/README.md
The syntax for the test cases wasn't correct. Added more information regarding the implementation as well.
=> fix typos and examples for test cases

tensorflow_addons/optimizers/weight_decay_optimizers.py, tools/testing/source_code_test.py
Per https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md#bug-fixes-and-other-changes-5 and https://www.tensorflow.org/api_docs/python/tf/Tensor#experimental_ref.
=> Use .ref() instead of .experimental_ref()

tensorflow_addons/optimizers/conditional_gradient.py, tensorflow_addons/optimizers/lazy_adam.py
Much similar to what `tf.keras.optimizers.*` do.
=> Use optimizer method instead of raw op

tensorflow_addons/optimizers/moving_average.py, tools/testing/source_code_test.py
Just a wrapper of private API.
https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/keras/backend.py#L1619-L1633
=> Use tf.keras.backend.moving_average_update instead of private api

tensorflow_addons/image/color_ops.py, tensorflow_addons/image/cutout_ops.py, tensorflow_addons/image/tests/color_ops_test.py, tensorflow_addons/image/tests/cutout_ops_test.py
Reverts tensorflow/addons#1980
=> Revert "Drop data_format argument"

tensorflow_addons/image/color_ops.py, tensorflow_addons/image/cutout_ops.py
Per https://github.com/tensorflow/addons/pull/1980
=> Add deprecation warning

tensorflow_addons/metrics/utils.py
Hello!
I changed For Loop to Dict Comprehension.
Improved readability and improved performance.
Thank You!
=> CLEAN: For Loop -> Dict Comprehension

CONTRIBUTING.md
Hello!
I improved the `CONTRIBUTING.md` file using Language Tag (I don't know if this work is right)
Thanks!
=> EHN: Using Language Tag in CONTRIBUTING.md

tensorflow_addons/metrics/f_scores.py, tensorflow_addons/metrics/hamming.py, tensorflow_addons/metrics/matthews_correlation_coefficient.py, tensorflow_addons/metrics/multilabel_confusion_matrix.py, tensorflow_addons/metrics/r_square.py
Hello, TensorFlow Addons Community!
I removed a duplicate initial value generation call from `reset_state`
Thanks!
=> CLEAN: Remove Duplicated reset value

.github/CODEOWNERS
Hello, SIG-Addons!
I want to make continuous contributions including maintenance to the `tfa.metrics` Sub Pkg of `tfa`.
Thank You!
=> ADD CODEOWNER @marload

tensorflow_addons/metrics/tests/r_square_test.py
=> REFACTOR: Remove unused variable 'i'

tensorflow_addons/metrics/cohens_kappa.py
The existing code was duplicated and I have removed duplication.
Thank You!
=> REFACOTR: Remove Duplicate Function Call

tensorflow_addons/metrics/r_square.py
In Early Return Pattern, `if if return` is more recommended than `if elif else`.
Thank You! :)
=> REFACTOR: Early Returnn Pattern (if elif else -> if if return)

CONTRIBUTING.md
Per https://github.com/NVIDIA/nvidia-docker#usage
=> Use updated method for launching GPU containers

tensorflow_addons/layers/tlu.py
I removed duplication and reduced the number of lines in the code.
Thank you!
=> REFACTOR: Remove Duplicated Function Call

tensorflow_addons/optimizers/tests/weight_decay_optimizers_test.py, tensorflow_addons/optimizers/weight_decay_optimizers.py
Fixes #844
Fixes #865
Modelled after similar fixes for RectifiedAdam (PR: https://github.com/tensorflow/addons/pull/1974/commits/41b15efc84e6ce28f90a44c70ade8129048d55e7)
=> Issue #844: Fix weight_decay schedule support for DecoupledWeightDecayExtension

.github/CODEOWNERS
Please include a summary of the change and which issue is fixed. 
*
=> Add marload CODEOWNER

.github/pull_request_template.md
=> Streamline PR template

README.md
- [x ] Updated or additional documentation
*
=> Set TF 2.3 for nightly

tensorflow_addons/seq2seq/attention_wrapper.py
=> Fix Layer class name in docstring

tensorflow_addons/seq2seq/attention_wrapper.py, tensorflow_addons/seq2seq/decoder.py
RNNCell was the name of the abstract RNN cell in TF 1. We should remove it to avoid confusion.
*
=> Remove references to the "RNNCell" name

tensorflow_addons/optimizers/weight_decay_optimizers.py
This brings the TensorFlow Addons Optimizers up to date with the built-in Optimizers
=> Allow Optimizers to accept a loss tensor

tensorflow_addons/activations/gelu.py, tensorflow_addons/activations/hardshrink.py, tensorflow_addons/activations/lisht.py, tensorflow_addons/activations/mish.py, tensorflow_addons/activations/rrelu.py, tensorflow_addons/activations/snake.py, tensorflow_addons/activations/softshrink.py, tensorflow_addons/activations/sparsemax.py, tensorflow_addons/activations/tanhshrink.py, tensorflow_addons/conftest.py
An example for #2066.
doctest + build_docs
=> Doctest activations

tensorflow_addons/layers/multihead_attention.py, tensorflow_addons/layers/netvlad.py, tensorflow_addons/layers/normalizations.py, tensorflow_addons/layers/optical_flow.py, tensorflow_addons/layers/poincare.py, tensorflow_addons/layers/polynomial.py, tensorflow_addons/layers/snake.py, tensorflow_addons/layers/sparsemax.py, tensorflow_addons/layers/spatial_pyramid_pooling.py, tensorflow_addons/layers/spectral_normalization.py, tensorflow_addons/layers/tlu.py, tensorflow_addons/layers/wrappers.py
Beautifier layers doc. Our layers doc is also messy 😢.
*
=> Beautifier layers doc

tensorflow_addons/callbacks/average_model_checkpoint.py, tensorflow_addons/callbacks/tqdm_progress_bar.py
=> Beautifier callbacks doc

tensorflow_addons/layers/multihead_attention.py
=> Deprecate MultiHeadAttention

tensorflow_addons/image/color_ops.py, tensorflow_addons/image/compose_ops.py, tensorflow_addons/image/connected_components.py, tensorflow_addons/image/cutout_ops.py, tensorflow_addons/image/dense_image_warp.py, tensorflow_addons/image/distance_transform.py, tensorflow_addons/image/distort_image_ops.py, tensorflow_addons/image/interpolate_spline.py, tensorflow_addons/image/resampler_ops.py, tensorflow_addons/image/sparse_image_warp.py, tensorflow_addons/image/transform_ops.py, tensorflow_addons/image/translate_ops.py, tensorflow_addons/image/utils.py
=> Beautifier image doc

tensorflow_addons/seq2seq/attention_wrapper.py, tensorflow_addons/seq2seq/basic_decoder.py, tensorflow_addons/seq2seq/beam_search_decoder.py
Use "Attributes" block to document attributes.
=> Fix namedtuple generated documentation

tensorflow_addons/optimizers/average_wrapper.py, tensorflow_addons/optimizers/tests/moving_average_test.py
=> Add experimental_aggregate_gradients support

tensorflow_addons/image/tests/transform_ops_test.py, tensorflow_addons/image/tests/translate_ops_test.py, tensorflow_addons/image/transform_ops.py, tensorflow_addons/image/translate_ops.py, tensorflow_addons/image/utils.py
Fixes #2092. Cast to `image.dtype`.
Test on various dtype.
=> Fix unwrap dtype

tools/docker/build_wheel.Dockerfile
Add ENV for setuptools v50.0.0
Required for setuptools v50.0.0:
https://setuptools.readthedocs.io/en/latest/history.html#v50-0-0
https://github.com/pypa/setuptools/issues/2352
- [x ] Bug fix
- [ x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
- [ x] By running Black + Flake8
- [ x] By running pre-commit hooks
CI will test his :wink: 
*
=> Add env variable for Setuptools 50.0.0

CONTRIBUTING.md
Describe how to run doctest locally.
doc
=> Add doctest section

docs/tutorials/average_optimizers_callback.ipynb
- [] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
*
=> Correct a typo in average_optimizers_callback.ipynb

.github/CODEOWNERS, tensorflow_addons/optimizers/__init__.py, tensorflow_addons/optimizers/discriminative_layer_training.py, tensorflow_addons/optimizers/tests/discriminative_layer_training_test.py
Fixing minor issues from #969.
Update code owners
Fix typo in class name
=> fixed typo in multioptimizer class name and added code owners

tensorflow_addons/metrics/cohens_kappa.py, tensorflow_addons/metrics/f_scores.py, tensorflow_addons/metrics/geometric_mean.py, tensorflow_addons/metrics/hamming.py, tensorflow_addons/metrics/matthews_correlation_coefficient.py, tensorflow_addons/metrics/multilabel_confusion_matrix.py, tensorflow_addons/metrics/r_square.py
Canonicalize metrics docs.
For testable docstring:
- Naming convention: `y_true`, `y_pred`, `metric`, `result`.
- Use numpy array, which is the same with core TF.
For doc rendering:
- Put `Args` section between `class` and `__init__`, which is the same with core TF.
- Add `name` and `dtype` doc if applicable.
*
=> Canonicalize metrics docs

tensorflow_addons/layers/crf.py, tensorflow_addons/layers/multihead_attention.py, tensorflow_addons/layers/polynomial.py, tensorflow_addons/layers/spectral_normalization.py, tensorflow_addons/layers/wrappers.py
=> #2066-doc-update-layers-v1

CONTRIBUTING.md
Add information regarding feature requests needing ecosystem review prior to submitting pull requests.
cc @dynamicwebpaige @tomerk @tanzhenyu
=>  Add information on ecosystem review for new contributions

tensorflow_addons/optimizers/moving_average.py, tensorflow_addons/optimizers/tests/moving_average_test.py
Fixes # (issue)  https://github.com/tensorflow/addons/issues/2107
- [x ] Bug fix 
- [x ] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
- [x ] I have added tests that prove my fix is effective or that my feature works
Run unit-tests
=> Makes create_slots automatically setup weights for swap_weights

tensorflow_addons/seq2seq/attention_wrapper.py
=> #2066 seq2seq.beamsearch

.github/workflows/release.yml
Fix warning in https://github.com/tensorflow/addons/actions/runs/299787623. https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
*
=> Deprecate set env

tools/update_release_version.sh
Add support to update releases list
*
=> Add support to releases list

.github/workflows/ci_test.yml, .github/workflows/release.yml, README.md, setup.py, tools/docker/cpu_tests.Dockerfile, tools/docker/sanity_check.Dockerfile, tools/run_gpu_tests.sh
Remove python3.5 support as it is EOL and no longer supported by TF core.
Fixes #2183
=> Drop python3.5 support

tensorflow_addons/seq2seq/attention_wrapper.py
See #2197 for additional context.
Ran the existing tests.
=> Graduate _BaseAttentionMechanism to a public base class

tensorflow_addons/seq2seq/attention_wrapper.py, tensorflow_addons/seq2seq/basic_decoder.py, tensorflow_addons/seq2seq/beam_search_decoder.py, tensorflow_addons/seq2seq/decoder.py, tensorflow_addons/seq2seq/sampler.py
Using absolute reference to other classes `tfa.seq2seq.` will create a link in the online documentation.
=> Improve docstring format and cross-linking

tensorflow_addons/seq2seq/sampler.py
=> Improve sampler documentation, use doctest

tensorflow_addons/seq2seq/__init__.py, tensorflow_addons/seq2seq/attention_wrapper.py, tensorflow_addons/seq2seq/basic_decoder.py, tensorflow_addons/seq2seq/beam_search_decoder.py, tensorflow_addons/seq2seq/decoder.py, tensorflow_addons/seq2seq/loss.py, tensorflow_addons/seq2seq/sampler.py
See overview in https://www.tensorflow.org/addons/api_docs/python/tfa/seq2seq.
=> Improve single-line description for the module overview

tensorflow_addons/seq2seq/attention_wrapper.py
This documents a typical usage of the wrapper.
=> Add a doctest example for AttentionWrapper

tensorflow_addons/seq2seq/basic_decoder.py
This clarifies the standard usage of the class.
Related to #2207.
=> Add a doctest example for BasicDecoder

.github/workflows/release.yml
Fixes #2222 . Recently the default shell for windows must have changed to PowerShell and the nightly flag env was not propagating to the build step:
https://github.com/tensorflow/addons/pull/2225/checks?check_run_id=1339434783
This debug run with shell explicitly set shows that this fixes the problem:
https://github.com/tensorflow/addons/pull/2225/checks?check_run_id=1339447511
=> Fix Windows Nightly

tensorflow_addons/metrics/cohens_kappa.py
=> Fix typo and example

tensorflow_addons/image/tests/transform_ops_test.py
Slightly increase tolerance from 1e-7 to 1e-6 in gradient test to prevvent failure due to change in tf.gradient_checker_v2
- [ *] Bug fix
Was tested internally at Google.
*
=> Slightly increase tolerance from 1e-7 to 1e-6 in gradient test 

tensorflow_addons/image/color_ops.py, tensorflow_addons/image/cutout_ops.py, tensorflow_addons/image/tests/cutout_ops_test.py
Remove deprecated arguments
Part of https://github.com/tensorflow/addons/issues/2122
=> Remove deprecated data_format

tensorflow_addons/callbacks/tests/avg_model_checkpoint_test.py, tensorflow_addons/optimizers/average_wrapper.py, tensorflow_addons/optimizers/moving_average.py, tensorflow_addons/optimizers/stochastic_weight_averaging.py
Part of https://github.com/tensorflow/addons/issues/2122
=> Remove deprecated sequential update

CONTRIBUTING.md, tensorflow_addons/activations/README.md, tensorflow_addons/callbacks/README.md, tensorflow_addons/image/README.md, tensorflow_addons/layers/README.md, tensorflow_addons/losses/README.md, tensorflow_addons/metrics/README.md, tensorflow_addons/optimizers/README.md, tensorflow_addons/rnn/README.md, tensorflow_addons/seq2seq/README.md, tensorflow_addons/text/README.md, tensorflow_addons/utils/test_utils.py
Replace `tf.config.experimental_run_functions_eagerly` with `tf.config.run_functions_eagerly` as we have dropped TF2.2 support.
https://www.tensorflow.org/api_docs/python/tf/config/experimental_run_functions_eagerly
*
=> Replace with tf.config.run_functions_eagerly

tensorflow_addons/optimizers/average_wrapper.py, tensorflow_addons/optimizers/tests/moving_average_test.py
Fixes #2255 
New tests with preprocessing layer.
=> Warn users when it's unable to assign average slot

tensorflow_addons/callbacks/average_model_checkpoint.py, tensorflow_addons/callbacks/tests/avg_model_checkpoint_test.py, tensorflow_addons/optimizers/tests/moving_average_test.py, tools/testing/source_code_test.py
Fix bug when wrapper MovingAverage with LossScaleOptimizer 
*  
Added test case to verify it.
=> support loss scale optimizer

tensorflow_addons/image/color_ops.py
=> Remove tf.function decorator in tfa.image.equalize

tensorflow_addons/callbacks/average_model_checkpoint.py
=> add LossScaleOptimizerV1

README.md
=> Update nightly compatibility matrix

tensorflow_addons/losses/tests/quantiles_test.py, tensorflow_addons/optimizers/tests/lookahead_test.py, tensorflow_addons/utils/test_utils.py
Remove some old check for old tensorflow
Pass tests.
=> Remove support of TF<2.2

tensorflow_addons/image/cutout_ops.py
Remove unsupported data_format
Pass existing tests.
=> Remove unsupported data_format

README.md
=> Update default CUDA in doc

tensorflow_addons/layers/max_unpooling_2d.py
=> MaxUnpooling2D typing

tensorflow_addons/image/filters.py
Fix filters type hints.
- `filter_shape` accepts a scalar to represents the same width and height
- `image` accepts all types of tensor
- `constant_values` can either be a scalar tensor or a scalar so accepts `TensorLike`
=> Fix filters type hint

tensorflow_addons/image/cutout_ops.py, tensorflow_addons/image/tests/cutout_ops_test.py
Fix cutout in keras layer (graph and symbolic tensor).
=> Make cutout compatible with keras layer

tensorflow_addons/image/sparse_image_warp.py, tensorflow_addons/image/tests/sparse_image_warp_test.py
Resubmit of #446 with unittests. Closes #332.
Passes existing tests and new tests.
=> Support unknown rank image

tensorflow_addons/version.py
Remove suffix from 0.12 branch
=> Update version.py 0.12

tensorflow_addons/image/sparse_image_warp.py, tensorflow_addons/image/tests/sparse_image_warp_test.py
Fix for #2300. One leftover for old style code.
=> Fix sparse_image_warp partially unknown shape

tensorflow_addons/image/sparse_image_warp.py, tensorflow_addons/image/tests/sparse_image_warp_test.py
Backport failed:
https://github.com/tensorflow/addons/pull/2308#issuecomment-749280054
=> Image/fix sparse image warp unknown batch size - r0.12

tensorflow_addons/version.py
Bump to 0.13-dev
Marking WIP until 0.12 release goes smoothly
=> Update version.py -0.13

configure.py
Build with c++14. Sync with TF. Also, for cuda build, thrust requires c++14 to slience warning.
*
=> Build with c++14

tensorflow_addons/utils/types.py
Workaround for #2325. This also improves the readibility of type hints although the newly added types are subset of `Callable`. tfrs also uses the similar type hints for initializer and regularizer. There should be a better way to control type hints and aliases when generating docs.
https://github.com/tensorflow/recommenders/blob/main/tensorflow_recommenders/layers/dcn.py#L86-L91
*
=> Specify detailed types

setup.py, tensorflow_addons/utils/ensure_tf_install.py, tensorflow_addons/utils/resource_loader.py, tensorflow_addons/version.py
Small improvement on the variable names. Previously it was difficult to know that MAX_VERISON was not included.
=> Improve version check variable names

tensorflow_addons/layers/normalizations.py, tensorflow_addons/layers/tests/normalizations_test.py
=> Fix FilterResponseNormalization save

tensorflow_addons/metrics/__init__.py, tensorflow_addons/metrics/harmonic_mean.py, tensorflow_addons/metrics/tests/harmonic_mean_test.py
Fixes #2035 
Note: I have manually confirmed the correctness of the tests.
=> Implement Harmonic Mean and add tests

.github/CODEOWNERS, tensorflow_addons/layers/noisy_dense.py, tensorflow_addons/layers/tests/noisy_dense_test.py
Add support for Independent Gaussian noise to noisy_dense.py
=> Independent Gaussian noise

tensorflow_addons/losses/focal_loss.py, tensorflow_addons/losses/tests/focal_loss_test.py
Fixes #2343
- Fix y_true casting. tf.convert_to_tensor cannot convert a uint8 type to float32.
- Fix alpha, gamma casting by casting to y_true.dtype
- Consolidate tests.
=> Fix focal loss casting.

tensorflow_addons/image/dense_image_warp.py
=> Add note to remove the function

tensorflow_addons/image/transform_ops.py
=> Documentation fix

tensorflow_addons/seq2seq/attention_wrapper.py
The example code is split in 2 in the rendered documentation:
https://www.tensorflow.org/addons/api_docs/python/tfa/seq2seq/AttentionWrapper?hl=fr#example
N/A
=> Minor formatting fix for AttentionWrapper example

tensorflow_addons/optimizers/lookahead.py
Initialize the "slow" vars of the lookahead optimizer when adding the slot instead of during the first iteration.
Sine variables might not be present during the first initialization, so that they are never be initialized to the correct value with the old behavior.
Fixes #2351.
- x] By running Black + Flake8
@axeldavy tested the change in #2351. I ran a short training with the modified optimizer and confirmed that it still works.
=> Lookahead optimizer: Initialize slow vars when adding slot

tensorflow_addons/version.py
Updating patch version now that 0.12.1 was released
=> Bump patch version 0.12

README.md
Update compat matrix for 0.12.1 release
=> Update Compat Matrix

.github/workflows/release.yml, CONTRIBUTING.md, tensorflow_addons/activations/mish.py, tools/build_dev_container.sh, tools/docker/cpu_tests.Dockerfile, tools/install_deps/tensorflow-cpu.txt, tools/install_deps/tensorflow.txt, tools/run_gpu_tests.sh
Update to build against patch version since 2.4.1 included compilation changes.
=> Update to 2.4.1 dependency

tensorflow_addons/metrics/f_scores.py
The documentation formula has a typo. This commit makes it match the implementation and the [commonly accepted version](https://en.wikipedia.org/wiki/F-score).
Verified against Wikipedia and source.
=> Update F-Beta score formula documentation

tensorflow_addons/metrics/r_square.py, tensorflow_addons/metrics/tests/r_square_test.py
I notice that r2_score and RSquare works differently in managing "-inf":
```python
import tensorflow as tf
from tensorflow_addons.metrics import RSquare
from sklearn.metrics import r2_score
actuals = tf.constant([0, 0], dtype=tf.float32)
preds = tf.constant([1e-3, 1e-3], dtype=tf.float32)
actuals = tf.cast(actuals, dtype=tf.float32)
preds = tf.cast(preds, dtype=tf.float32)
r2_score(actuals, preds)  # return 0.0
m = RSquare()
m.update_state(actuals, preds)
m.result().numpy()  # return -inf
```
I've replaced "-inf" in `raw_scores` with 0 to comply with sklearn implementation.
*
=> Better mimic of RSquare sklearn implementation

tensorflow_addons/metrics/r_square.py, tensorflow_addons/metrics/tests/r_square_test.py
Fixes RSquare serialization.
Fixes #2389.
=> Fix RSquare serialization

tensorflow_addons/layers/gelu.py, tensorflow_addons/losses/kappa_loss.py
Deprecates things that should be deprecated in v0.12. GELU should be a mistake warning as there is no GELU layer in core TF.
*
=> Deprecate things that should be deprecated in v0.12

tensorflow_addons/image/filters.py, tensorflow_addons/layers/max_unpooling_2d.py
Unify `normalize_tuple` typing. Make type hints that uses `normalize_tuple` in addons the same. See https://github.com/tensorflow/addons/blob/master/tensorflow_addons/utils/keras_utils.py#L83-L93.
=> Unify normalize_tuple typing

tensorflow_addons/image/distort_image_ops.py, tensorflow_addons/image/tests/distort_image_ops_test.py
Do not cast to float32 when dtype is floating for `adjust_hsv_in_yiq`.
=> Do not cast to float32 when dtype is floating

tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op.cc, tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op.h, tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op_gpu.cu.cc, tensorflow_addons/custom_ops/image/cc/ops/image_ops.cc, tensorflow_addons/image/distance_transform.py, tensorflow_addons/image/tests/distance_transform_test.py
@WindQAQ  I need your help since you are good at tensorflow internals.
Original implementation https://github.com/fsx950223/EDT
EDT based on http://www.theoryofcomputing.org/articles/v008a019/v008a019.pdf whose time complexity is O(n).
Fix https://github.com/tensorflow/addons/issues/2399
*
=> Optimize EDT

.github/ISSUE_TEMPLATE/feature-request.md, CONTRIBUTING.md
Adding two new guidelines to CONTRIBUTING.md
Fixes #2194
*
=> New contributions guidelines

configure.py
Fixes https://github.com/tensorflow/addons/issues/2439
Fixes build failure on Linux RHEL7/RHEL8 ppc64le architectures.
Main reason for the failure was that `-mavx` was getting added for linux ppc64le too which needs to be filtered out if the arch is ppc64le. So, I've added that check. Additionally I've added functions to detect other architectures too. But I've not used them as I don't have those systems to test the changes.
*
=> Fixed build on ppc

tensorflow_addons/seq2seq/attention_wrapper.py
This PR corrects the spelling of the word `Bahdanau` in the following functions:
- `BahdanauMonotonicAttention`
- `_bahdanau_score`
File: `tensorflow_addons/seq2seq/attention_wrapper.py`
=> Correct Spelling Of the word Bahdanau

tensorflow_addons/optimizers/novograd.py, tensorflow_addons/optimizers/tests/novograd_test.py
Brief Description of the PR: make NovoGrad optimizer working with float64 layers
Fixes #2465
* Just made sure float64 variables are passed to optimizer functions during testing (it fails w/out the fix)
=> Fix NovoGrad optimizer to work with float64 layers

tensorflow_addons/optimizers/cocob.py
=> Initialized `lr` with a small value

README.md
=> Update Compatibility Matrix

tensorflow_addons/version.py
=> Bump master branch to 0.14

setup.py
=> Update PyPI Py Versions

setup.py
=> Update pypi versions - 0.13

tensorflow_addons/version.py
=> Update 0.13 Patch Version

tensorflow_addons/custom_ops/layers/cc/kernels/embedding_bag_backward_kernels.cu.cc, tensorflow_addons/layers/embedding_bag.py
=> Fix embedding bag gpu kernel

docs/tutorials/average_optimizers_callback.ipynb
Fix some typos in a tutorial notebook.
*
=> Fix some typos

configure.py
This PR modifies configure.py to recognize `os.uname()[4]` machine hardware identifier `aarch64` for the Raspberry Pi addition to `armv7l` .
#2539
Build from source completed without error on a Raspberry Pi 4 8GB running 64-Bit Raspberry Pi OS.
*
=> Modify configure.py to recognize 'aarch64' for 64-Bit Raspberry Pi OS

tensorflow_addons/version.py
=> Bump to 0.15

tensorflow_addons/losses/focal_loss.py
=> Documentation fixes

.github/CODEOWNERS
=> Add a codeowner for CRF

tensorflow_addons/losses/sparsemax_loss.py
=> Fixed documentaion typo

tensorflow_addons/losses/quantiles.py
Fix minor punctuation error in docs for pinball loss.
No need for testing; docs only.
=> Fix minor grammar error in docs

.github/workflows/release.yml
Fixes https://github.com/tensorflow/addons/pull/2559#issuecomment-916930613
/cc @bhack
=> Fix ARM wheel uploading in release script

.github/workflows/release.yml
Cherry pick of #2565
/cc @bhack
=> [r0.13: cherry-pick] Fix ARM wheel uploading in release script

.github/workflows/release.yml
Cherry pick of #2565
/cc @bhack
=> [r0.14: cherry-pick] Fix ARM wheel uploading in release script

tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op.h
=> fix edt float16 kernel

tensorflow_addons/activations/snake.py
Brief Description of the PR: This PR will correct the documentation for the Snake activation function to make it consistent with the original literature and the cod written
Fixes #2571 
NA
=> Correct documentation for Snake activation to match literature and return statement

tensorflow_addons/text/crf.py, tensorflow_addons/text/tests/crf_test.py
=> bugfix for issue #2476

tensorflow_addons/layers/spectral_normalization.py, tensorflow_addons/layers/tests/spectral_normalization_test.py
=> fix mixed precision

tensorflow_addons/text/skip_gram_ops.py
=> remove useless args

.github/workflows/make_wheel_macOS_arm64.sh, .github/workflows/make_wheel_macOS_x86.sh
Attempt to fix broken CI. Can't find release notes for delocate 0.10 but I think the timeline lines up.
=> Pin delocate version

tensorflow_addons/version.py
=> Drop dev from 0.15

tensorflow_addons/version.py
=> Update version.py to 0.16

tensorflow_addons/seq2seq/tests/decoder_test.py
Providing trackable objects is now recommended for the users. This makes the
concrete function conversion API be based on the new SavedModel importer, which
will enable new TensorFlow Lite features including variable support, resources
and variant tensor, and signature concept.
- [V] New Seq2seq addition and the changes conform to the [seq2seq contribution guidelines](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/seq2seq/README.md#contribution-guidelines)
- [V ] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md#coding-style)
*
=> Update TFLite concrete function conversion codes to have the associated

.github/workflows/release.yml
=> Use same tf-macos version

.github/workflows/ci_test.yml, .github/workflows/validate_codeowners.yml
With the new system of notification (the bot token being a github actions secret), all workflows that need it must be either:
* a run from a commit in the repo tensorflow/addons, so the master branch or a release branch
* a pull_request_target workflow, which allows a fork to trigger a worflow that uses the token, but the code running this workflow is the code from the latest commit from the tensorflow/addons repo (to avoid arbitrary code execution).
Which means that with the current setup, executing the "Validate codeowner" workflow in a pull request means having it as a "pull_request_target", which means checking the latest commit of the master branch. So not very useful. 
In later PRs, what we can do is fetching the commit that triggered the PR and use the …
=> 🐛  Fix the CI job validating the codeowners

tensorflow_addons/seq2seq/attention_wrapper.py
Remove one of the private import of tf.keras
https://github.com/tensorflow/tensorflow/issues/28601
*
=> Remove one of the private import of tf.keras

tensorflow_addons/callbacks/tests/avg_model_checkpoint_test.py, tensorflow_addons/layers/tests/noisy_dense_test.py, tensorflow_addons/layers/tests/stochastic_depth_test.py, tensorflow_addons/seq2seq/tests/attention_wrapper_test.py, tensorflow_addons/seq2seq/tests/decoder_test.py, tensorflow_addons/utils/test_utils.py
Replace all usages of the experimental mixed precision Keras API with the non-experimental version. The experimental API is deprecated and will be removed in TensorFlow 2.9
Ran the unit tests.
=> Switch to non-experimental mixed precision API.

tools/install_deps/pytest.txt
=> Upgrade scikit-image

configure.py
=> add build support for tf2.9

configure.py
I found configure.py has already defined TF_CXX11_ABI_FLAG, so I removed redefined environment variable.
*
=> remove useless code

tensorflow_addons/metrics/r_square.py, tensorflow_addons/metrics/tests/r_square_test.py
Hello,
`y_shape` can be determine automatically, not manually typed by user.
Thanks.
=> AUTOTUNE 'y_shape'

tools/docker/build_wheel.Dockerfile
Need to ensure CI passes on this as we had issue on last release
=> Update build_wheel.Dockerfile for r0.17

tensorflow_addons/version.py
=> Update r0.17 version suffix

.github/workflows/release.yml, CONTRIBUTING.md, WORKSPACE, tools/build_dev_container.sh, tools/docker/cpu_tests.Dockerfile, tools/install_deps/tensorflow-cpu.txt, tools/install_deps/tensorflow.txt, tools/run_gpu_tests.sh
Returning CI... first time with codespace access :)
=> Update patch releases for breaking protobuf

configure.py, tensorflow_addons/custom_ops/image/cc/kernels/euclidean_distance_transform_op.h
=> Fix delete behavior

.github/workflows/release.yml, CONTRIBUTING.md, README.md, WORKSPACE, tensorflow_addons/image/color_ops.py, tools/build_dev_container.sh, tools/docker/cpu_tests.Dockerfile, tools/install_deps/tensorflow-cpu.txt, tools/install_deps/tensorflow.txt, tools/run_gpu_tests.sh
=> Update patch releases on 0.17

.github/workflows/release.yml
Add Python 3.10 support for `r0.17`.
No new test cases are required, just a new whl file is added.
=> Add Python 3.10 support for `r0.17` of Apple silicon.

tensorflow_addons/version.py
=> bump 0.17.1 version

tensorflow_addons/register.py
fix a typo in `register_all` docs: `tf.tf` -> `tf`.
https://www.tensorflow.org/addons/api_docs/python/tfa/register_all
This doesn't need test.
=> fix a typo in `register_all` docs

.github/CODEOWNERS
Update code owners to reflect https://github.com/tensorflow/addons/pull/2741
=> Update code owners for `streaming_correlations.py`

tensorflow_addons/metrics/streaming_correlations.py
Optimizes `SpearmansRank`'s metric computation
=> Optimization in `SpearmansRank` computation

tensorflow_addons/metrics/tests/streaming_correlations_test.py
Fix the unit tests for correlation metrics when using keras v2.10.
=> Correlation metrics keras2.10 fix

tensorflow_addons/callbacks/tests/avg_model_checkpoint_test.py, tensorflow_addons/optimizers/tests/moving_average_test.py, tensorflow_addons/optimizers/tests/weight_decay_optimizers_test.py, tensorflow_addons/optimizers/weight_decay_optimizers.py
fix optimizer-related failures for TF 2.11
=> fix optimizer failures for tf 2.11

tensorflow_addons/rnn/esn_cell.py
Change `self.spectral_radius` for `tf.cast(self.spectral_radius, dtype)` in lines `146` and `152`.
Change the spectral radius of `esn_cell.py`. More info in the following link:
https://github.com/tensorflow/addons/issues/2792
@bhack 
Tested in the following code:
https://gist.github.com/muriloasouza/6b928d762fbbd2f748c68bc99eaf8382
Before this change, the code didn't work.
Heres the csv file:
https://gist.github.com/muriloasouza/5f97167faf7a066cf2ad2858fbd4b1f5
*
=> Update spectral_radius in esn_cell.py

configure.py
Before the PR, `configure.py` writes the 
```
build --cxxopt="-D_GLIBCXX_USE_CXX11_ABI="0
```
This PR,
```
build --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"
```
*
=> Fix D_GLIBCXX_USE_CXX11_ABI

build_deps/toolchains/gpu/crosstool/BUILD.tpl, tensorflow_addons/BUILD, tensorflow_addons/callbacks/tests/tqdm_progress_bar_test.py, tensorflow_addons/image/tests/connected_components_test.py, tensorflow_addons/testing/tests/serialization_test.py, tensorflow_addons/text/tests/crf_test.py, tools/install_deps/doc_requirements.txt, tools/install_deps/pytest.txt
Test suite has several uses of np.bool and np.int which are no longer in the most recent version of numpy.
=> Fix Test Suite

tensorflow_addons/metrics/matthews_correlation_coefficient.py
Fix MCC formula typo in documentation
NA
=> Fix MCC formula typo

tensorflow_addons/optimizers/average_wrapper.py, tensorflow_addons/optimizers/lookahead.py
=> fix wrong hints

requirements.txt, tensorflow_addons/__init__.py, tensorflow_addons/utils/tfa_eol_msg.py
=> Print EOL warning on import

README.md
=> Add EOL to README.md

.github/workflows/release.yml
Add py38 macos arm74. Was accidently removed during build setup
=> Add py38 macos arm64

.github/workflows/release.yml
=> Add py38 macos arm64 to r0.21

tensorflow_addons/version.py
=> Increase version to 0.22

README.md
Uses github action new badge url
=> Update README.md - New badge url
